### ISSUE TITLE
spot data is not update from 2021/12/11

### ISSUE THREAD

**Issue by alexkuan0911** [binance/binance-public-data#100]
Is the spot data postponed to upload?

**Comment by Yurservice** [comment]
Yes, it hasn`t updated yet.

**Comment by houhashv** [comment]
when will the data be updated again, and those the api: GET /api/v3/historicalTrades is updated?

**Comment by Yurservice** [comment]
Does anyone have any information about the problem?

**Comment by Yurservice** [comment]
It`s been updated now

**Comment by chairz** [comment]
Data should be updated as of now.
