### ISSUE TITLE
Data before March 1,2021

### ISSUE THREAD

**Issue by Ricardo1902** [binance/binance-public-data#102]
Good afternoon, 

I am kind of new on this, and first thanks for this public data.  I would like to know, where can I find the data before March 3, 2021 for all the crypto currencies.

Thanks a lot for your answer.

**Comment by chairz** [comment]
What do you mean by that? If you can't find the data before a certain period of time, it means that the crypto is yet to be trading on Binance.

**Comment by excme** [comment]
> What do you mean by that? If you can't find the data before a certain period of time, it means that the crypto is yet to be trading on Binance.

The problem is on all cryptocurrencies haven't files in DAILY folders earlier March 2021

**Comment by pantonis** [comment]
@excme Did you find the date prior to that date?

**Comment by excme** [comment]
> @excme Did you find the date prior to that date?
I lost the context. What is the question?

**Comment by pantonis** [comment]
How can we get trade data before 2021-02-28?

**Comment by excme** [comment]
> How can we get trade data before 2021-02-28?

If you haven't files in daily and monthly folders, you can use api

**Comment by pantonis** [comment]
ok thanks I will give it a try. Does it happen to know how back data go?

**Comment by excme** [comment]
> ok thanks I will give it a try. Does it happen to know how back data go?

Don't understand

**Comment by pantonis** [comment]
what is the first datetime of the trade data that can be requested via API.

**Comment by excme** [comment]
> what is the first datetime of the trade data that can be requested via API.

Each сoin has its own start date for trading. Request tick #1 and inside you will see the date
