### ISSUE TITLE
Intraday daily file, updated every hour

### ISSUE THREAD

**Issue by wolfram265** [binance/binance-public-data#11]
Hi,

Could you arrange/offer intraday data download?
With the current limits, it takes about 2000-3000 REST call to download intraday trades data on high volume pairs.

If there would an intraday (daily) download zip, updated every hour for example, that would lower the number of REST requests significantly.

**Comment by Ninj0r** [comment]
We have plans to offer daily zip files but no plans to offer hourly zip files at this time.

**Comment by wolfram265** [comment]
You already offering daily zip files.
The idea is to offer intraday/current day daily zip file, updated every hour (for example).
