### ISSUE TITLE
一些逐笔数据缺失

### ISSUE THREAD

**Issue by Legend94rz** [binance/binance-public-data#114]
我只看了2020年 BTCUSDT 的逐笔交易，缺失的时间段如下，只记了缺失开始和结束时间，其他交易对或其他年份可能也有：
UTC时间
2020-02-09 02:00 - 2020-02-09 02:59
2020-02-19 11:36 - 2020-02-19 17:29
2020-03-04 09:22 - 2020-03-04 11:29
2020-04-25 02:00 - 2020-04-25 04:29
2020-06-28 02:00 - 2020-06-28 05:29
2020-11-30 06:00 - 2020-11-30 06:59
2020-12-21 13:48 - 2020-12-21 17:59
2020-12-25 02:00 - 2020-12-25 02:59

**Comment by 2pd** [comment]
请问是合约还是现货的， 如果有下载的文件的路径最好，我们可以看一下。
谢谢

**Comment by Legend94rz** [comment]
是现货的，就是用这个脚本下载的。我[这里](https://personalm365-my.sharepoint.com/:u:/g/personal/legend94rz_personalm365_onmicrosoft_com/EUhbz26uqZdLlP9RfYJimxwBLgiqD0aGzf2Imqro2TZLFQ?e=qJYrI6)已经下载好了一个2020.2月份BTCUSDT的逐笔，跟这个脚本下载是一样的，仅供参考。

**Comment by 2pd** [comment]
请提供一下你看的具体是daily的还是monthly的？ trade的数据？
具体是哪个下载文件？

**Comment by Legend94rz** [comment]
monthly 的逐笔数据，下载到的文件名是 `BTCUSDT-trades-2020-02.zip`。

**Comment by 2pd** [comment]
我看了一下，数据没有问题。 
BTCUSDT在这两个trade中间的时间gap是因为系统维护，没有trades。

```
241644724,9938.90000000,0.00117600,11.68814640,1581213592369,False,True
241644725,9938.86000000,0.05925500,588.92714930,1581217201792,False,True
```

你要看trade id是不是连续的，而不是看时间有没有gap。
