### ISSUE TITLE
Data wrong

### ISSUE THREAD

**Issue by freedev82** [binance/binance-public-data#115]
I am analyzing the historical data to see if it is correct.
However, it was confirmed that quite a lot of data were incorrect.
The incorrect data below is one of them.
Please let me know why I am getting the wrong result.

**- API DATA**
https://api3.binance.com/api/v3/klines?symbol=ACMUSDT&interval=1m&startTime=1639496580000&endTime=1639496580999&limit=1

```
[
[[1639496580000,"5.14000000","5.14000000","5.14000000","5.14000000","26.40000000",1639496639999,"135.69600000",1,"0.00000000","0.00000000","0"]]
]
```

Volume: 26.4

**- binance public data**

FileName: ACMUSDT-1m-2021-12-14.csv
![image](https://user-images.githubusercontent.com/6703718/154826630-9d5a4599-025f-48f5-823c-69390a805c81.png)

Volmue: 34.9

**Comment by 2pd** [comment]
do you have other examples for us to investigate please? thanks

**Comment by freedev82** [comment]
**- API DATA**
https://api3.binance.com/api/v3/klines?symbol=1INCHUSDT&interval=1m&startTime=1617274200000&endTime=1617274499999


```
[
  [ 1617274200000, "4.36290000", "4.36710000", "4.36240000", "4.36240000", "664.43000000", 1617274259999, "2899.63627500", 14, "228.98000000", "999.97855800", "0" ],
  [ 1617274260000, "4.35900000", "4.36180000", "4.35020000", "4.35020000", "5652.85000000", 1617274319999, "24610.92919200", 48, "623.36000000", "2717.07402300", "0" ],
  [ 1617274320000, "4.35080000", "4.35700000", "4.34360000", "4.35470000", "4728.26000000", 1617274379999, "20565.61920800", 87, "2319.79000000", "10092.58445300", "0" ],
  [ 1617274380000, "4.35470000", "4.35800000", "4.34020000", "4.34040000", "7422.79000000", 1617274439999, "32262.90776300", 128, "1782.65000000", "7765.57295100", "0" ],
  [ 1617274440000, "4.34610000", "4.35420000", "4.34400000", "4.35090000", "3472.97000000", 1617274499999, "15112.36711700", 60, "1711.91000000", "7450.52380300", "0" ]
]
```

---

**- binance public data**
FileName: 1INCHUSDT-1m-2021-04-01.csv

![image](https://user-images.githubusercontent.com/6703718/156598476-d7ccf783-6752-4397-acb2-904e065a1856.png)


---

FileName: 1INCHUSDT-5m-2021-04-01.csv

![image](https://user-images.githubusercontent.com/6703718/156598694-635c0a9f-8225-421e-bc33-acf0e7c3717b.png)


---


The sum of the volume of the 1 minute candle and the volume of the 5 minute candle do not match.
Please check the data. And please tell me the result of the check.

**Comment by 2pd** [comment]
thanks, we are still looking.

**Comment by Mag641** [comment]
Any updates?

**Comment by 2pd** [comment]
we are working on finding a solution to identify and fix the broken klines, however due to the size of the data, it may take a while.

thanks for your patience.

**Comment by 2pd** [comment]
This should be fixed. Please download the latest file.
