### ISSUE TITLE
BTCUSDT Futures trades data contains parts that are inconsistent

### ISSUE THREAD

**Issue by argalasjr** [binance/binance-public-data#12]
Downloaded file  BTCUSDT-trades-2020-08.csv

HEAD of file (first 10 rows)
173525189,11343.67,0.467,5297.49,1596240000519,true
195900282,11685.02,0.001,11.68,1598838277312,true
173525190,11343.67,1.428,16198.76,1596240000519,true
195900283,11685.02,0.004,46.74,1598838277375,true
173525191,11343.2,0.002,22.68,1596240000519,true
195900284,11685.02,0.005,58.42,1598838277386,true
173525192,11343.1,0.01,113.43,1596240000519,true

Issue: every other row contains data from Aug 31

PS: found similar inconsitencies on BTCUSDT futures trades data on months March, April, May, September, October, December

**Comment by 2pd** [comment]
will forward to the team, thanks for feedback.

**Comment by 2pd** [comment]
should be fixed, please try again.
