### ISSUE TITLE
Daily File generation time zone

### ISSUE THREAD

**Issue by salmasi** [binance/binance-public-data#121]
hi
first i check time with http://worldclockapi.com/api/json/utc/now and this is not depend my local time zone
i check daily file generation in utc time, i think the file generated in one tick after 23:59:59 utc time in all time frame but the file generated UTC+1 time zone
first i think this is file generation latency but when check binance app i saw the daily candle close in UTC+1 in the app too,
why daily candle not close in the end of UTC day?
is Binance work in another time zone?

**Comment by chairz** [comment]
Binance market data are based UTC timezone. Can you provide more information on your findings?
