### ISSUE TITLE
Binance Futures Data Vision broken

### ISSUE THREAD

**Issue by excme** [binance/binance-public-data#122]
![image](https://user-images.githubusercontent.com/13168074/157464493-cfa0a3d4-07cb-418b-afae-538148008c30.png)
https://data.binance.vision/?prefix=data/futures/um/daily/trades/ETHUSDT/

![image](https://user-images.githubusercontent.com/13168074/157464660-a921db2e-102c-4ab2-bd90-8f8dbc1c9774.png)
https://data.binance.vision/?prefix=data/futures/um/daily/trades/BTCUSDT/

Futures folders with trades and aggTrades have bug and haven't data since March 6th

**Comment by 2pd** [comment]
Some of futures data were re-uploaded recently and their LastModified has been updated, which caused the sorting issue.
We are working on finding a solution to sort the items, however latest zip files are uploaded every day.

**Comment by Shattenjagger** [comment]
Hello. There is another connected issue in my opinion. The https://data.binance.vision/?prefix=data/futures/um/monthly/klines/BTCUSDT/15m/ are unavalable for March. The same happened with all of available timeframes I believe.

**Comment by 2pd** [comment]
It seems it took us a little extra time for this monthly data, but it's able to download now, please try.
