### ISSUE TITLE
data.binance.vision is not working correctly

### ISSUE THREAD

**Issue by sleepymatto** [binance/binance-public-data#123]
Hello

Something weird is going on with data.binanace.vision. Seems like a bunch of historical data is no longer available or it was deleted on the /daily/aggTrades. Also it is not being updated daily as it usually is. For example, BTCUSDT last update was 2021-05-13.

https://data.binance.vision/?prefix=data/futures/um/daily/aggTrades/BTCUSDT/

![image](https://user-images.githubusercontent.com/62895862/158028066-b27642de-1094-4848-8331-b12e5809e824.png)

**Comment by chairz** [comment]
The daily data is available, you can use the find function to search for the file. The files are not sorted well. Sorry for any inconvenience caused.

**Comment by sleepymatto** [comment]
Ah yes I see it now. Thanks!!
