### ISSUE TITLE
README.md may need an update.

### ISSUE THREAD

**Issue by volkan-akkus-tr** [binance/binance-public-data#124]
Thank you for the documentation. It was useful. 

I have listed some minor points, below.

- It is not mentioned that daily data is also served.
- "... is downloaded from /api/v3/..."  is not useful in this context.
- url and file format definitions and samples don't include daily files.
- "All intervals are supported" is not true for every data type.

**Comment by chairz** [comment]
It is not mentioned that daily data is also served.
- Will update this accordingly.

"... is downloaded from /api/v3/..." is not useful in this context.
- This is to explain where we get the data for the zip files.

url and file format definitions and samples don't include daily files.
- Daily file comes from the directory /daily and the file name has its date appended. For example, https://data.binance.vision/data/spot/daily/aggTrades/1INCHBTC/1INCHBTC-aggTrades-2022-03-14.zip
This is a link to download 1INCHBTC-aggTrades for 2022-03-14

"All intervals are supported" is not true for every data type.
- Can you name the symbols that doesn't support all intervals?

**Comment by volkan-akkus-tr** [comment]
There are different number of intervals for these, for example.

https://data.binance.vision/?prefix=data/spot/monthly/klines/1INCHBTC/
https://data.binance.vision/?prefix=data/spot/daily/klines/1INCHBTC/

**Comment by chairz** [comment]
You can't have intervals that are more than a day for daily files.

**Comment by volkan-akkus-tr** [comment]
you are right.

**Comment by 2pd** [comment]
We updated the readme doc to mention that daily data is provided.

**Comment by volkan-akkus-tr** [comment]
Thank you.
