### ISSUE TITLE
Would column explanations for AggTrade, Kline and Trade objects be helpful for newcomers ?

### ISSUE THREAD

**Issue by volkan-akkus-tr** [binance/binance-public-data#125]
Hi there, thank you for your efforts.

As a newcomer, I felt a need for more information about columns of AggTrade, Kline and Trade objects.

I think it would be great If there are some leads to learn more details about them.

If there is another source for it, it would be enough to have some link.

Thank you.

**Comment by chairz** [comment]
https://binance-docs.github.io/apidocs/spot/en/#market-data-endpoints

The information for the columns are explained on the documentation. You can refer to it above.

**Comment by volkan-akkus-tr** [comment]
I could not see any explaination for columns. 
Could you help me to find the exact line? 
thank you.

**Comment by volkan-akkus-tr** [comment]
I leave following links for people like me.

https://dev.binance.vision/t/beginners-guide-to-quoteorderqty-market-orders/404
https://www.reddit.com/r/algotrading/comments/81xd6n/can_someone_explain_a_trades_maker_and_best_match/
https://www.reddit.com/r/BinanceExchange/comments/96iymr/api_nomenclature_taker_buy_base_asset_volume_vs/?sort=new
https://money.stackexchange.com/questions/90686/what-does-buyer-is-maker-mean

**Comment by volkan-akkus-tr** [comment]
I am still looking for what "Was the trade the best price match" column of AggTrade means...

**Comment by Ipan1988** [comment]
If you notice, all values are TRUE so this column doesn't matter, just delete it.

**Comment by volkan-akkus-tr** [comment]
Thanks.
