### ISSUE TITLE
Differences between daily and monthly data for Kline 1m BTCUSDT.

### ISSUE THREAD

**Issue by volkan-akkus-tr** [binance/binance-public-data#129]
I have downloaded and compared Kline 1m data for BTCUSDT between 2021-03-01 and 2022-03-01. 
I have found differences between them as listed in the attached file.

[diff_Kline_1m_BTCUSDT.txt](https://github.com/binance/binance-public-data/files/8356348/diff_Kline_1m_BTCUSDT.txt)

**Comment by chairz** [comment]
What differences? why are u comparing 2 different years of data?

**Comment by volkan-akkus-tr** [comment]
- " What differences? "
They are listed in the attached file as mentioned in the second sentence of my entry, like "I have found differences between them as listed in the attached file". It is clear that you have not even read the second line not even realizing there is a file attached, aside.

- "why are u comparing 2 different years of data?"
That is not two different years but a period between two different years.
Short answer is "why not". Long one is for data accuracy.

-------------------------------------------------------------------

Following is my personal opinion and feelings after reading all issues in this project and making a preliminary data consistency check. You don't have to answer. Positive criticism is my goal not fighting.

First of all, I really appreciate your efforts to prepare ready-to-use zip files for us. It really speeds our workflow up. Thank you. We will establish algorithmic trading strategies by using your data. Instead of downloading via api, we have preffered to give a chance for ready-to-use zip files.

However, you are adding an extra step to the process. You download data via api then zip it. This may or may not create issues about data accuracy. It needs to be checked. Data accuracy is the fundamental requirement for algorithmic trading. It may cost months of efforts.

There are troubles in your data. I have found some by comparing your daily data vs monthly data. They are both prepared by you, served by you. You may see some of them in the attached file. The reason of their existence should be your main concern, immediately. These errors make your data dirty and worthless. Besides your efforts goes to dumpster.

Your team is not acting pro-actively about these issues. After someone proves that there is trouble, you would check and solve it. There are proofs in Issues section.

Your team acts like they dont wanna hear about problem. It makes me feel like they are not very volunteer to see any trouble from this project, this project is a burden for you and may be doomed. One proof is your answer, above.
