### ISSUE TITLE
Lots of 0.00 in futures orderbook qty

### ISSUE THREAD

**Issue by cchicote** [binance/binance-public-data#131]
Hi everyone !

I've been playing with Binance's API for the last few days, and after retrieving future orderbooks with the script given in the github repository (binance/binance-public-data/tree/master/Futures_Order_Book_Download) for pretty common coins (BTCUSDT and ETHUSDT) i've noticed a lot of `0.00` in the `qty` column.

It's written in the github repo that the data may have gapes, but it seems that there are a lot of `0.00` in this column.

Since there's nothing about the `0.00` in the `qty` column, I was wondering that maybe you guys would know ! 

Thanks a lot,
Take care

**Comment by 2pd** [comment]
script of `Futures_Order_Book_Download` is used to download "futures orderbook level 2 data", which is orderbook ticker by ticker data.  The `0.00` in the order book means the price depth is gone from the orderbook.

You can observe the similar results in the websocket stream "Diff. Book Depth Streams"

https://binance-docs.github.io/apidocs/futures/en/#diff-book-depth-streams

**Comment by cchicote** [comment]
Thanks a lot, it makes sense now ! 

Is this information available publicly anywhere online ?

**Comment by 2pd** [comment]
The API document has everything related to API development.
