### ISSUE TITLE
Futures order book data is corrupted.

### ISSUE THREAD

**Issue by seongs1024** [binance/binance-public-data#138]
Corrupted is futures order book data downloaded by `Futures-order-book-Level2-data-download.py`.

Awkward folders and files are contained in the compressed data file and the file size of `_depth_update.csv` looks wrong.
![image](https://user-images.githubusercontent.com/56729421/165126096-e0fc24b1-c6e2-42ea-8f5d-306a9c7bdf6b.png)

```python
# Specify the four input parameters below:
symbol = "BTCUSDT"  # specify the symbol name
startTime = 1648771200000  # specify the starttime
endTime = 1650758399000  # specify the endtime
dataType = "T_DEPTH"  # specify the dataType to be downloaded
```
They are configurations (`startTime` is Apr. 1st, 2022 and `endTime` is Apr. 23rd, 2022)

**Comment by 2pd** [comment]
Thanks for the feedback, could you please give us more details for investigation?

**Comment by seongs1024** [comment]
Oh valid data have been received!
