### ISSUE TITLE
Issues with FUTURES BTCUSDT AggTrade History

### ISSUE THREAD

**Issue by CaymanTurtleBeach** [binance/binance-public-data#139]
I believe there are issues with BTCUSDT AggTrade events in monthly AggTrade files. For example (from October 2021):
AggTradeId  |  Price      | Qty      | First Trade Id   | Last Trade Id   | Timestamp | formatted time
--------------|-----------|---------|-----------------|----------------|--------------| ----------------
847587457 | 46000 | 0.035 | 1495468737 | 1495468739 | 1633084069237 | 2021-10-01 10:27:49.237Z
847587458 | 45385.51 | 0.001 | 1495468740 | 1495468740 | 1633084069237 | 2021-10-01 10:27:49.237Z
847587459 | 46000 | 19.94 | 1495468741 | 1495468753 | 1633084069237 | 2021-10-01 10:27:49.237Z
847587460 | 45385.51 | 0.08 | 1495468754 | 1495468754 | 1633084069237 | 2021-10-01 10:27:49.237Z
847587461 | 46000 | 0.2 | 1495468755 | 1495468755 | 1633084069237 | 2021-10-01 10:27:49.237Z

The event Ids are consecutive, as expected. However, the price difference between these AggTrade events is an oscillating value of $614.49. There should not be such a wide price discrepancy, in different directions, happening at the same time.

Is this indicative of a fundamental problem with the matching engine, or is it a problem in logging?

From October 2021 through March 2022 there are around 1200 agg trade events out of 309187707 total events that exhibit similar anomalous behavior. I would appreciate an explanation.
Thanks.

**Comment by 2pd** [comment]
After reviewing, there is no issue of the data, it's caused by large price variation.

Thanks

**Comment by CaymanTurtleBeach** [comment]
With respect, of course there were large price variations in the AggTrades I listed. **BUT** with the real time liquidity of the order book for BTCUSDT, I am surprised that you would say the order book actually contained such a range of bid-ask prices for the quantities (slightly over 20 BTC) reflected in the orders. I just do not think that price fluctuations of $600 in consecutive trades at the **top** of the order book are  realistic, or even permitted based on the little published information about the matching engine that I have found. As best I can tell without digging into historic order book data, the order book ALWAYS has a depth in the thousands of bid-ask price levels (feel free to correct my assumptions with facts if you can). And the top of the order book has differentials of small tick values (.1, .2, etc.). An Exchange is supposed to provide a fair and orderly market - and the price fluctuations in the trades I identified are certainly not orderly, and as a consequence probably not fair. I think this should be brought to the attention of whatever group is responsible for technical as well as regulatory management of the Binance futures matching engine.

**Comment by tantialex** [comment]
>  I just do not think that price fluctuations of $600 in consecutive trades at the top of the order book are realistic, or even permitted based on the little published information about the matching engine that I have found. As best I can tell without digging into historic order book data, the order book ALWAYS has a depth in the thousands of bid-ask price levels (feel free to correct my assumptions with facts if you can). And the top of the order book has differentials of small tick values (.1, .2, etc.). An Exchange is supposed to provide a fair and orderly market - and the price fluctuations in the trades I identified are certainly not orderly, and as a consequence probably not fair. 

This is incorrect. The order delta between levels in an order book correlates to the volume of the trades in the market. The larger the volume of trades the more likely the gap between level 0 and level 1 will increase. 

For the issue you raised above, it appears there was a trading spike during 10:27:00 which lasted a couple of minutes. During this event, the order book is subject to high volatility due to liquidity. The above can be confirmed either by
- Checking the frequency of aggTrades and their volumes.
- Checking 1m klines.

Below is a sample taken from the Klines API highlighting the increase of about 20x the normal trading volume.

```
# 2021-12-10 10:25:00 to  2021-12-10 10:34:99 to 
GET https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1m&startTime=1633083900000&limit=10

[
    [
        1633083900000,
        "44894.00000000",
        "44909.48000000",
        "44894.00000000",
        "44906.39000000",
        "14.88602000",
        1633083959999,
        "668428.45854370",
        480,
        "9.11356000",
        "409217.63867520",
        "0"
    ],
    [
        1633083960000,
        "44906.40000000",
        "44978.11000000",
        "44895.95000000",
        "44973.44000000",
        "41.54078000",
        1633084019999,
        "1866703.85396980",
        852,
        "29.38352000",
        "1320450.82211600",
        "0"
    ],
    [
        1633084020000, // 2021-12-10 10:27:00
        "44973.45000000",
        "45789.99000000",
        "44959.55000000",
        "45703.60000000",
        "846.38205000", // 20x the previous volume
        1633084079999,
        "38349475.99178800",
        20356,
        "664.45775000",
        "30096800.59286240",
        "0"
    ],
    [
        1633084080000,
        "45703.60000000",
        "46750.00000000",
        "45375.03000000",
        "46721.58000000",
        "981.62895000",
        1633084139999,
        "45075716.07737210",
        28437,
        "650.65237000",
        "29905851.34326500",
        "0"
    ],
    [
        1633084140000,
        "46721.59000000",
        "46950.00000000",
        "45932.21000000",
        "46497.67000000",
        "962.95022000",
        1633084199999,
        "44700883.15198760",
        25365,
        "499.15943000",
        "23182466.56029240",
        "0"
    ],
    [
        1633084200000,
        "46449.22000000",
        "46838.84000000",
        "46223.52000000",
        "46445.35000000",
        "697.40019000",
        1633084259999,
        "32389465.38443470",
        12939,
        "375.67356000",
        "17459130.75591260",
        "0"
    ],
    [
        1633084260000,
        "46465.68000000",
        "46746.12000000",
        "46409.71000000",
        "46621.49000000",
        "391.05000000",
        1633084319999,
        "18215257.91954780",
        7584,
        "194.67059000",
        "9067027.44579580",
        "0"
    ],
    [
        1633084320000,
        "46630.85000000",
        "47086.16000000",
        "46600.31000000",
        "46740.92000000",
        "522.95147000",
        1633084379999,
        "24502801.14939480",
        11803,
        "314.49134000",
        "14742296.83524560",
        "0"
    ],
    [
        1633084380000,
        "46740.92000000",
        "46764.73000000",
        "46531.87000000",
        "46627.92000000",
        "304.92785000",
        1633084439999,
        "14225807.99258270",
        5715,
        "157.35507000",
        "7341721.61546400",
        "0"
    ],
    [
        1633084440000,
        "46627.93000000",
        "46909.00000000",
        "46625.90000000",
        "46817.13000000",
        "375.11252000",
        1633084499999,
        "17533299.07220120",
        5775,
        "231.49370000",
        "10819182.50055330",
        "0"
    ]
]
```
