### ISSUE TITLE
Timestamps are off by at least 14 seconds for kline data

### ISSUE THREAD

**Issue by moritzgun** [binance/binance-public-data#14]
For BTCUSDT and ETHUSDT candlestick data for Feb 2018 is a little off. From line 10110 of the BTCUSDT 1m candles of Feb 2018 timestamps are wrong until line 11311. Same issue for about the same range in ETHUSDT. Im checking other symbols now to find out whether this happens for all symbols!

**Comment by moritzgun** [comment]
The same holds true for BNBUSDT, LTCUSDT and NEOUSDT starting from line 10110.

**Comment by 2pd** [comment]
there is a gap from server side. Can be verified by :
`https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1m&startTime=1518049680000&limit=5`

**Comment by moritzgun** [comment]
Thanks for the clarification. Is that gap going to be corrected or do I have to do it myself? How can i be sure that there are no other gaps like this in more recent candlestick data?

**Comment by 2pd** [comment]
During the gap, it can be considered as no trading.

**Comment by moritzgun** [comment]
I see. So the files are not going to be corrected from your end?

**Comment by moritzgun** [comment]
Between 4th and 17th december 2017 the timestamps for BTCUSDT are also off.. Can you explain why this is the case? If it is to be considered as "no trading", why do the OHLC values seem to be correct and just off by some seconds?
