### ISSUE TITLE
startDate & endDate is not working well for download_kline.py

### ISSUE THREAD

**Issue by 4xmk0815** [binance/binance-public-data#141]
Dear Sir or Madam,

when I run:
download_kline.py -s BTCUSDT -startDate 2022-01-02 -endDate 2022-02-02 -t spot -i 1m

then a single monthly zip file for the whole "February 2022" will be downloaded instead of the daily zip files from 2nd of January 2022 to 2nd of February 2022.

The data are available, as I can manually use following Web-Link to download the ZIP files by following sample file:
https://data.binance.vision/data/spot/daily/klines/BTCUSDT/1m/BTCUSDT-1m-2022-01-02.zip

Please check, why the script is not able to download the data according to its "startDate" and "endDate" value, as this is the Date-format from the --help (YYYY-MM-YY)

Best regards,
4xmk0815

**Comment by chairz** [comment]
This issue is fixed in df2717909e3e3923058f8a74477653cc4258525a.
