### ISSUE TITLE
Speed up the download

### ISSUE THREAD

**Issue by helloyhan** [binance/binance-public-data#144]
Hi experts, is there any workaround to speed up the download? 
Despite I'm now using a proxy, I can see the process bar goes fast when it is downloading one file, while the interval between 2 files downloading is relatively long, which in a result causes much time to wait. 
Thank you if any hints!

**Comment by 2pd** [comment]
The files are hosted in AWS S3 buckets, if you have good connection to S3, it should be fast to download those files.

**Comment by saiaman** [comment]
would be better to provider s3 buckets names directly ... could be easier to process
