### ISSUE TITLE
Question about futures orderbook qty

### ISSUE THREAD

**Issue by cchicote** [binance/binance-public-data#145]
Hi,

Quick question about the sample data found in the README of the Futures_Order_Book_Download dir:
<html>
<body>

symbol | timestamp | first_update_id | last_update_id | side | update_type | price | qty
-- | -- | -- | -- | -- | -- | -- | --
BTCUSDT | 1593647999921 | 39538108420 | 39538108420 | a | set | 9235.09 | 0
BTCUSDT | 1593647999933 | 39538108444 | 39538108444 | a | set | 9236.04 | 0.852
BTCUSDT | 1593647999954 | 39538108472 | 39538108472 | b | set | 9219.67 | 0
BTCUSDT | 1593647999983 | 39538108497 | 39538108497 | a | set | 9236.04 | 0.912
BTCUSDT | 1593647999983 | 39538108498 | 39538108498 | a | set | 9235.11 | 0

</body>
</html>

Does it mean that the qty asked for price `9236.04` at time `1593647999983` is `0.912` or is it `0.852+0.912` ? 

Thanks a lot,
cchicote

**Comment by tantialex** [comment]
It's `0.912`.

The value in the `qty` column is the absolute quantity at `timestamp`.

**Comment by cchicote** [comment]
Thanks for your answer!

And can the 0.912 qty correspond to an aggregation of multiple quotes ?

Thanks again,
cchicote

**Comment by tantialex** [comment]
That is correct, `0.912` refers to the aggregation of all orders at the `9236.04` level.

**Comment by cchicote** [comment]
Ok ! Thanks a lot for your answers :)
