### ISSUE TITLE
How i can get news from Binance earlier than official releases?

### ISSUE THREAD

**Issue by KindSpidey** [binance/binance-public-data#146]
Hello guys. Sorry, if it is not the best place for such question, but i guess it is kind of official Binance API page and I guess only you can help me. So, listings on Binance is cool, but as i analyzed their effect on tokens' price, pump is always begins on 2 minutes earlier official news release. How does it happen all the time?) Is there any way to connect to Binance News API and get news before they released?

**Comment by tantialex** [comment]
There is no API for Announcements by Binance. Stay up to date with the Exchange Information endpoint for any changes or new listings.

**Comment by tantialex** [comment]
Correct, or poll the `/exchangeInfo` endpoint for differences.
