### ISSUE TITLE
Timestamps issue?

### ISSUE THREAD

**Issue by emanuele** [binance/binance-public-data#15]
After a very preliminary check, I see some inconsistent data: for example, SKYBTC-trades-2021-02.zip should have a very very notable peak at 2021-02-13 17:00 GMT but, according to the data in the zip file, its timestamp is around 1612386000000 which corresponds to
```
>>> datetime.fromtimestamp(1612386000000/1000.0)
datetime.datetime(2021, 2, 3, 22, 0)
```
which is 10 days earlier. Why?
Moreover, what is the timezone of the published timestamps?

Thanks

**Comment by 2pd** [comment]
UTC timestamp.

**Comment by emanuele** [comment]
Thanks @2pd !
About the 10 days difference, do you have more information?

**Comment by 2pd** [comment]
what do you mean by "have a very very notable peak at 2021-02-13 17:00 GMT"?

**Comment by emanuele** [comment]
Hi @2pd , I am trying to do some quality assurance on the data. As a first thing, I'd like to assess how accurate is the timestamp of the trades. A simple and effective way is to look for massive events in the timeseries and check the consistency with the data provided here, by binance-public-data. Useful examples for this purpose are the infamous _pump_ events, which produces such spikes. Here I am referring to SKYBTC on 2021-02-13 17:00 GMT, which was reported elsewhere as occurring on binance and visible from main chart websites:
- https://thecoinpump.com/events/6
- https://coinmarketcap.com/currencies/skycoin/ in Feb 2021
- https://finance.yahoo.com/quote/SKY-BTC/chart in Feb 2021

According to SKYBTC-trades-2021-02.zip, the peak of that month is 10 days away from 2021-02-13 which looks strange to me:

```
import pandas as pd
from datetime import datetime

df = pd.read_csv('SKYBTC-trades-2021-02.zip', names=("trade Id", "price", "qty", "quoteQty", "time", "isBuyerMaker", "isBestMatch"))
peak_idx = df['price'].argmax()
peak_time = df['time'][peak_idx]
peak_price = df['price'][peak_idx]
print(peak_price, peak_time, datetime.fromtimestamp(peak_time/1000))
```
which gives:
```
>>> 0.0004856 1612386022741 2021-02-03 22:00:22.741000
```

BTW it is not just the numerical position of the peak. If you look at the price graph from the zip file, the whole timesereis is visibly shifted of like 10 days.

**Comment by 2pd** [comment]
The trades data is the original transactions that happened on Binance. You may compare the trade info with Binance Kline chart. If there is price mismatching,  we can have a look.
