### ISSUE TITLE
How often do you update the futures markPriceKlines data?

### ISSUE THREAD

**Issue by noahverner1995** [binance/binance-public-data#150]
I want to know how often do you update futures markPriceKlines data because I need to use OHLC prices from the BTCUSDT trading pair within the time period of 2022-05-12 to 2022-05-22 and according to your [website](https://data.binance.vision/?prefix=data/futures/um/daily/markPriceKlines/BTCUSDT/15m/) the last day (22) in my period hasn't been upload yet:

![image](https://user-images.githubusercontent.com/83596569/169991697-9bf7f2cc-3c69-4a10-9117-9a85ec7a2fb9.png)

I thought you had a delay of 1 day, but it seems it's even longer. Is this normal?

**Comment by 2pd** [comment]
thanks for feedback, will let team know to upload the latest asap.

**Comment by 2pd** [comment]
All daily data in May have been uploaded,  team is working to speed up.
Close this issue,  please open a new one if you have any other concern.
