### ISSUE TITLE
Having trouble pulling binance order book data, output of script provided is <Response [200]>

### ISSUE THREAD

**Issue by minhajk21** [binance/binance-public-data#152]
Using the provided Python script, I can't seem to generate a download link for binance futures order book data, the response im getting is <Response [200]>. Is there something im missing?

**Comment by 2pd** [comment]
You need to apply it first, did you get response from team?

**Comment by minhajk21** [comment]
> You need to apply it first, did you get response from team?

I applied for order book data directly from Binance and they emailed confirmation of access. Is there a separate access I need to raise?

**Comment by 2pd** [comment]
What exactly did you receive in your response body?

**Comment by minhajk21** [comment]
> What exactly did you receive in your response body?

I just receive the following output: <Response [200]>

Which I believe means the request has been handled correctly, but no download link is printed. Have you been able to download order book data?

**Comment by AdamSwift95** [comment]
Yeah I have been having the same issue, get a response 200 but there is no date returned/link/id. The script provided breaks at "downloadID = resultDownloadID.json()["id"]" as there is no data returned by the API.

I did get access approved by Binance to access this data

**Comment by AdamSwift95** [comment]
all good - was using the wrong API

**Comment by 2pd** [comment]
> > What exactly did you receive in your response body?
> 
> I just receive the following output: <Response [200]>
> 
> Which I believe means the request has been handled correctly, but no download link is printed. Have you been able to download order book data?

I updated the script with more debug info, please run it again and print out the debug info here.

**Comment by minhajk21** [comment]
> > > What exactly did you receive in your response body?
> > 
> > 
> > I just receive the following output: <Response [200]>
> > Which I believe means the request has been handled correctly, but no download link is printed. Have you been able to download order book data?
> 
> I updated the script with more debug info, please run it again and print out the debug info here.

Sorry about the slow response.

I receive the following:

response status code: 200
response content: b'{"id":598721}'
598721
<Response [200]>
{'link': 'Link is preparing; please request later. Notice: when date range is very large (across months), we may need hours to generate.'}

However, no link appears. Is the link meant to be printed into my console?

**Comment by 2pd** [comment]
based on the error, it seems that you will need to wait a while and check later when it's preparing the link.

**Comment by DmitryBorisenko** [comment]
@2pd

I am having the same issue as @minhajk21 

The problem is, no matter how long I wait, calling the 'get' function still returns 'Link is preparing...', which is weird given that the request spans only 100 seconds of data. I also observe the same behavior with 'T_TRADE' data type.

Running the script produces:

> response status code: 200
> response content: b'{"id":598921}'
> 598921
> <Response [200]>
> {'link': 'Link is preparing; please request later. Notice: when date range is very large (across months), we may need hours to generate.'} 

The insides of 'resultToBeDownloaded' look like this:

> {'_content': b'{"link":"Link is preparing; please request later. Notice: when date range is very large (across months), we may need hours to generate."}',
>  '_content_consumed': True,
>  '_next': None,
>  'status_code': 200,
>  'headers': {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '137', 'Connection': 'keep-alive', 'Date': 'Tue, 14 Jun 2022 16:21:52 GMT', 'Server': 'nginx', 'X-SAPI-USED-IP-WEIGHT-1M': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 ade2b5e2170ccd4f394b741b27bb0eec.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': 'Eiol_rmnr3_DNBfHQrAN-gNky0aKdF7wtxGFVJLbL9Mk3SfzlT4H2Q=='},
>  'raw': <urllib3.response.HTTPResponse at 0x1dd71087848>,
>  'url': 'https://api.binance.com/sapi/v1/downloadLink?downloadId=598921&timestamp=1655223710498&signature=9f7d2a205c113f903bc8f2068964dd83562417a46bd1e8a177469284e174f3a8',
>  'encoding': 'UTF-8',
>  'history': [],
>  'reason': '',
>  'cookies': <RequestsCookieJar[]>,
>  'elapsed': datetime.timedelta(microseconds=482038),
>  'request': <PreparedRequest [GET]>,
>  'connection': <requests.adapters.HTTPAdapter at 0x1dd71084588>}

Hope this helps.

**Comment by 2pd** [comment]
thanks for the feedback, will share with team for review.

**Comment by jellebuth** [comment]
> @2pd
> 
> **Update:** it works, but the wait time until the file is prepared for download is extremely long - it took 8 hours to get 3 days of T_TRADE data for a single contract.
> 
> I am having the same issue as @minhajk21
> 
> The problem is, no matter how long I wait, calling the 'get' function still returns 'Link is preparing...', which is weird given that the request spans only 100 seconds of data. I also observe the same behavior with 'T_TRADE' data type.
> 
> Running the script produces:
> 
> > response status code: 200
> > response content: b'{"id":598921}'
> > 598921
> > <Response [200]>
> > {'link': 'Link is preparing; please request later. Notice: when date range is very large (across months), we may need hours to generate.'}
> 
> The insides of 'resultToBeDownloaded' look like this:
> 
> > {'_content': b'{"link":"Link is preparing; please request later. Notice: when date range is very large (across months), we may need hours to generate."}',
> > '_content_consumed': True,
> > '_next': None,
> > 'status_code': 200,
> > 'headers': {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '137', 'Connection': 'keep-alive', 'Date': 'Tue, 14 Jun 2022 16:21:52 GMT', 'Server': 'nginx', 'X-SAPI-USED-IP-WEIGHT-1M': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 ade2b5e2170ccd4f394b741b27bb0eec.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': 'Eiol_rmnr3_DNBfHQrAN-gNky0aKdF7wtxGFVJLbL9Mk3SfzlT4H2Q=='},
> > 'raw': <urllib3.response.HTTPResponse at 0x1dd71087848>,
> > 'url': 'https://api.binance.com/sapi/v1/downloadLink?downloadId=598921&timestamp=1655223710498&signature=9f7d2a205c113f903bc8f2068964dd83562417a46bd1e8a177469284e174f3a8',
> > 'encoding': 'UTF-8',
> > 'history': [],
> > 'reason': '',
> > 'cookies': <RequestsCookieJar[]>,
> > 'elapsed': datetime.timedelta(microseconds=482038),
> > 'request': <PreparedRequest [GET]>,
> > 'connection': <requests.adapters.HTTPAdapter at 0x1dd71084588>}
> 
> Hope this helps.

I was wondering how the message with the link is received. just via the terminal whenever it is ready? Which timestamps did you use for the simple request?

**Comment by jellebuth** [comment]
Thanks! In addition, I requested the T_depth data for ADA-USDT. I received the order book snapshots and the depth_update. However, I am only interested in the snapshots. The orderbook updates were 2.7GB, while the snapshots were only 9MB.

Is there a way to only request the orderbook snapshots instead of both?

**Comment by DmitryBorisenko** [comment]
@jellebuth 
> Thanks! In addition, I requested the T_depth data for ADA-USDT. I received the order book snapshots and the depth_update. However, I am only interested in the snapshots. The orderbook updates were 2.7GB, while the snapshots were only 9MB.
> 
> Is there a way to only request the orderbook snapshots instead of both?

Snapshots in the output are taken infrequently, hence the small file size. I believe they are included to serve as a starting point to reconstruct the whole order book using 'depth_update'

**Comment by minhajk21** [comment]
Has there been any update on this? wonder if there is a better way of aggregating orderbook data. @2pd happy to discuss if you're open to ideas. Thanks

**Comment by minhajk21** [comment]
Managed to get the S3 link, seems to just take a while (several days in my case).

**Comment by jellebuth** [comment]
How many days of data did you request?

**Comment by minhajk21** [comment]
@jellebuth, two months worth of data (01/01/2021 to 01/03/2021).

**Comment by minhajk21** [comment]
Going to close this as it seems to be working, just slow to generate the link and download the data. Thanks for your help!
