### ISSUE TITLE
aggTrade data is missing while kline data is present 

### ISSUE THREAD

**Issue by wen-lambo-ser** [binance/binance-public-data#153]
```
Market type:    USD-M futures
Data type:      aggTrades
Symbol:         BTCUSDT, ETHUSDT, DOGEUSDT and others
```

Ranges where the interval between adjacent aggTrade ticks is longer than 1 minute:

```
from:     1651443937403 (2022-05-01T22:25:37.403000Z)
to:       1651445710707 (2022-05-01T22:55:10.707000Z)
duration: 29m 33s 304ms

from:     1653755977208 (2022-05-28T16:39:37.208000Z)
to:       1653758100492 (2022-05-28T17:15:00.492000Z)
duration: 35m 23s 284ms

```

Is this expected?

**Comment by 2pd** [comment]
![image](https://user-images.githubusercontent.com/365354/171776666-5970e0ec-4e52-4999-adc6-2f228c04a71e.png)

The data is correct.  During the time window, there is no trade. 
Kline always generate even if there is no trade.

**Comment by Matoran** [comment]
Maybe you can be a little bit less aggressive? 
When you have this kind of data, check if the exchange was down for some reason.
They had an issue that suspended trading for 35 minutes, data is then correct.
https://twitter.com/binance/status/1530595451275198469
