### ISSUE TITLE
I got COIN-M Feature Order Book Level-2 data when requesting the USDT-M symbol

### ISSUE THREAD

**Issue by zgwl** [binance/binance-public-data#155]
Hi, I was downloading the USDT-M future data for both symbol `BTCUSDT` and `ETHUSDT` for the past two years.

The data before 11/19/2020 was correct, however, after 11/20/2020, the CSV contains the COIN-M data (which was wrong).

Here is the sampled data from the 11/21/2021, BTCUSDT:
`
symbol,timestamp,first_update_id,last_update_id,side,update_type,price,qty,pu
BTCUSDT,1605917815492,99615425606,99615425606,a,snap,18782.30,0.003,-1
BTCUSDT,1605917815492,99615425606,99615425606,a,snap,18782.07,0.004,-1
BTCUSDT,1605917815492,99615425606,99615425606,a,snap,18782.00,0.850,-1
BTCUSDT,1605917815492,99615425606,99615425606,a,snap,18781.90,0.005,-1
`

`
['symbol', 'timestamp', 'first_update_id', 'last_update_id', 'side', 'update_type', 'price', 'qty', 'pu']
['BTCUSDT', '1605916800034', '99603207936', '99603208187', 'b', 'set', '18626.35', '10.000', '99603207927']
['BTCUSDT', '1605916800034', '99603207936', '99603208187', 'b', 'set', '18632.00', '0.348', '99603207927']
['BTCUSDT', '1605916800034', '99603207936', '99603208187', 'b', 'set', '18636.67', '0.009', '99603207927']
`

The symbol `BTCUSDT` is correct, but the data is obviously wrong because the **pu** column is only for the COIN-M data.

would it be possible to take a look?

**Comment by 2pd** [comment]
After reviewed by team, there is no issue found in the data.

After 2020/11/20 data is based on api datasource. previous update id(pu) comes for both after that day.

**Comment by zgwl** [comment]
@2pd 

Hi Jeremy,

Thanks for looking into my issue! If the data is correct, why are the data on 11/19/2020 and 11/20/2020 so different?

This is the `depth_snap.csv` from 2020-11-29:
`symbol,timestamp,first_update_id,last_update_id,side,update_type,price,qty
BTCUSDT,1605743999999,97961301646,97961301646,a,snap,100000.00,0.098
BTCUSDT,1605743999999,97961301646,97961301646,a,snap,99999.99,0.028
BTCUSDT,1605743999999,97961301646,97961301646,a,snap,99998.00,0.002
BTCUSDT,1605743999999,97961301646,97961301646,a,snap,99995.80,0.002`

This is the `depth_snap.csv` from 2020-11-20:
`symbol,timestamp,first_update_id,last_update_id,side,update_type,price,qty,pu
BTCUSDT,1605830641162,98772995188,98772995188,a,snap,17991.64,0.001,-1
BTCUSDT,1605830641162,98772995188,98772995188,a,snap,17991.52,0.001,-1
BTCUSDT,1605830641162,98772995188,98772995188,a,snap,17991.11,0.025,-1
BTCUSDT,1605830641162,98772995188,98772995188,a,snap,17990.81,0.004,-1`

I was trying to rebuild the order book, but the data from 2020-11-20 doesn't fit with data from previous dates.

E.g. at 2020-11-19, the highest ask price is 100000, but it was gone in the 2020-11-20 snap csv. How am I supposed to use the data properly?

**Comment by zgwl** [comment]
(url
[BTCUSDT_T_DEPTH_2020-11-20_depth_snap.csv](https://github.com/binance/binance-public-data/files/8906417/BTCUSDT_T_DEPTH_2020-11-20_depth_snap.csv)
)
[BTCUSDT_T_DEPTH_2020-11-19_depth_snap.csv](https://github.com/binance/binance-public-data/files/8906418/BTCUSDT_T_DEPTH_2020-11-19_depth_snap.csv)

I have attached the download file, hope it will help.

**Comment by 2pd** [comment]
1605743999999 =>  November 18, 2020 23:59:59.999
1605830641162 =>   November 20, 2020 0:04:01.162

Those are the time when the snap was collected.

Those price are the open orders in the book when the snap was created, so it's possible without problem.
