### ISSUE TITLE
Spot trades and aggTrades: interpretation of timestamps with multiple unique isBuyerMaker values

### ISSUE THREAD

**Issue by ihopethiswillfi** [binance/binance-public-data#157]
Hi, I'm looking at trades data.  How should I interpret timestamps at which there are multiple distinct values of `isBuyerMaker`?

Example: the last 5 lines of `BTCUSDT-trades-2022-05.csv`, there you will see that at timestamp `1654041599996` there are 2 lines.  One line has isBuyerMaker TRUE, and the other line has isBuyerMaker FALSE.

![image](https://user-images.githubusercontent.com/17611570/176499865-2913dbb9-db9c-41ea-8520-ce2feb02347e.png)

In attempting to better understand this, I had a look at the aggTrades data as well:  `BTCUSDT-aggTrades-2022-05.csv`.  This did not lead to anything, as everything there looks exactly the same for these timestamps.

**Comment by 2pd** [comment]
In this case, 2 trades were generated in one millisecond. Because the timestamp is only displayed at the millisecond level, the timestamp looks the same.  The price for each trade is different, that's one of the clues.

**Comment by ihopethiswillfi** [comment]
So do I understand correctly that if the CSV's would be provided with microsecond resolution, then these 2 rows would have different timestamps?

What's the reason the resolution is limited to milliseconds?

**Comment by 2pd** [comment]
> So about the above example, do I understand correctly that if the CSV's would be provided with microsecond resolution, then these 2 rows would have different timestamps?

Technically, maybe, if those trades were not filled at the same microsecond.

**Comment by 2pd** [comment]
> Below is a new example in which the price for each trade is identical. Is the situation the same here? I.e. each of the 4 rows happened at different points in time, but it is simply not shown in the data because of the low time resolution?

Based on your examples, yes.

**Comment by 2pd** [comment]
> 

The trade id is enough to identify the orders.

I will close the ticket, please open new ticket for other concerns.
