### ISSUE TITLE
Browser does not show data older than 1st March of 2021

### ISSUE THREAD

**Issue by reisenmachtfreude** [binance/binance-public-data#158]
If I open e.g. https://data.binance.vision/?prefix=data/spot/daily/klines/BNBUSDT/1m/
I don't see older data than  1st March of 2021:
![image](https://user-images.githubusercontent.com/13700219/176816951-25d5c405-669b-4f91-bd25-627f09e36bac.png)

However, older data is available since the following link works fine:
https://data.binance.vision/data/spot/monthly/klines/BNBUSDT/1m/BNBUSDT-1m-2019-01.zip

**Comment by 2pd** [comment]
https://data.binance.vision/data/spot/monthly/klines/BNBUSDT/1m/BNBUSDT-1m-2019-01.zip
This is monthly data, not daily data. You should see this file in this directory:
https://data.binance.vision/?prefix=data/spot/monthly/klines/BNBUSDT/1m/
