### ISSUE TITLE
Futures_Order_Book_Download: it showed "Link is preparing; please request later" even though the time span is only a few minutes.

### ISSUE THREAD

**Issue by 2789747643** [binance/binance-public-data#160]
I try to run this script to download FuturesOrderbook: https://github.com/binance/binance-public-data/blob/master/Futures_Order_Book_Download/Futures-order-book-Level2-data-download.py

The only modification I made to the code was specifying my api_key and secret_key. The input parameters I use are the default ones.

It showed "Link is preparing; please request later", I waited twenty minutes and tried again, but still got the same result.

![image](https://user-images.githubusercontent.com/73594200/176985199-40d8cf0c-67a0-4c39-bba2-46955a46a8b2.png)

![image](https://user-images.githubusercontent.com/73594200/176985213-ef0647b4-1bcb-45ff-be92-f24e155b60f5.png)

**Comment by zgwl** [comment]
It's expected, you had to re-run it again to get the download link. The server needs some time to assemble the CSV file.

**Comment by 2pd** [comment]
Yeah, please open another topic if you have further question.
