### ISSUE TITLE
missing aggTrade data

### ISSUE THREAD

**Issue by wen-lambo-ser** [binance/binance-public-data#161]
Alright, here we go again:

```
Market type:    USD-M futures
Data type:      aggTrades
Symbol:         ETHUSDT, but also many others
```

```
from:     1655423999784 (2022-06-16T23:59:59.784000Z)
to:       1655510400082 (2022-06-18T00:00:00.082000Z)
duration: 1day 298ms

from:     1656028799851 (2022-06-23T23:59:59.851000Z)
to:       1656115200054 (2022-06-25T00:00:00.054000Z)
duration: 1day 203ms

from:     1656287999883 (2022-06-26T23:59:59.883000Z)
to:       1656633600019 (2022-07-01T00:00:00.019000Z)
duration: 4days 136ms
```

What's the explanation this time? [Last time](https://github.com/binance/binance-public-data/issues/153) there was no BTC trade for 35 minutes. What now, no trades for 6 days?

Incompetence or malice?

If incompetence, then guys, it's about time to get your hands out of your butt and start validating the data you are uploading. Any computer science student can make a validation script in an evening.

If malice - market data manipulation, well then we have enough clues in this repo to start a lawsuit. You know very well that people use this data to backtest their models. Don't pretend you don't know this.

In any case, what a disgrace for the largest exchange in the world...

**Comment by 2pd** [comment]
We found some missing data from the monthly aggtrade zip files. The team is working on preparing new monthly data packs that include all aggTrade data. We will also improve the process, hopefully, will deliver complete monthly data later.

The daily aggTrade data has no issue and was uploaded with all records in the zip files.  You are welcome to download them now and merge them into your monthly data to have a complete dataset. 
For example, the data of `ETHUSDT-aggTrades-2022-06-30`, which was uploaded at `2022-07-05T15:32:59.000Z`,  can be found at:
https://data.binance.vision/data/futures/um/daily/aggTrades/ETHUSDT/ETHUSDT-aggTrades-2022-06-30.zip

Also, all of the aggTrades records can be fetched from this public endpoint `GET /fapi/v1/aggTrades`. This public data contains the exactly same data from this endpoint. So you are free to download or verify the aggTrade from this endpoint in your convenience.

**Comment by 2pd** [comment]
Please download the latest monthly file, they should include all data.
