### ISSUE TITLE
How to discover delivery contracts?

### ISSUE THREAD

**Issue by dr1ver1** [binance/binance-public-data#162]
Hi,
I'm want to automatically download (from Python) delivery contracts, e.g. BTCUSDT_220325
They are not in symbols.txt. How can I programmatically find out which delivery contracts are available?

**Comment by 2pd** [comment]
The available trading symbols can be found from the endpoint `GET /dapi/v1/exchangeInfo`, it's reasonable to call it first and then download data of the symbols you find.

**Comment by dr1ver1** [comment]
The API only has live data and so does not contain historical contracts.
The web file download is for historical. The web download should be self-contained - i.e. query what is available in order to then download.

**Comment by 2pd** [comment]
OK, we will see if all CM futures symbols are available/

**Comment by dr1ver1** [comment]
Thanks - appreciate it - and also UM futures symbols please

**Comment by 2pd** [comment]
Please find futures symbols from here:

https://github.com/binance/binance-public-data/tree/master/data

**Comment by dr1ver1** [comment]
Thanks for that. How will these be kept up to date? So what happens just after a contract has expired?

**Comment by 2pd** [comment]
we try to keep them up to date.   You are also welcome to get current symbols from endpoint `/api/v3/exchangeInfo` regularly.

**Comment by dr1ver1** [comment]
There are items missing from cm-futures-symbols.txt. For instance searching for "_211231" returns 5 contracts.
https://data.binance.vision/?prefix=data/futures/cm/daily/klines/ has 9 contracts for _211231

**Comment by dr1ver1** [comment]
Are the various symbols.txt files manually populated? (Hopefully not!) They could be populated by a query that looks at data.binance.vision and runs on a schedule (e.g. daily)

**Comment by dr1ver1** [comment]
some 2206 and 2209 contracts are also missing from cm-futures-symbols.txt. I think there are other contracts missing for other months.

**Comment by 2pd** [comment]
> Are the various symbols.txt files manually populated? (Hopefully not!) They could be populated by a query that looks at data.binance.vision and runs on a schedule (e.g. daily)

symbols.txt contains part of the spot trading symbols, you can get all of them the endpoint `GET /api/v3/exchangeInfo`

**Comment by 2pd** [comment]
> 



> some 2206 and 2209 contracts are also missing from cm-futures-symbols.txt. I think there are other contracts missing for other months.

we will verify the cm futures symbols.

**Comment by 2pd** [comment]
Please check again. #165

**Comment by dr1ver1** [comment]
ok - I can see all the contracts for BTCUSD and ETHUSD now

**Comment by 2pd** [comment]
Well since we have uploaded all data into the storage, users can get the symbol list from there.
We will make a plan and see how to upload all symbols more frequently.
