### ISSUE TITLE
No trade data

### ISSUE THREAD

**Issue by Ivromandr** [binance/binance-public-data#163]
Hello, guys. 
There is no data by daily trades from 2022-07-12. Last mod.date 2022-07-13.
https://data.binance.vision/?prefix=data/spot/daily/trades/

Best regards, Roman

**Comment by chairz** [comment]
The data is present just not sorted in correct order. You can use the find function to look for 2022-07-14. We will fix this asap, sorry for the inconvenience caused.

**Comment by Ivromandr** [comment]
Ok. thanks)
