### ISSUE TITLE
Variable definition in Klines data

### ISSUE THREAD

**Issue by bhdoan** [binance/binance-public-data#168]
Hello,

When I go over the data files, I have some small questions that may need confirmation from you guys. Here we go.

Is that "Quote asset volume" means the volume in USDT, and "Base asset volume" or "volume only" means the volume in BTC for BTCUSDT in Spot and USD-M Futures? (Q1)

How about "Volume" and "Base asset volume" in  BTCUSD_PERP of COIN-M Futures data? (Q2)

Also "taker buy" means taker is the buyer in Kline data of Spot, USD-M Futures and COIN-M Futures? (Q3) 

In addition, do the variables in download-futures-indexPriceKlines.py, download-futures-markPriceKlines.py, , download-futures-premiumIndexKlines.py have the same meaning as those in Klines data? (Q4)

My understanding is that indexPrice is a bucket of prices from the major Spot market exchanges, weighted by their relative volume. MarkPrice is only used as a reference in liquidations and calculations of unrealized PNL of futures position. So is PremiumIndex based on the difference in price between (MarkPrice or last trade price of the corresponding futures contract???) and indexPrice? (Q5)

Then, in futures data, is OHLC price in Klines what we see in order book in real time, while OHLC price in indexPrice Klines and markPrice Klines are not what we see in order book right? (Q6)

That's why we only have meaningful data in OHLC price for indexPrice Klines, markPrice Klines and PremiumIndex Klines, opening time and closing time.

Thank you.

**Comment by chairz** [comment]
Q1: Yes, that is correct. 
Q2: Volume refers to the number of contracts, Base asset volume refers to the quantity of BTC.
Q3: It means the buyer is a taker. Which means that this buyer 'removes' an order from the orderbook.
Q4: The definition can be found here: https://binance-docs.github.io/apidocs/delivery/en/#index-kline-candlestick-streams
Q5: This is how the data of premiumIndex looks like: https://binance-docs.github.io/apidocs/futures/en/#mark-price
Q6: Yes, OHLC in klines are generated from trades which are placed in the orderbook. The other types of price are used for different purposes in futures trading.

**Comment by bhdoan** [comment]
thank you!
