### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by cryptang** [binance/binance-public-data#170]
Hi,
Data is missing : 
From https://data.binance.vision/data/futures/um/daily/klines/BTCUSDT/1m/BTCUSDT-1m-2021-02-22.zip
To https://data.binance.vision/data/futures/um/daily/klines/BTCUSDT/1m/BTCUSDT-1m-2021-02-26.zip

Can tou upload the data ?

grtz

**Comment by 2pd** [comment]
Thanks for waiting, they are available to download now.
