### ISSUE TITLE
Sucessful [200] but empty response

### ISSUE THREAD

**Issue by screaming-frog** [binance/binance-public-data#171]
I have had my account whitelisted for the historical order book data. Using the example script and my key and secret key, I get the following error:

`response status code: 200
response content: b'{}'
KeyError: 'id'`

I'm sure I'm doing something silly but not sure what.

**Comment by 2pd** [comment]
Sorry to hear that. Are you able to get the download Id now?

**Comment by screaming-frog** [comment]
No, unfortunately not

**Comment by screaming-frog** [comment]
No, unfortunately not.

**Comment by DanZBo** [comment]
I have the same issue. I tried different times, contracts, and types but I got empty answers in any case.

**Comment by andrea-c-binance** [comment]
hi @screaming-frog what was startTime, endTime, type, and symbol  you were requesting?

**Comment by gborrageiro** [comment]
I have the identical issue.

Example query (requests post):
'symbol': 'BTCUSDT',
 'startTime': 1671448859098,
 'endTime': 1671448979098,
 'dataType': 'T_DEPTH',
 'timestamp': 1671535319098
 
 https://api.binance.com/sapi/v1/futuresHistDataId

**Comment by gborrageiro** [comment]
It worked previously. My API key and IP are whitelisted.

Any ideas as to what the problem is?
