### ISSUE TITLE
download daily klines for last n days impossible 

### ISSUE THREAD

**Issue by iden83** [binance/binance-public-data#172]
There used to be implementation in **download-kline.py** allowing to download daily data for last 35 days. It's even still documented in `./download-kline.py -h`
As it was before recent changes: 

> Date to download in [YYYY-MM-DD] format\nsingle date or multiple dates separated by space\ndownload past 35 days if no argument is parsed

Now this functionality has changed and if no argument is parsed - it downloads daily data since 2020-01-01
That is way too much and not really useful anymore.

Workaround I'm using is to change PERIOD_START_DATE in **enums.py** manually to ~35 days ago each time before using this script.
Would be great to recover this functionality or if intended - to update documentation by explaining that not using arguments to parsed - downloads daily data since 2020.

**Comment by 2pd** [comment]
Thanks for the feedback, we will update the document.

**Comment by chairz** [comment]
This is a new default value that is defined. Alternatively, if you prefer to have data from a certain date, you can make use of the `-startDate` argument to download data starting from the specified `-startDate- to current date.

**Comment by chairz** [comment]
The documentation is update in #175
