### ISSUE TITLE
Missing data for BNBUSDT (and BNBBUSD) in Futures T_DEPTH

### ISSUE THREAD

**Issue by jwallbridge** [binance/binance-public-data#173]
There seems to be missing data for Futures orderbook T_DEPTH update data on 2022-07-15 (and I assume many others since I have not checked exhaustively).

BNBUSDT has the missing window:
1. 1657914272413 (7:44:32.413 PM) through 1657914363486 (7:46:03.486 PM).

BNBBUSD has two missing windows:
1. 1657856621820 (3:43:41.820 AM) through 1657856795630 (3:46:35.630 AM).
2. 1657914272418 (7:44:32.418 PM) through 1657914461496 (7:47:41.496 PM).

Please provide an update on this.

**Comment by chazzmoney** [comment]
Hi @2pd - thanks for reviewing this. Is there any update?

**Comment by jonte-z** [comment]
Hi @chazzmoney - I've checked the data for BNBUSDT and BNBBUSD and can't personally see any missing data in the time ranges you stated. Can you confirm if this is fixed on your side now?
