### ISSUE TITLE
Data completeness of T-DEPTH and T-DEPTH-BACKFILL for BTCUSDT

### ISSUE THREAD

**Issue by ai-fx** [binance/binance-public-data#176]
I have downloaded T-DEPTH and T-DEPTH-BACKFILL data and have found that data 
completeness is almost perfect. But several defects exist. Time gaps for data over 
10 minutes are shown below. These gaps make it difficult to make a precise order-
book from update data.
I would like to ask Binance staffs to complete the data.

[Time gap in seconds]: [start time] [end time]
36716.887s : 2020-12-16 13:48:03.141000+00:00 2020-12-17 00:00:00.028000+00:00
2374.516s : 2021-03-02 01:00:08.614000+00:00 2021-03-02 01:39:43.130000+00:00
1628.919s : 2021-05-19 13:20:36.598000+00:00 2021-05-19 13:47:45.517000+00:00
6000.105s : 2022-01-05 23:59:59.935000+00:00 2022-01-06 01:40:00.040000+00:00
4560.103s : 2022-01-06 01:41:59.913000+00:00 2022-01-06 02:58:00.016000+00:00
2640.114s : 2022-01-06 02:59:59.925000+00:00 2022-01-06 03:44:00.039000+00:00
840.489s : 2022-01-06 03:45:59.907000+00:00 2022-01-06 04:00:00.396000+00:00
9000.47s : 2022-01-06 04:01:59.545000+00:00 2022-01-06 06:32:00.015000+00:00
7200.105s : 2022-01-06 06:33:59.935000+00:00 2022-01-06 08:34:00.040000+00:00
3960.299s : 2022-01-06 08:35:59.721000+00:00 2022-01-06 09:42:00.020000+00:00
7080.144s : 2022-01-06 09:43:59.857000+00:00 2022-01-06 11:42:00.001000+00:00
17400.116s : 2022-01-06 11:43:59.880000+00:00 2022-01-06 16:33:59.996000+00:00
2280.261s : 2022-01-06 16:35:59.935000+00:00 2022-01-06 17:14:00.196000+00:00
5040.191s : 2022-01-06 17:15:59.850000+00:00 2022-01-06 18:40:00.041000+00:00
12600.192s : 2022-01-06 18:41:59.828000+00:00 2022-01-06 22:12:00.020000+00:00
1560.222s : 2022-01-06 22:13:59.763000+00:00 2022-01-06 22:39:59.985000+00:00
4680.103s : 2022-01-06 22:41:59.973000+00:00 2022-01-07 00:00:00.076000+00:00
1533.335s : 2022-03-21 12:24:59.905000+00:00 2022-03-21 12:50:33.240000+00:00
1773.243s : 2022-05-01 22:25:37.522000+00:00 2022-05-01 22:55:10.765000+00:00
2123.15s : 2022-05-28 16:39:37.405000+00:00 2022-05-28 17:15:00.555000+00:00

**Comment by 2pd** [comment]
"T_DEPTH_BACKFILL: tick-by-tick order book (level 2). T_DEPTH backfilled with internal logs. Currently in beta. And has stopped producing since mid-July 2021, resume date TBD."

**Comment by ai-fx** [comment]
Thanks for your reply , 2pd. 
I know that from the README file. 
I use the back-filled  data until mid-July 2021. 
However, it still have large time gaps.

**Comment by andrea-c-binance** [comment]
hi @ai-fx could you provide what symbol was this?

**Comment by arapseut** [comment]
thank u
