### ISSUE TITLE
3 minutes kline discrepency between archive spot data and api data

### ISSUE THREAD

**Issue by ligrire** [binance/binance-public-data#178]
Below is the kline data in archive ETHUSDT/1m/ETHUSDT-1m-2022-03.zip at timestamp 1646709120000 (2022-03-08 11:13:00 UTC+8:00)
<img width="1146" alt="Screen Shot 2022-09-01 at 5 51 07 PM" src="https://user-images.githubusercontent.com/32402508/187886630-9ff17560-9e83-4116-985b-16fe26e1665e.png">
However, the data from binance api or the binance spot market website shows:
<img width="1145" alt="Screen Shot 2022-09-01 at 5 56 30 PM" src="https://user-images.githubusercontent.com/32402508/187887211-26344e16-4fe9-4991-afd2-d1be39fe52e5.png">

What is the cause of the this discrepency?  Do other discrepencies exist in other symbols or at other timestamps?

**Comment by chairz-2** [comment]
Thank you for spotting this. We will review and amend with correct data accordingly.

**Comment by 2pd** [comment]
Please download the monthly data again, it should be fixed.
