### ISSUE TITLE
missing 2022-09-04 and 2022-09-05 data

### ISSUE THREAD

**Issue by smartcoder888** [binance/binance-public-data#179]

**Comment by 2pd** [comment]
we are working on it.

**Comment by mcpeer** [comment]
Hello @2pd, is there any update regarding this, and the missing data from 2022-09-14 and 2022-09-15? Thank you in advance.

**Comment by smartcoder888** [comment]
the SANDUSDT, ADAUSDT, FTMUSDT still missing 2022-09-05 data

**Comment by 2pd** [comment]
> Hello @2pd, is there any update regarding this, and the missing data from 2022-09-14 and 2022-09-15? Thank you in advance.

They are uploaded.  #181

**Comment by 2pd** [comment]
> 

Seems this happening on futures aggTrades data, we are working on it.

**Comment by 2pd** [comment]
> the SANDUSDT, ADAUSDT, FTMUSDT still missing 2022-09-05 data

Seems this happening on futures aggTrades data, we are working on it.

**Comment by 2pd** [comment]
This has been fixed, please open new issue if you still have questions.

Thanks.
