### ISSUE TITLE
Missing 08-27-2022 T_DEPTH Data

### ISSUE THREAD

**Issue by ozitrance** [binance/binance-public-data#180]
Hi there thank you for maintaining this

I’m downloading T_DEPTH data and noticed that one day is missing for a few pairs so far: 08-27-2022.

I found this on a few coin margin pairs like AAVEUSD_PERP and ADAUSD_PERP and also couple of the still active delivery futures for ADA. 

Can you please fix this and inform us when it’s done? 
Thank you!

**Comment by ozitrance** [comment]
Any news regarding this? I tried again today and those days are still missing. 

Thanks

**Comment by ozitrance** [comment]
Seems like all COIN-M pairs are missing that date. Is there anything new about this? Is it gonna get fixed at some point...?

**Comment by Colonel-Colt** [comment]
Any updates on this?
