### ISSUE TITLE
Missing 2022-09-14 data

### ISSUE THREAD

**Issue by ivanshuer** [binance/binance-public-data#181]
Hi, 

Seems 2022-09-14 spot 1d kline data is still missing. Do you know when it will be available?

**Comment by seraliilhan** [comment]
Not just 1hour data. I don't think there was an update at all yesterday (or today).

**Comment by smartcoder888** [comment]
The data is usually updated with a delay of 1 to 7 days. let's waiting for it

**Comment by 2pd** [comment]
Thanks for waiting, we had to slow down when expending the local storage. 
They are all uploaded now and back to normal.
The spot data usually uploaded in about 4-6 hours.
