### ISSUE TITLE
How to import the price change distribution of the whole market?

### ISSUE THREAD

**Issue by ELOIARMYOUNES** [binance/binance-public-data#185]
I think the price change distribution is much more critical, So, could you please help me to import it, or give me the formula between the price change distribution and the symbols of coins?

**Comment by 2pd** [comment]
what do you mean by price change distribution?
The Kline data contains the price change with different intervals.

**Comment by ELOIARMYOUNES** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/65903563/192661100-b62708e1-0648-42f1-8128-1fe8c6478e52.png">

**Comment by ELOIARMYOUNES** [comment]
That's what I mean.

**Comment by 2pd** [comment]
Unfortunately that's not available from public API.
The data here is coming the kline/trade/aggTrade endpoints.

**Comment by ELOIARMYOUNES** [comment]
Ok, thanks for your reply.
