### ISSUE TITLE
BTCUSDT monthly 1m-2022-06 klines complete day 2022-06-09 missing

### ISSUE THREAD

**Issue by Grepsy** [binance/binance-public-data#186]
https://data.binance.vision/data/futures/um/monthly/klines/BTCUSDT/1m/BTCUSDT-1m-2022-06.zip

This package is missing a complete day of klines for 2022-06-09.

![image](https://user-images.githubusercontent.com/383616/193280837-563df75c-cd74-4ef1-9435-9a75b888b37f.png)

**Comment by jonte-z** [comment]
I can confirm this data is missing, thanks for letting us know

**Comment by darienhuang** [comment]
we will try to recover this, eta 3 weeks.

**Comment by 2pd** [comment]
This has been fixed. Please download them again.
