### ISSUE TITLE
ETH-USDT-PERP 12 millions of missing ids in aggregated trades

### ISSUE THREAD

**Issue by UCT10** [binance/binance-public-data#190]
Hi. I'm building my local aggTrades storage, unfortunately, the provided snapshots are not consistent. There's a missing id list for ETHUSDTPERP in the attachment, I think, the issue is not specific for ETHUSDT pair. Please, check other aggTrades archives as well.

P.S. I've used zopfli (pigz -11) compression, so you might need pigz or something like that to decompress it. Also, I've used monthly snapshots, so everything from 2022-10-01 is not relatable.
https://data.binance.vision/?prefix=data/futures/um/monthly/aggTrades/ETHUSDT/

UPD
The link is below
[na_aggTrade.csv.gz](https://github.com/binance/binance-public-data/files/9769321/na_aggTrade.csv.gz)

**Comment by Nyanraltotlapun** [comment]
I see holes in data in monthly snapshots for spot aggTrades data for BTCBUSD and BTCUSDT pairs.
For example 121 minutes of data missing in BTCBUSD around id:206050876 and time:2021-09-29 12:00
It seems no missing data after this date but a lot before.

**Comment by 2pd** [comment]
> 



> I see holes in data in monthly snapshots for spot aggTrades data for BTCBUSD and BTCUSDT pairs.
> For example 121 minutes of data missing in BTCBUSD around id:206050876 and time:2021-09-29 12:00
> It seems no missing data after this date but a lot before.

Are you referring to different issue? this topic is about UM futures.

If it's about spot data, please open a separate topic with more details, like which zip file and which line of data is wrong.

Thanks

**Comment by jonte-z** [comment]
Hi @UCT10 - You seemed to have forgotten to attach the file you mentioned? It would be helpful in investigating the issue. Eg. an ID or date range is preferable.

**Comment by UCT10** [comment]
> Hi @UCT10 - You seemed to have forgotten to attach the file you mentioned? It would be helpful in investigating the issue. Eg. an ID or date range is preferable.

Nope, it was there, highlighted it in my first comment

**Comment by jonte-z** [comment]
> > Hi @UCT10 - You seemed to have forgotten to attach the file you mentioned? It would be helpful in investigating the issue. Eg. an ID or date range is preferable.
> 
> Nope, it was there, highlighted it in my first comment

Thanks for updating your original comment, I can download it now. I wasn't able to see it/download it prior to your edit.

**Comment by 2pd** [comment]
I think this has been fixed, please open a new issue for any concern.
