### ISSUE TITLE
BTCUSDT future missing data on 20220609

### ISSUE THREAD

**Issue by LYK-CC** [binance/binance-public-data#192]
I downloaded all the data from binance visions, and just before I was going to to the backtesting, I realized that there were many missing kline data for instruments.
for example, starting from 2022, January first to sep 30th, 4h candle line, in a total of 1632 klines for eth and 1608 for BTC, a huge difference, representing that there is a lot data missing
![image](https://user-images.githubusercontent.com/49092631/197676180-e17dce9f-a98d-4331-9bd9-521d21892288.png)

**Comment by jonte-z** [comment]
Hi, I looked into the data speficially for 20220609 on BTCUSDT UM Futures and I can confirm there's no missing data.

**Comment by UCT10** [comment]
> Hi, I looked into the data speficially for 20220609 on BTCUSDT UM Futures and I can confirm there's no missing data.

There is. More than that, not only 2022 06 09  is missing, but 2022 08 10, 2022 08 11 2022 08 12 BTCUSDT UM **montly** klines (5min and 1min at least) miss as well
Also BNBUSDT UM **monthly** 5min and 1min klines miss 2022 04 17, 2022 06 09, 2022 08 10, 2022 08 11, 2022 08 12 data
