### ISSUE TITLE
ethusdt trades  2022-11-3 7:37--8:0 miss

### ISSUE THREAD

**Issue by xiongbenwu** [binance/binance-public-data#194]
ethusdt trades  2022-11-3 7:37--8:0 miss

**Comment by xiongbenwu** [comment]
um

**Comment by jonte-z** [comment]
Hi @xiongbenwu,
I have checked the data and can confirm that there aren't missing trades for ETHUSDT on USDT-M Futures in the period of 07:37 - 08:00 GMT+0 on 2022-11-03.

**Comment by xiongbenwu** [comment]
thks
