### ISSUE TITLE
ETHUSDT-aggTrades-2022-11-1.zip  miss

### ISSUE THREAD

**Issue by xiongbenwu** [binance/binance-public-data#195]
ETHUSDT-aggTrades-2022-11-1.zip  miss

**Comment by xiongbenwu** [comment]
File not found: https://data.binance.vision/data/futures/um/daily/aggTrades/ETHUSDT/ETHUSDT-aggTrades-2022-11-06.zip

**Comment by 2pd** [comment]
this is fixed.
