### ISSUE TITLE
How long will preparing download link for T_DEPTH data?

### ISSUE THREAD

**Issue by dazre** [binance/binance-public-data#199]
symbol = "LINKUSD_230331"
startTime = 1668978000000
endTime = 1669593600000

downloadID -> 720807

Two days have already passed...

**Comment by dazre** [comment]
Three days have already passed...

**Comment by dazre** [comment]
Four days have already passed...

**Comment by dazre** [comment]
Five days have already passed...

**Comment by dazre** [comment]
Six days have already passed...

**Comment by ysq151944** [comment]
I got the same problem...

**Comment by dazre** [comment]
Eight days have already passed...

**Comment by Evrard-Nil** [comment]
Experiencing the same issue. Any updates @2pd ?

**Comment by darienhuang** [comment]
we provided new endpoint for this, check faq here: https://www.binance.com/en/support/faq/binance-futures-order-book-historical-data-e707685b4e0f408fa7c1b9ccd8ea7aa9
