### ISSUE TITLE
Column definations of daily trades of Future contracts

### ISSUE THREAD

**Issue by Ev3rlasting** [binance/binance-public-data#20]
Hi Binance,

I am wondering if you could provide the column definitions of `trades` of the USDT-M future contract, for example:
`51254697,9.96,18.8,187.248,1617840001352,false`

downloaded from https://data.binance.vision/data/futures/um/daily/trades/OMGUSDT/OMGUSDT-trades-2021-04-08.zip

I can't seem to find the definition for the last Boolean column, is it `isBuyerMaker` or `isBestMatch`? What does the `isBestMatch` mean? Thanks

**Comment by ishuen** [comment]
This file is generated by data fetched from this endpoint. https://binance-docs.github.io/apidocs/futures/en/#old-trades-lookup-market_data
So, to answer your question, those fields refer to
id               | price | qty   | quoteQty | time                      | isBuyerMaker
51254697 | 9.96  | 18.8 | 187.248.   | 1617840001352 | false

**Comment by Ev3rlasting** [comment]
Thank you for the quick reply. What does the `isBestMatch`  mean in the `AggTrades`? (You may close the issue now)

**Comment by chairz** [comment]
isBestMatch is not relevant in the current trading context for now. It is a boolean reserved for future use.
