### ISSUE TITLE
Why do the data of the coin that has been currently delisted still exist after delisting date?

### ISSUE THREAD

**Issue by homedry** [binance/binance-public-data#201]
https://www.binance.com/en/support/announcement/binance-futures-will-delist-fttbusd-usdt-margined-contract-7305d3e50f0647838078ded2be975d48
The above page says FTTBUSD um contract was delisted months ago.
But I can download the data on November 30th from https://data.binance.vision/?prefix=data/futures/um/daily/klines/FTTBUSD/1d/ .
Although that the volume is zero makes sense but, I don't understand how the price exists.

is the data from other markets, meaning they are not specific to binance contract?
Or how do you maintain them?

**Comment by 2pd** [comment]
```json
[
    [
        1671148800000,
        "1.678",
        "1.678",
        "1.678",
        "1.678",
        "0.0",
        1671235199999,
        "0.0000",
        0,
        "0.0",
        "0.0000",
        "0" # trade amount
    ]
]

```

This FTTBUSD is delisted.  The data from the kline endpoint has the data you like to know.

- The price is inherited from last valid trade.
-  The last `0` shows the trade amount. It tells that there is no trade during this kline.

**Comment by homedry** [comment]
Thank your for the reply!
