### ISSUE TITLE
Get User ID active futures positions 

### ISSUE THREAD

**Issue by Polar-Bear300** [binance/binance-public-data#202]
Hello, I'd like to know if there's any possible way to get all the active future positions of any accounts that shares their positions using their User ID ? If so, how could I do that? 

Thank you

**Comment by 2pd** [comment]
Please open topic at dev.binance.vision for API related question.
I don't think it's possible to query positions by user id.

**Comment by LeFesh** [comment]
Hello, can you please permanently delete this issued?
