### ISSUE TITLE
missing 2022-11-14 data

### ISSUE THREAD

**Issue by smartcoder888** [binance/binance-public-data#207]
BTCUSDT, SOLUSDT, MATICUSDT, GALAUSDT, RUNEUSDT

**Comment by 2pd** [comment]
Can you check again if there are available or not?

Is it futures or spot? klines?

**Comment by smartcoder888** [comment]
still missing, it is futures agg_trades

**Comment by darienhuang** [comment]
we will take a look and try to recover, eta 3 weeks

**Comment by s-z-20230331** [comment]
fixed
