### ISSUE TITLE
Historical data of Options, when?

### ISSUE THREAD

**Issue by mihonf** [binance/binance-public-data#209]
Please, add to API connections the historical data of options trading in EOD timeline per each date. The data that is now available for connections and downloads is practically useless.

Date of   trading | symbol of Options | Price_Open | Price_Close | markPrice | Volume | bidIV | askIV | markIV | delta | theta | gamma | vega | Expiration Date | sumOpenInterest | sumOpenInterestUsd | BaseAsset | Price EOD_BaceAsset

Thanks in advance. :-)

**Comment by 2pd** [comment]
what exactly data are you referring?

**Comment by mihonf** [comment]
Date of trading | symbol of Options | Price_Open | Price_Close | markPrice | Volume | bidIV | askIV | markIV | delta | theta | gamma | vega | Expiration Date | sumOpenInterest | sumOpenInterestUsd | BaseAsset | Price EOD_BaceAsset

in EOD timeline

**Comment by 2pd** [comment]
Are you talking the futures orderbook L2 data? if so, can you give an example data that why it's useless, and how do you like to improve.

thanks

**Comment by darienhuang** [comment]
Option data is on our roadmap, likely you can see these in Q2 this year

**Comment by mihonf** [comment]
> Are you talking the futures orderbook L2 data? if so, can you give an example data that why it's useless, and how do you like to improve.
> 
> thanks

What is futures for here? I need historical options data. Futures and options are not the same things.

**Comment by wony-zheng** [comment]
I need historical options data too

**Comment by Om994272** [comment]
For what

في اثنين، ٢٤ يوليو، ٢٠٢٣ في ٦:٠٧ ص، كتب wony ***@***.***>:

**Comment by mihonf** [comment]
I don't know who and how did this but it is super. Thanks. This is all i wanted

**Comment by darienhuang** [comment]
Option data can be found in https://www.binance.com/en/landing/data
