### ISSUE TITLE
Open Interest data frequency

### ISSUE THREAD

**Issue by thomasd3** [binance/binance-public-data#211]
Right now, with futures, we can get the open interest for the day only.

Using: https://data.binance.vision/?prefix=data/futures/um/daily/metrics/BTCUSDT/

We get data like:

```
create_time	symbol	sum_open_interest	sum_open_interest_value	count_toptrader_long_short_ratio	sum_toptrader_long_short_ratio	count_long_short_ratio	sum_taker_long_short_vol_ratio
2023-01-21	BTCUSDT	98666.16300000	        2236289208.19726700	0.766568632422291	                1.1363333457	                0.8332767017782309	0.9253075900
```

While getting the live data from Binance's servers, we get updates at a much lower time interval (20s I believe).

How can we get access to the whole Open Interest history?

**Comment by darienhuang** [comment]
We will provide OI data with small granularity, likely in Q2 this year

**Comment by thomasd3** [comment]
great, thanks!

**Comment by huaiweicheng** [comment]
any plans to support other metrices data with small granularity like topLongShortPositionRatio or takerlongshortRatio?

**Comment by darienhuang** [comment]
Yes, plan to have those on Q2 this year.

**Comment by tunedforai** [comment]
Binance only publishes daily OI snapshots in the public data repo. For higher-frequency history you have two paths:

1. **Binance API directly**: `/fapi/v1/openInterest` gives the latest OI value per symbol, but historical intraday OI is not exposed via REST. You would need to poll and store it yourself.
2. **Aggregated data providers**: there are services that poll and warehouse OI (and funding, liquidations, long/short ratios) at sub-minute granularity. If you do not want to run the scraper yourself, we expose OI + funding + CVD across 20 exchanges via a pay-per-call API: https://x402.tunedfor.ai/guide. Snapshots are $0.20; hourly history is $5.

If you prefer self-hosted, the simplest scraper is a cron that hits `/fapi/v1/openInterest` every minute, appends to Parquet/TSDB, and backfills gaps from the daily Binance dumps.
