### ISSUE TITLE
Some trades ara missing futures/um/daily/trades/BTCUSDT/BTCUSDT-trades-2023-01-24.zip

### ISSUE THREAD

**Issue by kdcd** [binance/binance-public-data#213]
No trades after 2023-01-24 20:14:17.838
https://data.binance.vision/data/futures/um/daily/trades/BTCUSDT/BTCUSDT-trades-2023-01-24.zip
And It's the same for all future contracts. 
2023-01-23 has the same problem too.

**Comment by darienhuang** [comment]
We are aware of this and trying to fix, please take another look after two weeks

**Comment by ihopethiswillfi** [comment]
I'm facing the same issue almost 2 months after the latest reply here, and it looks to me that this is not just for 2023-01-23 and 2023-01-24.

I am loading monthly UM FUTURES into a DB.
I do this in chunks of 2,000,000 rows.
While doing this, I do some validation.
Below is my output for BTCUSDT.

```
0it [00:00, ?it/s]missing trades in batch: 142 / 2000000
(inserted into table) 2019-10-11 05:59: : 1it [00:02,  2.32s/it]missing trades in batch: 4334 / 2000000
(inserted into table) 2019-10-26 07:40: : 2it [00:03,  1.70s/it]missing trades in batch: 479 / 2000000
(inserted into table) 2019-11-03 04:04: : 3it [00:04,  1.53s/it]missing trades in batch: 859 / 2000000
(inserted into table) 2019-11-11 08:07: : 4it [00:06,  1.43s/it]missing trades in batch: 1163 / 2000000
(inserted into table) 2019-11-19 03:47: : 5it [00:07,  1.38s/it]missing trades in batch: 2594 / 2000000
(inserted into table) 2019-11-23 04:41: : 6it [00:08,  1.36s/it]missing trades in batch: 427 / 2000000
(inserted into table) 2019-11-26 11:34: : 7it [00:10,  1.34s/it]missing trades in batch: 405 / 2000000
(inserted into table) 2019-11-30 04:06: : 8it [00:11,  1.33s/it]missing trades in batch: 686 / 2000000
(inserted into table) 2019-12-04 21:58: : 9it [00:12,  1.33s/it]missing trades in batch: 231 / 2000000
(inserted into table) 2019-12-11 09:53: : 10it [00:14,  1.32s/it]missing trades in batch: 927 / 2000000
```

I checked also ETH-USDT and LTC-USDT: same problem.

I did a few (3 or so...) manual spot checks of daily files: same problem.  The trades missing in the monthly files are also missing in the daily files.

Seems to me that all `futures/um` trades files are broken.

**Comment by darienhuang** [comment]
Can I ask how you judge whether there is missing trade? Thanks

**Comment by ihopethiswillfi** [comment]
Missing id'sOn 11 Apr 2023 07:00, darienhuang ***@***.***> wrote:
Can I ask how you judge whether there is missing trade? Thanks
