### ISSUE TITLE
The latest date of historical spot klines data is inconsistent among trading pairs

### ISSUE THREAD

**Issue by le8888e** [binance/binance-public-data#218]
Currently, the latest date for BTCUSDT historical spot klines data is 2023-2-13, but the latest date for ETHUSDT is 2023-2-12, as you can see in the picture. 
![date inconsistent](https://user-images.githubusercontent.com/34771253/218964735-12f9ff25-aaf3-4333-be40-4685f3451a7c.png)

**Comment by aisling-2** [comment]
This is no longer a problem, so closing the issue
