### ISSUE TITLE
In binance website showing data in different then public data for example check kline price of 4th dec 2021 in website and public price are different. 

### ISSUE THREAD

**Issue by surajwala15** [binance/binance-public-data#221]
is:issue is:open in binance website showing data in different then public data for example check kline price of 4th dec 2021 in website and public price are different.

**Comment by aisling-2** [comment]
@surajwala15 Please be more specific:
- Which file from public data? You can use link to redirect us. There's different time intervals.
- Screenshot of the website to showcase the expected behavior.
- Which price? There's OHLC prices.

More details helps us to be able to understand your perspective and verify.

**Comment by jbmlaird** [comment]
Looking at ETHGBP 1m intervals for 2023-04-07:
https://data.binance.vision/data/spot/daily/klines/ETHGBP/1m/ETHGBP-1m-2023-04-07.zip

<img width="463" alt="Screenshot 2023-04-13 at 16 03 08" src="https://user-images.githubusercontent.com/16595870/231802435-99bd0d19-f3ba-4c53-adf9-126b34719f79.png">
website shows £1497.35 at 12:10am

above file shows £1508.97 at 12:10am
<img width="1265" alt="Screenshot 2023-04-13 at 16 05 47" src="https://user-images.githubusercontent.com/16595870/231802865-cae04713-46fc-4d35-8ad1-a54beffa2566.png">

Very rarely do these two values match. Should I trust these Binance files or the UI? Should I be using another file to get 1 minute interval prices?

**Comment by aisling-2** [comment]
https://api.binance.com/api/v3/klines?symbol=ETHGBP&interval=1m&startTime=1680826200000&limit=1

```
[
		1680826200000,
		"1508.97000000", —> Open price (as in the public data file)
		"1508.97000000",
		"1508.97000000",
		"1508.97000000",
		"0.00000000",
		1680826259999,
		"0.00000000",
		0,
		"0.00000000",
		"0.00000000",
		"0"
]
```
https://www.binance.com/en/trade/ETH_GBP
<img width="909" alt="Screen Shot 2023-04-14 at 11 07 33" src="https://user-images.githubusercontent.com/112478306/231923573-50f6c6b1-8c8d-443c-95fc-0fdbdbca115a.png">

@jbmlaird 
They both have open price `1508.97000000`. 
Remember to set your Website trading view to UTC to be in same time frame as the API/public data files.
