### ISSUE TITLE
BTCUSDT Future S-Depth order book data(202210/202211/202212) lack some second data

### ISSUE THREAD

**Issue by Jasonissmart** [binance/binance-public-data#223]
I downloaded BTCUSDT Future S-Depth order book data(202210/202211/202212) through API.
I read in the data through pandas read_cv() function and transfrom "ts" column into pandas datatime object through to_datetime(, unit='ms') function.
Then I resample data into second unit by using pandas resample('S', on='ts') function.
I found that it lacks so many second data(around 3% per month).
What is the reason to cause this? Or Did I make some mistake about data preprocessing?

**Comment by darienhuang** [comment]
S_Depth data quality before 2023-05-28 was not good due to old design, please try generate snapshot data using T_Depth
