### ISSUE TITLE
U本位BTC永续klines 月份数据 2022年6月和8月

### ISSUE THREAD

**Issue by xiongbenwu** [binance/binance-public-data#224]
月kline6月9号10号    8月10 11 12 3 缺失
链接
[BTCUSDT-1h-2022-06.zip](https://data.binance.vision/data/futures/um/monthly/klines/BTCUSDT/1h/BTCUSDT-1h-2022-06.zip)

[BTCUSDT-1h-2022-08.zip](https://data.binance.vision/data/futures/um/monthly/klines/BTCUSDT/1h/BTCUSDT-1h-2022-08.zip)

**Comment by s-z-20230331** [comment]
same issue with https://github.com/binance/binance-public-data/issues/186
fixing
