### ISSUE TITLE
futures/cm/daily/klines/BTCUSD_PERP/1m/BTCUSD_PERP  missing on 2020-11-02 ~ 2020-11-06

### ISSUE THREAD

**Issue by eromoe** [binance/binance-public-data#226]
File not found: https://data.binance.vision/data/futures/cm/daily/klines/BTCUSD_PERP/1m/BTCUSD_PERP-1m-2020-11-02.zip

File not found: https://data.binance.vision/data/futures/cm/daily/klines/BTCUSD_PERP/1m/BTCUSD_PERP-1m-2020-11-03.zip

File not found: https://data.binance.vision/data/futures/cm/daily/klines/BTCUSD_PERP/1m/BTCUSD_PERP-1m-2020-11-04.zip

File not found: https://data.binance.vision/data/futures/cm/daily/klines/BTCUSD_PERP/1m/BTCUSD_PERP-1m-2020-11-05.zip

File not found: https://data.binance.vision/data/futures/cm/daily/klines/BTCUSD_PERP/1m/BTCUSD_PERP-1m-2020-11-06.zip

**Comment by darienhuang** [comment]
tech team will evaluate to see if we can add these back

**Comment by s-z-20230331** [comment]
fixed
