### ISSUE TITLE
Missed klines UM BNXUSDT 15m

### ISSUE THREAD

**Issue by yaroshoris** [binance/binance-public-data#229]

**Comment by s-z-20230331** [comment]
which date? Can you provide more information

**Comment by yaroshoris** [comment]
Ohhh, I don't know where my description went, just dissappeared. Anyway:
I download all datasets and started iterating through each timestamp. For example if we are speaking about 15m TF my script comparing timestamp of 2 neigboor candles and if the value > 15m * 60s * 1000ms (ms) it'll give me a notification about where is gap has occured.  

`           
             for i, row in enumerate(dataset):
                if i != len_a - 1:

                    current_value = int(row[0])  ## Get TS of **current bar**
                    next_value = int(dataset[i + 1][0])   ## Get TS of **next bar** 
                    predicted_value = current_value + 900000  ## Gap should be (15m * 60s * 1000ms) == 900k ms
                    
                    if predicted_value != next_value:
                        gap = int((next_value - predicted_value) / 900000)
                        print(f"MARKET predicted_value {predicted_value} || next_value {next_value}, GAP {gap}")
`
I have detected multiple gaps for the most of symbols that are traded on Binance. It occurs even on higher TF (60m).

Thanks for taking it into consideration and improving the consistency of the datasets.

**Comment by yaroshoris** [comment]
It seems that current was doubled with this issue #230 
 Sorry for that
