### ISSUE TITLE
Missing daily files for the trades spot data in the 2020. 

### ISSUE THREAD

**Issue by dremdem** [binance/binance-public-data#232]
Hello! 

Tried to download daily files for the trades spot data in the 2020 and found the monthly data only. 
Could be fixed somehow in order to not download these huge files for a couple days data. 

Thanks for advance!
Vlad.

**Comment by 2pd** [comment]
This is in the plan,  it will take a while due to the amount of files that need to be prepared.

**Comment by 2pd** [comment]
All spot data should be already uploaded.
