### ISSUE TITLE
月度数据目前只更新到2023年2月，请问可否更新一下

### ISSUE THREAD

**Issue by szz1233** [binance/binance-public-data#233]

**Comment by 2pd** [comment]
你说的具体是哪个symbol？ 可以给个例子么？

**Comment by szz1233** [comment]
抱歉打扰了，当时4月5日是在：
https://data.binance.vision/?prefix=data/spot/monthly/klines/BTCUSDT/1d/ 
查询月度数据包文件时没有3月的zip，第二天已有。
