### ISSUE TITLE
Future data download link takes much more time to generate than before

### ISSUE THREAD

**Issue by randomwalker42** [binance/binance-public-data#236]
I was able to get the download link for data type 'S_DEPTH' and 'T_DEPTH' in a short time two years ago. However, when I run the same script now the download link never finishes generating. 

The official example [Futures-order-book-Level2-data-download.py](https://github.com/binance/binance-public-data/blob/master/Futures_Order_Book_Download/Futures-order-book-Level2-data-download.py) has the following config: 

```
# Specify the four input parameters below:
symbol = "ADAUSDT"  # specify the symbol name
startTime = 1635561504914  # specify the starttime
endTime = 1635561604914  # specify the endtime
dataType = "T_DEPTH"  # specify the dataType to be downloaded
```

It requests only two minute's data, but actually takes hours to generate the download link, which makes it impossible download data for longer history. Would you kindly look at the problem?

**Comment by PierreLeGuen** [comment]
I am experiencing the same issue. The exports were functioning perfectly fine two weeks ago, but now they never seem to resolve. We currently have short exports pending (for only a month) for over a week now, with no resolution in sight.

**Comment by PierreLeGuen** [comment]
cc @darienhuang

**Comment by PierreLeGuen** [comment]
cc @2pd

**Comment by Colonel-Colt** [comment]
I am experiencing the same issue. Any ideas on how long it will take for recovering?

**Comment by Evrard-Nil** [comment]
Same issue as well. It started being slow about 2 weeks ago and now it seems completely stuck.

**Comment by Qasak** [comment]
Same, I generated a few download links after waiting for about a week(both large and small). I guess their server is stacking up too many requests and all the waits are in one queue.

**Comment by PierreLeGuen** [comment]
I think the download links will never come. We have had links pending for almost two weeks now. Usually, it always returns a valid link within 6 hours.

**Comment by Evrard-Nil** [comment]
Any updates @2pd ?

**Comment by darienhuang** [comment]
We are working on fixing this, ETA early June

**Comment by PierreLeGuen** [comment]
@darienhuang, how is it looking you guys found the root cause?

**Comment by darienhuang** [comment]
we released new endpoint to get this data: https://binance-docs.github.io/apidocs/spot/en/#get-future-ticklevel-orderbook-historical-data-download-link-user_data
