### ISSUE TITLE
Trade history of the current day to the current time

### ISSUE THREAD

**Issue by jorkey** [binance/binance-public-data#237]
Hello.
Can I get trade history of the current day up to the current time?
I can get trade events of previous days by download daily archives and realtime trade events stream by API.
But how to fill the gap between them?

**Comment by doitagainforme** [comment]
response = requests.get(f"{BASE_URL}/fapi/v1/historicalTrades?symbol={symbol}&limit=1000&fromId={from_id}",
                                headers=headers)

**Comment by jorkey** [comment]
Sorry, but that is futures API. That request returns futures trades, but I need spot trades.

**Comment by doitagainforme** [comment]
BASE_URL = "https://api.binance.com"
API_KEY = '********************'
headers = {'X-MBX-APIKEY': API_KEY}

def get_historical_trades(symbol, from_id):
    try:
        response = requests.get(f"{BASE_URL}/api/v3/historicalTrades?symbol={symbol}&limit=1000&fromId={from_id}",
                                headers=headers)
        if response.status_code == 200:
            return response.json()
        else:
            print(f"Error fetching historical trades. Status code: {response.status_code}")
            return None
    except Exception as e:
        print(f"Error fetching historical trades: {str(e)}")
        return None


you can't query historicalTrades for time, but you can query aggTrades for time, its response has [' f ' ] which contains the desired id for historicalTrades.


def get_first_trade_id(symbol, start_time):
    url = f"{binance_api_base}/api/v3/aggTrades"
    params = {'symbol': symbol, 'startTime': start_time, 'limit': 1}
    response = requests.get(url, params=params)

    if response.status_code == 200:
        agg_trade = response.json()
        if agg_trade:
            return agg_trade[0]['f']
    else:
        print(f"Error {response.status_code}: {response.text}")
        return None

**Comment by doitagainforme** [comment]
> Sorry, but that is futures API. That request returns futures trades, but I need spot trades.

```
BASE_URL = "https://api.binance.com"
API_KEY = '********************'
headers = {'X-MBX-APIKEY': API_KEY}

def get_historical_trades(symbol, from_id):
    try:
        response = requests.get(f"{BASE_URL}/api/v3/historicalTrades?symbol={symbol}&limit=1000&fromId={from_id}",
                                headers=headers)
        if response.status_code == 200:
            return response.json()
        else:
            print(f"Error fetching historical trades. Status code: {response.status_code}")
            return None
    except Exception as e:
        print(f"Error fetching historical trades: {str(e)}")
        return None
```


you can't query historicalTrades for time, but you can query aggTrades for time, its response has [' f ' ] which contains the desired id for historicalTrades.


```
def get_first_trade_id(symbol, start_time):
    url = f"{binance_api_base}/api/v3/aggTrades"
    params = {'symbol': symbol, 'startTime': start_time, 'limit': 1}
    response = requests.get(url, params=params)

    if response.status_code == 200:
        agg_trade = response.json()
        if agg_trade:
            return agg_trade[0]['f']
    else:
        print(f"Error {response.status_code}: {response.text}")
        return None
```

**Comment by jorkey** [comment]
Thanks, this is what I need.

**Comment by doitagainforme** [comment]
No, there is no other way.  I am receiving trade data via websocket.  If the websocket connection fails, I fill in the missing data using the above method.
Also keep in mind that the response to the request does not come at the same second.  For example, 7 hours of missing data is filled in about 2 hours.

**Comment by jorkey** [comment]
Ok, thanks.

ср, 24 мая 2023 г. в 12:01, doitagainforme ***@***.***>:
