### ISSUE TITLE
Spot monthly klines data missing since 2022-onwards for some pairs

### ISSUE THREAD

**Issue by cbrunnkvist** [binance/binance-public-data#238]
For example, in https://data.binance.vision/?prefix=data/spot/monthly/klines/NANOUSDT/1d/, the last created/modified date is 2022-01-25.

**Comment by cbrunnkvist** [comment]
_(I wonder how these data files are generated in case the jobs by any chance are ordered by something, and it times out at some predictable point during each generation run?)_

**Comment by 2pd** [comment]
This is not an issue.  When the symbol is removed from exchange, the kline will stop generating new data.

**Comment by cbrunnkvist** [comment]
You were correct. The corresponding renamed symbol is available at https://data.binance.vision/?prefix=data/spot/monthly/klines/XNOUSDT/1d/ in this case.
