### ISSUE TITLE
USDT to Fiat (USD)

### ISSUE THREAD

**Issue by ying-w** [binance/binance-public-data#239]
Given the recent [stablecoin instability](https://www.coindesk.com/learn/why-stablecoin-usdcs-unstable-weekend-matters/) is there a way to look up USDT to fiat? Would the best equivalent be USDT-BUSD? When I looked at the march klines it didn't show much change.

**Comment by 2pd** [comment]
Sorry, I don't think there is market data of USDT to fiat, please check the endpoint `/exchangeInfo` to see what is the available trading symbols.
