### ISSUE TITLE
Error BTCUSDT trades archives unpacking 

### ISSUE THREAD

**Issue by Kalugin** [binance/binance-public-data#24]
Downloaded all trades for BTCUSDT. But there are errors in the following archives:

- BTCUSDT-trades-2019-03
- BTCUSDT-trades-2019-04
- BTCUSDT-trades-2019-05
- BTCUSDT-trades-2019-06
- BTCUSDT-trades-2019-07
- BTCUSDT-trades-2019-08
- BTCUSDT-trades-2019-09
- BTCUSDT-trades-2019-10
- BTCUSDT-trades-2019-11
- BTCUSDT-trades-2019-12
- BTCUSDT-trades-2020-01
- BTCUSDT-trades-2020-02

Can't open with python (zipfile.BadZipFile: File is not a zip file) or OS tools (7-zip).
Сhecksums are correct. 
Other archives are fine.

**Comment by 2pd** [comment]
thanks for the feedback, we will look into this.

**Comment by 2pd** [comment]
It should be fixed now.
