### ISSUE TITLE
Is the trade history from BTCUSDT-trades-2023-04.csv (um futures) corrupted?

### ISSUE THREAD

**Issue by doitagainforme** [binance/binance-public-data#240]
Аbout half of the lines of the entire uploaded file look like this:

id,price,qty,quote_qty,time,is_buyer_maker
3520593365,28454.8,0.009,256.0932,1680307200158,true
3610094716,27494.1,0.001,27.4941,1682384979351,false
3520593366,28454.8,0.027,768.2796,1680307200165,true
3610094717,27494.1,0.041,1127.2581,1682384979445,false
3520593367,28454.8,0.005,142.274,1680307200165,true
3610094718,27494.1,0.036,989.7876,1682384979463,false
3520593368,28454.8,0.022,626.0056,1680307200165,true
3610094719,27494.1,0.001,27.4941,1682384979931,false

Through each trade, the price jumps and returns back by $1,000. Is it possible to fix?

**Comment by darienhuang** [comment]
This is likely due to some OTC trades, not real issue; We will try to check if we can remove those
