### ISSUE TITLE
futures/um/daily/aggTrades/BTCUSDT March 31 is missing

### ISSUE THREAD

**Issue by nepolak** [binance/binance-public-data#243]
[BTCUSDT-aggTrades-2023-03-31.zip](https://data.binance.vision/data/futures/um/daily/aggTrades/BTCUSDT/BTCUSDT-aggTrades-2023-03-31.zip)

returns `The specified key does not exist`.

**Comment by s-z-20230331** [comment]
fixing

**Comment by s-z-20230331** [comment]
fixed
