### ISSUE TITLE
data.binance.vision/ data had not been updated from May 22nd

### ISSUE THREAD

**Issue by pakchu** [binance/binance-public-data#244]
i have checked some pairs ('ETHUSDT', '1INCHUSDT') for 15m, 1m and all of their lastest data is May 22nd's data

**Comment by s-z-20230331** [comment]
Do you mean um kline? These data is ready now.

**Comment by pakchu** [comment]
> 
thanks for the updates! i guess theres some gap between the real time and the update time

**Comment by 2pd** [comment]
This should be already updated.
