### ISSUE TITLE
Futures orderbook data for BTCUSDT pair have no data for 05-28 (now 06-05)

### ISSUE THREAD

**Issue by Cphilo** [binance/binance-public-data#245]
I try download T_DEPTH data for BTCUSDT. I found that the download link is generated. But extracted files have issues. The file for `BTCUSDT_T_DEPTH_2023-05-28_depth_update.csv` is empty. It seems strange. From the doc, I think if today is 06-05, then 06-04 data should be ok. Pls take a look.

**Comment by Cphilo** [comment]
@darienhuang I checked the data after 2023-05-27. Uncompress file like `BTCUSDT_T_DEPTH_2023-05-27_depth_snap.csv` or `BTCUSDT_T_DEPTH_2023-07-14_depth_snap.csv` only contains 1 l2_snapshot. And this l2_snapshot seems more than 40k level. Before 2023-05-27, the l2_snapshot is 1000 levels. I think new l2_snapshot is invalid data. Need take a look at this issue.

**Comment by darienhuang** [comment]
yes we are providing more level so user can replicate whole orderbook, new data is correct
