### ISSUE TITLE
CSV header row missing in Futures data

### ISSUE THREAD

**Issue by czernalex** [binance/binance-public-data#246]
I tried to download futures 1m monthly klines data for `BTCUSDT` symbol from `2020-01-01` to `2023-03-31`, however I encountered interesting issue, namely the result csv data until `2022-05-01` are missing the header row with column names (`open_time`, `open`, `high`, `low`, etc.). Is there any particular reason for this inconsitency? Thanks.

**Comment by s-z-20230331** [comment]
Because the header row is added after that date, earlier files don't contain the header
