### ISSUE TITLE
ETHUSDT USDⓢ-M Perpetual Trade data missing for 2023-05-21

### ISSUE THREAD

**Issue by dylanmckendry** [binance/binance-public-data#247]
The [ETHUSDT-trades-2023-05-21.zip](https://data.binance.vision/data/futures/um/daily/trades/ETHUSDT/ETHUSDT-trades-2023-05-21.zip) is missing.

**Comment by s-z-20230331** [comment]
fixing

**Comment by s-z-20230331** [comment]
fixed

**Comment by dylanmckendry** [comment]
Thanks! Confirmed it is working
