### ISSUE TITLE
CHECKSUMs don't match for kline monthly 1s data 201 files

### ISSUE THREAD

**Issue by andrewkip** [binance/binance-public-data#249]
Hi!
I've find out that for 201 files CHECKSUMs don't mutch see summary bellow. (detailed info in attached file) 
Redownloaded many times (more then 4 times) from diferent servers and diferent countires :)
Summary:

<table>
    <tr>
        <td>market</td>
        <td>TP</td>
        <td>Data Type</td>
        <td>Period</td>
        <td>Files</td>
        <td>File period</td>
    </tr>
    <tr>
        <td>spot</td>
        <td>ATOMUSDT</td>
        <td>K-line</td>
        <td>1s</td>
        <td>31</td>
        <td>monthly</td>
    </tr>
    <tr>
        <td>spot</td>
        <td>BNBUSDT</td>
        <td>K-line</td>
        <td>1s</td>
        <td>48</td>
        <td>monthly</td>
    </tr>
    <tr>
        <td>spot</td>
        <td>DOGEUSDT</td>
        <td>K-line</td>
        <td>1s</td>
        <td>26</td>
        <td>monthly</td>
    </tr>
    <tr>
        <td>spot</td>
        <td>LINKUSDT</td>
        <td>K-line</td>
        <td>1s</td>
        <td>35</td>
        <td>monthly</td>
    </tr>
    <tr>
        <td>spot</td>
        <td>MATICUSDT</td>
        <td>K-line</td>
        <td>1s</td>
        <td>32</td>
        <td>monthly</td>
    </tr>
    <tr>
        <td>spot</td>
        <td>SOLUSDT</td>
        <td>K-line</td>
        <td>1s</td>
        <td>17</td>
        <td>monthly</td>
    </tr>
    <tr>
        <td>spot</td>
        <td>TWTUSDT</td>
        <td>K-line</td>
        <td>1s</td>
        <td>12</td>
        <td>monthly</td>
    </tr>
</table>

[BadCheckSumFiles.csv](https://github.com/binance/binance-public-data/files/11781302/BadCheckSumFiles.csv)

**Comment by Full4me** [comment]
Same problem. For 71 files of BTCUSDT just 21 matches, ETHUSDT also 21 for 71 files. Other pairs also not working correctly.

**Comment by 2pd** [comment]
we have updated the checksum files, please download again.

Thanks

**Comment by Om994272** [comment]
Ok you official stake ??

في جمعة، ٢٨ يوليو، ٢٠٢٣ في ٨:٠٤ ص، كتب Jeremy ***@***.***>:
