### ISSUE TITLE
BTCUSDT Futures trades monthly 2021-03 are missing days

### ISSUE THREAD

**Issue by argalasjr** [binance/binance-public-data#25]
BTCUSDT-trades-2021-03.csv file does not contain all the days

**Comment by ishuen** [comment]
Hi @argalasjr  May I know which day you are checking? The csv file does contain the data for everyday from 2021-03-01 00:00:00 to 2021-03-31 23:59:59 GMT+00:00.

**Comment by SanjayaBR** [comment]
> BTCUSDT-trades-2021-03.csv file does not contain all the days

This issue is fixed. Please verify. Thanks
