### ISSUE TITLE
Access Denied when accessing https://public.bnbstatic.com/static/js/ocbs/@binance/fiat-widget.js

### ISSUE THREAD

**Issue by John-Blair** [binance/binance-public-data#252]
Hi, I am trying to use the Binance Fiat Widget on my website by accessing https://public.bnbstatic.com/static/js/ocbs/@binance/fiat-widget.js from my website or a browser gives  Access Denied

Attempting to follow the instruction here which don't work due to the access denied issue:
https://www.npmjs.com/package/@binance/fiat-widget

Not sure if it is a cloudflare issue.

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2ZHK48PMG8N4N0EG</RequestId>
<HostId>lh5CTM4Ze5LGZYrPelT/58Kd4idR55CoSYJGq6oHPq5nlL8RkiyHT4MWA4jIRrtrNxK47eb9ghc=</HostId>
</Error>

note: The previous widget worked fine here https://www.npmjs.com/package/binance-fiat-widget
but is now broken so using the new one recommended above.

**Comment by 2pd** [comment]
Please feel free to open a topic at https://dev.binance.vision for any API concern that outside of the this repo's scope.
