### ISSUE TITLE
Missing metrics for futures/um BTCUSDT 2023-07-25

### ISSUE THREAD

**Issue by ytskuh** [binance/binance-public-data#258]
https://data.binance.vision/data/futures/um/daily/metrics/BTCUSDT/BTCUSDT-metrics-2023-07-25.zip
https://data.binance.vision/data/futures/um/daily/metrics/BTCUSDT/BTCUSDT-metrics-2023-07-25.zip.CHECKSUM
These two files are missing.

**Comment by darienhuang** [comment]
fixed
