### ISSUE TITLE
problems in the aggTrades data.

### ISSUE THREAD

**Issue by Adam1679** [binance/binance-public-data#263]
some of the aggTrades data is not correct. For example, for BTCUSDT_perpetual in USDM on "BTCUSDT-aggTrades-2023-03-21.csv", the qty field is not correct due to precision error.  It looks like this: 
![image](https://github.com/binance/binance-public-data/assets/32404962/9339d88c-7ca9-4e99-8bdf-36569ca92261)

The qty field is nearly zero.

**Comment by crackcomm** [comment]
In this dataset: https://data.binance.vision/data/futures/um/monthly/aggTrades/BTCUSDT/BTCUSDT-aggTrades-2023-05.zip 38% trades have zero quantity.

**Comment by darienhuang** [comment]
we will fix this week
