### ISSUE TITLE
No *klines data since 2023-08-28

### ISSUE THREAD

**Issue by christophlins** [binance/binance-public-data#267]
There seems to be no *klines data for CM symbols after 2023-08-27. 

https://data.binance.vision/?prefix=data/futures/cm/daily/indexPriceKlines/ETHUSD/1m/
https://data.binance.vision/?prefix=data/futures/cm/daily/klines/ETHUSD_PERP/1m/
https://data.binance.vision/?prefix=data/futures/cm/daily/premiumIndexKlines/ADAUSD_PERP/1m/

**Comment by thisismygitrepo** [comment]
@christophlins May I ask a bit of a side question. The klines for CM that you are referring to, what are the headers of the columns therein ?
The README says it is 
`['openTime', 'open', 'high', 'low', 'close', 'volume', 'closeTime', 'baseAssetVolume', 'numberOfTrades', 'takerBuyVolume', 'takerBuyBaseAssetVolume', 'ignore']`
But some of those files that you refer to actually contain the headers (the majority don't) and they say that columns are:

`['open_time', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_volume', 'count', 'taker_buy_volume', 'taker_buy_quote_volume', 'ignore']`

Which one is correct? `QuoteVolume` or `BaseVolume` ?

**Comment by christophlins** [comment]
I ignore the headers and assume `quote_asset_volume` for UM and Spot and `base_asset_volume` for CM for the column in question.

Can you provide me an example where it mentions quote asset in a CM kline?
