### ISSUE TITLE
bad csv line in KSMUSDT-trades-2021-09-16

### ISSUE THREAD

**Issue by petrkozorezov** [binance/binance-public-data#275]
[KSMUSDT-trades-2021-09-16](https://data.binance.vision/data/spot/daily/trades/KSMUSDT/KSMUSDT-trades-2021-09-16.zip) contains bad line:85954 `34550875,431.80000000,0.0234550876,431.80000000,0.02500000,10.79500000,1631766616805,False,True`

**Comment by 2pd** [comment]
this is fixed, please download it again.
