### ISSUE TITLE
metrics data on 2023-09-18 was generally missing

### ISSUE THREAD

**Issue by MokerWill** [binance/binance-public-data#276]
https://data.binance.vision/?prefix=data/futures/um/daily/metrics/
I verified the metrics data and selected the fields 'sum_open_interest' and 'sum_open_interest_value', and found that the data on 2023-09-18 was generally missing.

**Comment by pennymax** [comment]
Agree, generally missing hours from 13 to 24 in 2023-09-18

**Comment by 2pd** [comment]
this has been fixed, please download them again.
