### ISSUE TITLE
Some trades are missing

### ISSUE THREAD

**Issue by p-i-** [binance/binance-public-data#28]
Examining OXT daily trades, I find:

```
1684950,0.00001144,87.00000000,0.00099528,1619247104155,True,True
1684951,0.00001145,116.00000000,0.00132820,1619247146932,True,True
1684952,0.00001146,410.00000000,0.00469860,1619247160026,True,True
1687081,0.00001069,1169.00000000,0.01249661,1619308836628,True,True
1687082,0.00001069,467.00000000,0.00499223,1619308836628,True,True
```

My verifier flagged it:
```
NONCONSEC
2021-04-24 06:52:40.026000 (1684952, 1619247160026, True)
2021-04-25 00:00:36.628000 (1687081, 1619308836628, True)
```

As this is the first coin I tested against, I imagine other coins may also have missing trades.

Is this expected/known?

Is it going to be fixed?

Is it likely to fix itself once we enter the next month, and a fresh 'April' OXT monthly zip is generated?

Or are these trades lost forever in the Matrix?

**Comment by p-i-** [comment]
NOTE: There seems to be the same time-chunk missing from all coins
If Binance was down, surely the re-opening trade would have the next ID.

**Comment by ishuen** [comment]
Hi. There was a maintenance at that time, the trade was suspended.
https://www.binance.com/en/support/announcement/8acdc6f4ce0e43c6a402475d35ce41ac

**Comment by 2pd** [comment]
we have fixed the missing data, please check again.
