### ISSUE TITLE
Missing documentation: timestamp is TradeTime not EventTime

### ISSUE THREAD

**Issue by p-i-** [binance/binance-public-data#29]
I recommend you document _which_ timestamp you are using in historical trade data -- it's not in the `README.md`.

As per https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#trade-streams

```
{
  "e": "trade",     // Event type
  "E": 123456789,   // Event time
  "s": "BNBBTC",    // Symbol
  "t": 12345,       // Trade ID
  "p": "0.001",     // Price
  "q": "100",       // Quantity
  "b": 88,          // Buyer order ID
  "a": 50,          // Seller order ID
  "T": 123456785,   // Trade time
  "m": true,        // Is the buyer the market maker?
  "M": true         // Ignore
}
```

There is `Event Time` and `Trade Time`.

I can see from my own data you are using `T`, but maybe document this...

**Comment by 2pd** [comment]
The trade csv file data are fetched from endpoint `api/v3/historicalTrades`.
