### ISSUE TITLE
MISSING KLINE for monthly 2023-11 spot market

### ISSUE THREAD

**Issue by rmalvarezkai** [binance/binance-public-data#292]
Example:

rmalvarez@arizona:/tmp/tester$ LANG=C wget https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1m/BTCUSDT-1m-2023-11.zip
--2023-12-03 16:44:37--  https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1m/BTCUSDT-1m-2023-11.zip
Resolving data.binance.vision (data.binance.vision)... 3.160.119.104, 3.160.119.3, 3.160.119.108, ...
Connecting to data.binance.vision (data.binance.vision)|3.160.119.104|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-12-03 16:44:39 ERROR 404: Not Found.

Thank You

**Comment by rmalvarezkai** [comment]
Today I check this and file not found
rmalvarez@arizona:/tmp/tester$ LANG=C wget https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1mo/BTCUSDT-1mo-2023-03.zip
--2023-12-05 01:36:44--  https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1mo/BTCUSDT-1mo-2023-03.zip
Resolving data.binance.vision (data.binance.vision)... 3.160.119.3, 3.160.119.104, 3.160.119.70, ...
Connecting to data.binance.vision (data.binance.vision)|3.160.119.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-12-05 01:36:46 ERROR 404: Not Found.

Thank You

**Comment by 2pd** [comment]
Hi, there should be fixed. Please check.

**Comment by rmalvarezkai** [comment]
Thank You very much
