### ISSUE TITLE
Spot Kline BTCUSDT 2023 week, missing data for May 29 2023 and Jul 31 2023

### ISSUE THREAD

**Issue by vdse** [binance/binance-public-data#298]
In file: https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1w/BTCUSDT-1w-2023-05.zip
 - missed data for May 29 2023 00:00:00 GMT+0000

In file: https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1w/BTCUSDT-1w-2023-07.csv
 - missed data for Jul 31 2023 00:00:00 GMT+0000

**Comment by 2pd** [comment]
This has been fixed,  please download again.
