### ISSUE TITLE
'File not Found' Error in download-kline.py Script When Downloading Zip Files

### ISSUE THREAD

**Issue by ben9809** [binance/binance-public-data#299]
### Description
When executing the `download-klines.py` script, users encounter a 'File Not Found' error. This issue arises when attempting to download one or more files that actually exist. The root cause of this problem seems to be a mismatch in the file formats: the script is designed to download `.zip` files, but the actual files being downloaded are in `.csv` format.

### Steps Demonstrating the Related Observation
1. Navigate to [Binance Market Data](https://data.binance.vision) website.
2. Attempt to download the klines of a cryptocurrency pair.
3. Observe that when clicking on a link to download a `.zip` file, a `.csv` file is downloaded instead.

**Comment by 2pd** [comment]
I'm not sure if I understand it correctly. On the https://data.binance.vision/ page, all files are stored as zip files, download them and unzip, you will get the csv files.
