### ISSUE TITLE
Broken trades files

### ISSUE THREAD

**Issue by pha377** [binance/binance-public-data#301]
Dear Binance Data,

I downloaded the following files:
https://data.binance.vision/data/futures/um/monthly/trades/SOLUSDT/SOLUSDT-trades-2023-10.zip
https://data.binance.vision/data/futures/um/monthly/trades/SOLUSDT/SOLUSDT-trades-2023-11.zip
https://data.binance.vision/data/futures/um/monthly/trades/SOLUSDT/SOLUSDT-trades-2023-12.zip

https://data.binance.vision/data/futures/um/daily/trades/SOLUSDT/SOLUSDT-trades-2024-01-01.zip

The IDs don't correlate,
those files seem to be broken.

Could you please guide me on how to interpret them?

Regards,

**Comment by pha377** [comment]
Not broken, we just need to order by trade id

**Comment by 2pd** [comment]
I will close this. Please open issue for any other concern.
