### ISSUE TITLE
Please fix data missing from Jan 11 2024 to now for solusdt

### ISSUE THREAD

**Issue by crabbit22** [binance/binance-public-data#302]
See https://data.binance.vision/?prefix=data/spot/daily/klines/SOLUSDT/1m/, this is missing from Jan 11, 2024

**Comment by Crpto999** [comment]
Not just for the SOLU-USDT pair, but since January 10th of this year, the spot K-line data for all other cryptocurrencies have stopped updating. However, the futures contract data continue to update normally. This is quite strange

**Comment by 2pd** [comment]
It's been updated and fixed, thanks for waiting.
