### ISSUE TITLE
Suggestion for a simple compression technique for trades data

### ISSUE THREAD

**Issue by p-i-** [binance/binance-public-data#31]
Examining a chunk of trades data:

```
252195,0.00005717,383.00000000,0.02189611,1601560817800,False,True
252196,0.00005726,29.00000000,0.00166054,1601560820102,False,True
252197,0.00005726,29.00000000,0.00166054,1601560820102,False,True
252198,0.00005726,29.00000000,0.00166054,1601560820103,False,True
252199,0.00005726,29.00000000,0.00166054,1601560820103,False,True
252200,0.00005726,29.00000000,0.00166054,1601560820103,False,True
252201,0.00005726,29.00000000,0.00166054,1601560820103,False,True
252202,0.00005726,29.00000000,0.00166054,1601560820103,False,True
```

This could be stored much more efficiently.

- OrderId is almost always incrementing
- Multiplying `price` by 10^8 yields an integer.  Storing the delta: `(price - prev_price)`. Usually it's `0`.
- Remove trailing zeros from `quantity`
- Multiplying `quoteQty` by 10^8 yields an integer
- Store timestamp delta `(time - prev_time)`.
- Use `0`, `1` for `False`, `True`

```
252195,5717,383.00000000,0.02189611,1601560817800,False,True
+1, +9, 29, 166054, +302, 0, 1
+1, +0, 29, 166054, +0, 0, 1
:
```

This seems much more readable to me.
As it is using integer arithmetic, there is no accumulating floatingpoint random walk error.

Just an idea...

**Comment by 2pd** [comment]
Thank you for the suggestion,   we wish to leave the file as simple as possible, easy to read.
