### ISSUE TITLE
BTTUSDT missing

### ISSUE THREAD

**Issue by kenny0514** [binance/binance-public-data#311]
BTTUSDT is missing since 2022 Jan

**Comment by kenny0514** [comment]
I was looking at spot 5m

**Comment by aisling-2** [comment]
@kenny0514 `BTTUSDT` was renamed to `BTTCUSDT`, hence you're not finding the rest of the data with the old symbol name.

https://www.binance.com/en/support/announcement/binance-will-support-the-bittorrent-btt-token-migration-redenomination-and-renaming-plan-2722e6da4f5141dd9b2fb07b5b1f3f75
