### ISSUE TITLE
BTCUSDT Spot Trade missing data: 2018-02-08

### ISSUE THREAD

**Issue by naijim** [binance/binance-public-data#316]
open the csv file downloaded, https://data.binance.vision/data/spot/daily/trades/BTCUSDT/BTCUSDT-trades-2018-02-08.zip, check the first and last column:

```
14764081,7599.00000000,0.22477000,1708.02723000,1518048000016,True,True
...
14776497,7784.02000000,0.00322700,25.11903254,1518049694685,True,True
```

The last timestamp is `Thu Feb 08 2018 00:28:14 GMT+0000`, so there is only 28 minutes of data?

**Comment by aisling-2** [comment]
Hi @naijim, thanks for looking into it.
There was a long system maintenance that day (you can news online), so it's an expected case.
