### ISSUE TITLE
2024-01 Monthly kline data  are missing  from 2024-01-10 for some symbols

### ISSUE THREAD

**Issue by ligrire** [binance/binance-public-data#320]
For many symbols including 1000SATSUSDT AERGOUSDT AEURUSDT AGIXUSDT..., the 2024-01 monthly kline data are only provided between 2024-01-01 and 2024-01-10.

**Comment by aisling-2** [comment]
Thanks for noticing it, we'll work on it.

**Comment by aisling-2** [comment]
We would like to inform that `2024-01` monthly data has been re-uploaded and should be with full days now.
