### ISSUE TITLE
Missing 2024-02 Monthly Klines Data for Spot 

### ISSUE THREAD

**Issue by baoutch** [binance/binance-public-data#321]
02-2024 spot klines monthly data are missing on all symbols (as far as the ones i usually download through scripts)

If you browse for instance here :

https://data.binance.vision/?prefix=data/spot/monthly/klines/BTCUSDT/1h/
https://data.binance.vision/?prefix=data/spot/monthly/klines/ETHUSDT/1h/

Data from February 2024 are not present (it is now march 9th)

Thanks

**Comment by aisling-2** [comment]
We'll get into it soon. thank you

**Comment by aisling-2** [comment]
They've been uploaded! :)
