### ISSUE TITLE
 response content: b'{"code":-1002,"msg":"You are not authorized to execute this request."}'

### ISSUE THREAD

**Issue by leewi9** [binance/binance-public-data#323]
Following Futures_Order_Book_Download/Futures-order-book-Level2-data-download.py

Execute get_futures_orderbook_download_id method, use my API, it is valid, and get this error msg:

 response content: b'{"code":-1002,"msg":"You are not authorized to execute this request."}'

 why?

**Comment by aisling-2** [comment]
It's complicated to immediately know the source of failure as it can be several and it's related with your own personal API setup. The troubleshooting needs to be on your side, you can look at this topic for some ideas on where to start: https://dev.binance.vision/t/error-you-are-not-authorized-to-execute-this-request/8102/2
