### ISSUE TITLE
What are those folders for?

### ISSUE THREAD

**Issue by astrocodie** [binance/binance-public-data#329]
Hello,

there are no explanation for those folders.

below this folder
https://data.binance.vision/?prefix=data/futures/um/daily/aggTrades/

there are

BTCUSDT/
BTCUSDT_210326/ 
BTCUSDT_210625/ 
BTCUSDT_210924/ 
BTCUSDT_211231/ 
BTCUSDT_220325/ 
BTCUSDT_220624/ 
BTCUSDT_220930/ 
BTCUSDT_221230/ 
BTCUSDT_230331/ 
BTCUSDT_230630/ 
BTCUSDT_230929/ 
BTCUSDT_231229/ 
BTCUSDT_240329/ 
BTCUSDT_240628/ 
BTCUSDT_240927/

there are BTCUSDT and why there are the others folder with date postfixed?

please carify me about those folders.

Thank you.

**Comment by aisling-2** [comment]
While most symbols listed in Futures have perpetual contracts, some of them can have a delivery date, which is the case of `BTCUSDT` and that's what date in the folders represent. 
You can confirm this by searching in the UI: https://www.binance.com/en/futures/BTCUSDT
