### ISSUE TITLE
Many USDⓢ-M Perpetual AggTrades and Klines data missing for 2024-04-18

### ISSUE THREAD

**Issue by dylanmckendry** [binance/binance-public-data#330]
Many of the AggTrades and Klines are missing for 2024-04-18. I included a few links of the missing files but there are more.

[SANDUSDT-aggTrades-2024-04-18.zip](https://data.binance.vision/data/futures/um/daily/aggTrades/SANDUSDT/SANDUSDT-aggTrades-2024-04-18.zip)

[SNXUSDT-aggTrades-2024-04-18.zip](https://data.binance.vision/data/futures/um/daily/aggTrades/SNXUSDT/SNXUSDT-aggTrades-2024-04-18.zip)

[MANAUSDT-1d-2024-04-18.zip](https://data.binance.vision/data/futures/um/daily/klines/MANAUSDT/1d/MANAUSDT-1d-2024-04-18.zip)

**Comment by aisling-2** [comment]
We're resolving this soon. Please recheck after 2 days.
