### ISSUE TITLE
BTCUSDT data for 2024-04-18 does not exist!

### ISSUE THREAD

**Issue by enriquepiatti** [binance/binance-public-data#331]
Hi, is there any problem with the aggTrades from 2024-04-18 in BTCUSDT? the files was not created:

https://data.binance.vision/?prefix=data/futures/um/daily/aggTrades/BTCUSDT/

**Comment by yaroshoris** [comment]
same issue with 
File not found: https://data.binance.vision/data/futures/um/daily/klines/ADAUSDT/1m/ADAUSDT-1m-2024-04-18.zip

**Comment by aisling-2** [comment]
We're resolving this soon. Please recheck after 2 days.

**Comment by solutionsGH** [comment]
This should be solved now, so we're closing the issue.
