### ISSUE TITLE
[Need Help]Service unavailable

### ISSUE THREAD

**Issue by parsleye** [binance/binance-public-data#332]
met this error when requesting open interest api
```
Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error.
```

**Comment by aisling-2** [comment]
The error reason is as stated in the error message, you can't use the API endpoint due to your location.
Nevertheless, this topic is unrelated to Public Data (data.binance.vision), so closing the issue.
