### ISSUE TITLE
klines missing for XMRUSD_PERP from 2024-02-15  /dapi/v1/continuousKlines broken

### ISSUE THREAD

**Issue by ejbenven** [binance/binance-public-data#333]
**Bug**

The most recent file in https://data.binance.vision/?prefix=data/futures/cm/daily/klines/XMRUSD_PERP/4h/ is dated from 2024-02-16
Querying /dapi/v1/klines similarly don't give us information past this date.

Querying /dapi/v1/continuousKlines for XMRUSD yields results for up to today, but all entries have 128.03538479 set as their open, close, high, and low price.

**Comment by dylanmckendry** [comment]
It was delisted on 2024-02-15

https://www.binance.com/en/support/announcement/binance-will-delist-ant-multi-vai-xmr-on-2024-02-20-f73b083ba6834771b07dbe5319917ae5

**Comment by aisling-2** [comment]
Thanks for the share @dylanmckendry, it's indeed related with the delisting, so `data.binance.vision` is returning as it's expected.
