### ISSUE TITLE
Many USDⓢ-M bookTicker data is missing starting from April 1st, 2024

### ISSUE THREAD

**Issue by qevc** [binance/binance-public-data#334]
For many (possibly all) USDⓢ-M futures pairs, bookTicker data:
- daily files are missing from 2024-04-01 till today, 2024-05-13
- monthly file (2024-04) contains data only for first few hours from 2024-04-01

examples:
- daily: [BTCUSDT](https://data.binance.vision/?prefix=data/futures/um/daily/bookTicker/BTCUSDT/), [BCHUSDT](https://data.binance.vision/?prefix=data/futures/um/daily/bookTicker/BCHUSDT/), [LTCUSDT](https://data.binance.vision/?prefix=data/futures/um/daily/bookTicker/LTCUSDT/), [ETHUSDT](https://data.binance.vision/?prefix=data/futures/um/daily/bookTicker/ETHUSDT/), [SOLUSDT](https://data.binance.vision/?prefix=data/futures/um/daily/bookTicker/SOLUSDT/), [XMRUSDT](https://data.binance.vision/?prefix=data/futures/um/daily/bookTicker/XMRUSDT/), [XRPUSDT](https://data.binance.vision/?prefix=data/futures/um/daily/bookTicker/XRPUSDT/)
- monthly: [BTCUSDT](https://data.binance.vision/?prefix=data/futures/um/monthly/bookTicker/BTCUSDT/), [BCHUSDT](https://data.binance.vision/?prefix=data/futures/um/monthly/bookTicker/BCHUSDT/), [LTCUSDT](https://data.binance.vision/?prefix=data/futures/um/monthly/bookTicker/LTCUSDT/), [ETHUSDT](https://data.binance.vision/?prefix=data/futures/um/monthly/bookTicker/ETHUSDT/), [SOLUSDT](https://data.binance.vision/?prefix=data/futures/um/monthly/bookTicker/SOLUSDT/), [XMRUSDT](https://data.binance.vision/?prefix=data/futures/um/monthly/bookTicker/XMRUSDT/), [XRPUSDT](https://data.binance.vision/?prefix=data/futures/um/monthly/bookTicker/XRPUSDT/)

**Comment by aisling-2** [comment]
https://www.binance.com/en/support/faq/how-to-download-historical-market-data-on-binance-5810ae42176b4770b880ce1f14932262

Hi @qevc, thanks for the post. What you're seeing is expected. Binance Futures has stopped providing historical data on bookticker. Please use websocket to listen to this data from now on. 
This data might be provided again in the futures, but there's no timeline for it.
