### ISSUE TITLE
Data shows different values than website

### ISSUE THREAD

**Issue by Pimpin321** [binance/binance-public-data#34]
If one downloads the 1-min candle data here:
https://data.binance.vision/?prefix=data/futures/um/monthly/klines/BTCUSDT/1m/

and compares it with the values on the binance website for 
BTCUSDT in 1-min resolution. 

The values don't fit. For example the website shows for 30 April 2021 13:18
O: 54267.75
H: 54344.95
etc. 

Which is completely different than the downloaded values
30.04.2021 13:18:00 
O=54495.34
H=54538.38
.......

**Comment by yohplala** [comment]
Hi there,
Interested in knowing more about this topic, I add a screenshot of the candle mentionned by @Pimpin321 
That can help the discussion.

@Pimpin321
I disagree with you. See at the screenshot I took on binance website.
Are you in UTC time? (by default, it sets to your own local time, see at the bottom left of the screen)

ok for you?
![binance2](https://user-images.githubusercontent.com/13206058/119237139-b0e20880-bb3b-11eb-9f9d-9c67188b2966.png)

**Comment by Pimpin321** [comment]
Hi yohplala, 

Thanks man! Sorry that it took so long to answer but i was drounding in work the last days. That helped, it was a combination of things that led to me not understanding: intuitively i thought that the time would be the same as on page. Then i searched for the exact price in the data opened in OneNote++ but it somehow didn't find it (sometimes the search seems not to be working right). Anyways that helped. 

But one thing i stumbled across which is strange is the first candle, same timestamp different story.

![image](https://user-images.githubusercontent.com/51787560/119642831-6c948800-be1b-11eb-871c-3b958378b889.png)

Volume of the first candle with 1.5 Mio BTC seems wrong, would be staggering 90 billion USD in 1-min...


To your PS: Well in the monthly data the 30th is kinda the closest you can go, but yes it was tedious as hell ;)

**Comment by hj-1994** [comment]
Thanks ！Another question is whether there are ask1 and bid1 data.

**Comment by yohplala** [comment]
Thinking of it, it is probably Binance UI system that applies itself a `.drop_duplicates(keep='last')`...

**Comment by Pimpin321** [comment]
Hi yohplala, 
somehow the notification didn't reach me. 

> Hey man, really, to save the others some efforts, could you put a screenshot of said candle?
Ok, I do it for you once again.

The picture i showed you was from the txt file? Why all the work to look for the candle on the UI? I just wanted that someone looks in the csv file. that you get if you follow the link from the main post.

So far no answer from Binance the new monthly file for May contains the same duplicate entry. Would be nice if someone - hopefully from Binance - could explain this, it's certainly a bug in the candles format to have a candle twice.

Thanks for the work yohplala, but part of it was not needed, asked for.

Anyways have a good one

**Comment by yohplala** [comment]
>but part of it was not needed, asked for

I am sorry if my tone sounds aggressive, this has not been my intention.
By showing the UI, one may check which candle is the right one(according to the UI, so according Binance team assuming they are doing things intentionally).
Of course the 1st one is surprising because of the volume. But high/low/close values are also noticeably different.

This leads me to think that the 1st candle might be for a different timeframe than 1mn.
Volume is big. Can you try to see if it would fit a full month candle?
Maybe each month, the 1st candle is that of the month?
Bests,

**Comment by Pimpin321** [comment]
Hi yohplala, 
no problem its very good to talk to you. 

> Volume is big. Can you try to see if it would fit a full month candle?
interesting hypothesis. I aggregated the data from 1st of May till 30th May (yeah that's when the data ends).
But the result is very clear: No it's not the monthly candle. Volume for the timeframe would be even much higher with (approx 16 155 564.34 btc) and the low would be with 28 688 much much lower.

Another thing i noticed is: some months its the first candle, in other months like may its the second candle that has a volume >1Mio btc. I am now filtering now with the rule if there is a candle within the first 5 candles has a volume over 1 mio drop it.

Another thing is may has 31 days but the data Ends exactly at 30th of may 23:59:00. complete last day missing.

**Would be really cool if someone from binance could look into this. There are some oddities going on with the data, we can not really solve alone.**

All the best to you yohplala!

**Comment by yohplala** [comment]
hi @ishuen,
Please, can we have your feedback on above questions?
Thanks a lot for your help,
Bests,

**Comment by ishuen** [comment]
Hi.
Let me first make a small summary from you guys discussion, correct me if I miss anything.
1. Why are there duplicate timestamps in csv file?
2. Why the volume indicated at the same timestamp differs?
3. How to cope with the records mentioned above?
4. 31st day of the month in csv file is missing. (Will verify it with team)

**Comment by Pimpin321** [comment]
Hi ishuen good to hear from you, 
your questions are good. I would just write No 1 more precise: 
**
**1. Why is the **first** timestamp (aka Candle) always twice in the files, with one of them having an absurdly high volume?** If in future there are more duplicates it would be interesting of course too.
**

The rest ist just fine...

**Comment by ishuen** [comment]
Okay so for the first 3 questions,

> 1. Why is the first timestamp (aka Candle) always twice in the files, with one of them having an absurdly high volume?
> 2. Why the volume indicated at the same timestamp differs?
> 3. How to cope with the records mentioned above?

One of the data row with duplicated timestamp somehow looks like the accumulated data for the whole month  (still checking) and that's why the volume is large. You can see the its open time (1st column) is the beginning of the month and the close time (7th column) is almost the last moment of the month. Meanwhile, please ignore that data row.

> 4. 31st day of the month in csv file is missing. (Will verify it with team)

The new file is uploaded, please check if it is completed or not, thanks.

**Comment by Pimpin321** [comment]
Hi ishuen, 
good to have you on board! I downloaded the file and yes the 31st is now included. Did Binance give a reason what happened?
To your questions:
> One of the data row with duplicated timestamp somehow looks like the accumulated data for the whole month (still checking) and that's why the volume is large.
Well i did aggregate the data from 1st of May to 30th and it didn not match (you can find this in one of my previous posts)
I did aggregate it again with the new data and the result is (for 1st till 31st):
![Monthly_Candle](https://user-images.githubusercontent.com/51787560/121706146-a29d6180-cad5-11eb-8fe4-b8f27030907b.PNG)

**Comment by ishuen** [comment]
I see, thanks for checking the data from your side. Please ignore that record if you are still using the old csv file. The new one should not have it.
Regarding the column names, you can check readme.md file, spot klines column name. Futures kline is the same as it.

**Comment by Pimpin321** [comment]
Hi ishuen, yohplala, 
thanks for the tipp. :+1: 

**One thing that "scared" me a bit is while reading i found the last column "ignore" Should one have a filter and ignore rows with that attribute beeing 1?**

Another question: Data-quality is never perfect. Even if one buys data from an official stock market for 15K € there are mistakes in it. 
So how would you rate the data quality for the binance data? I it very Beta? Is there a list with limitations, problems to be expected? It is not fun to build models on data just to find out 4 weeks later that one can not use them....

Thanks!

**Comment by yohplala** [comment]
> **One thing that "scared" me a bit is while reading i found the last column "ignore" Should one have a filter and ignore rows with that attribute beeing 1?**

If I am right, the last column is the 8th one.
In the readme (or project presentation page of the git repo), it is called:
_Was the trade the best price match_

In Binance documentation, 'ignore' is not the column name. It is a request to the user: _please, ignore this column_.
Make a check, but the content of this column is always 1 as far as I can tell, and so is useless and you can ignore it.

This is my understanding.

**Comment by Pimpin321** [comment]
Hi yohpla, 

but if you look in the readme under spot / Klines it is the name of the column, not the content of the first row. 

>In Binance documentation, 'ignore' is not the column name. It is a request to the user: please, ignore this column.
Make a check, but the content of this column is always 1 as far as I can tell, and so is useless and you can ignore it. 

Is there another documentation i thought that is it. 
And it should always be 0 according to the data. Which wuld make sense, like don't ignore.

**Comment by yohplala** [comment]
Hi sorry, yes my bad, I looked at 'aggTrade' data.

**Comment by Pimpin321** [comment]
So do you or someone know if one should ignore a row turns into a 0?

**Comment by volkan-akkus-tr** [comment]
@yohplala @Pimpin321 
Hi there, 
Do you still feel uncomfortable with data integrity ?
Do you trust 100% now to Binance as data supplier ?
