### ISSUE TITLE
U-pairs bookDepth

### ISSUE THREAD

**Issue by michael2015tse** [binance/binance-public-data#345]
Hi team,

I'm looking for some data that provide snapshot depth, similar to what Partial Book Depth Streams offer in Websocket Market Stream. 
Is the `bookDepth` at https://data.binance.vision/?prefix=data/futures/um/daily/bookDepth/ what I'm looking for, and what does the columns mean in bookdepth csv? Thank you!

![image](https://github.com/user-attachments/assets/348ee097-cbcb-42ce-9933-f57a5510f544)

**Comment by darienhuang** [comment]
bookdepth dataset is no longer updated
