### ISSUE TITLE
Futures data gives "Access Denied" when downloading

### ISSUE THREAD

**Issue by Thomas-X** [binance/binance-public-data#35]
See [here](https://data.binance.vision/?prefix=data/futures/um/daily/trades/BTCUSDT/) and click any of the zip files. The specific link would be this: https://data.binance.vision/data/futures/um/daily/trades/BTCUSDT/BTCUSDT-trades-2021-05-24.zip.

RequestID: `XTCA65VBX2RKASJF`

**Comment by ishuen** [comment]
Thanks for reporting, will check it with the team.

**Comment by Thomas-X** [comment]
I'm able to download it from my side now, wasn't throttling because I could still download spot data, but it works now so thanks guys! 

Cheers!
