### ISSUE TITLE
Excuse me, what is the aggregation mode of aggtrade

### ISSUE THREAD

**Issue by hj-1994** [binance/binance-public-data#36]

**Comment by yohplala** [comment]
[Official doc here](https://binance-docs.github.io/apidocs/spot/en/#aggregate-trade-streams):

_The Aggregate Trade Streams push trade information that is aggregated for a single taker order._


A more thorough answer [here](https://dev.binance.vision/t/recent-trades-historical-and-aggregate/128/2):

_A raw trade is strictly defined as 1 taker and 1 maker trading some quantity at a price, but an aggregate trade is defined as 1 taker, n makers, trading the sum of all the individual raw trade quantities at a price.
For example, a user places a market order to buy 10 BNB for $16.50. The user trades with 3 different makers at the price of $16.50 for 2, 5, and 1 BNB, and then 1 maker at the price of $16.51 for 2 BNB._

**Comment by hj-1994** [comment]
Thanks ！Another question is whether there are ask1 and bid1 data.

**Comment by hj-1994** [comment]
Thanks ！Another question is whether there are ask1 and bid1 data.

**Comment by yohplala** [comment]
Sorry I don't see and I don't know what is 'ask1' and 'bid1'? Where do you see this mentionned?

**Comment by 2pd** [comment]
This is not related to public data,  please open a topic at dev.binance.vision.
