### ISSUE TITLE
liquidationSnapshot data missing

### ISSUE THREAD

**Issue by stephenLee** [binance/binance-public-data#361]
https://data.binance.vision/?prefix=data/futures/um/daily/liquidationSnapshot/BTCUSDT_240628/
https://data.binance.vision/?prefix=data/futures/um/daily/liquidationSnapshot/BTCUSDT_240927/

**Comment by darienhuang** [comment]
this data is no longer provided

**Comment by PerichrisTW** [comment]
Hello sir,
thank you for the superrrrb convenient website,
just purely curious about why the liquidation data is no longer provided because it's pretty helpful.
thank you for your reply and the amazing work of the website.
