### ISSUE TITLE
 data

### ISSUE THREAD

**Issue by net2221** [binance/binance-public-data#375]
over

**Comment by MAKAR1031** [comment]
Faced the same problem. For example, for ETHUSDT agregate trades is available only until 12th november on this page:

https://data.binance.vision/?prefix=data/spot/daily/aggTrades/ETHUSDT/

This is true for all assets

**Comment by tedteng85** [comment]
has this happend before? any idea when its gonna be fixed?

**Comment by TATAjiHAU** [comment]
they are intentionally not doing this... Think about it. Why would they give so much in-depth insights to normal retailers.. They have huge data gaps amongst all the data they provide !!!

**Comment by alplabin** [comment]
Thank you for pointing out the issue. The missing data are now being uploaded.

**Comment by MAKAR1031** [comment]
@alplabin Please check the uploaded data. The file obtained for ETHUSDT for 11/19/2024 using public endpoint ["Compressed/Aggregate trades list"](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/public-api-endpoints#compressedaggregate-trades-list) differs from the one in the archive at https://data.binance.vision/data/spot/daily/aggTrades/ETHUSDT/ETHUSDT-aggTrades-2024-11-19.zip

I am sure that the file received via the endpoint is correct. For example, for 11/12/2024 the files were completely identical

**Comment by MAKAR1031** [comment]
Here is the file I received (ETHUSDT, 11/19/2024):

https://drive.google.com/file/d/1Nl7qvJLUwEWox5Zs23pr9z19ddswRldS/view?usp=sharing

By the way, ETHUSDT data for 11/18/2024 matched completely

**Comment by MAKAR1031** [comment]
I see that the [file ETHUSDT by 11/19/2024](https://data.binance.vision/data/spot/daily/aggTrades/ETHUSDT/ETHUSDT-aggTrades-2024-11-19.zip) has been updated. Now the files are identical by SHA256
