### ISSUE TITLE
What is the regular update date for each month?

### ISSUE THREAD

**Issue by kelvinxue** [binance/binance-public-data#38]
For example, at the begining of June (20210604), I found that the 202105's data is not ready

What is the expected date in June that I can download May's data

Thx

**Comment by ishuen** [comment]
Hi. Ideally monthly data should be uploaded on the first date of the next month. Do you still remember which data set was missing at that time?

**Comment by kelvinxue** [comment]
i guess i am not the only one who found that issue, the same issue as this post: 

https://github.com/binance/binance-public-data/issues/39

**Comment by ishuen** [comment]
That is another issue, I think. #39 indicates that the file was presented but the data size was much smaller than expectation. In your case, the files you were looking for are not there, correct?

**Comment by 2pd** [comment]
it will take a little bit of time to upload all monthly data. It will be finished in 1-3 days.
