### ISSUE TITLE
Missing huge amount of trade data for 2021-05

### ISSUE THREAD

**Issue by ramazanpolat** [binance/binance-public-data#39]
I've downloaded XRPUSDT trade for both 2021-04 and 2021-05 from:
[https://data.binance.vision/data/spot/monthly/trades/XRPUSDT/XRPUSDT-trades-2021-04.zip](https://data.binance.vision/data/spot/monthly/trades/XRPUSDT/XRPUSDT-trades-2021-04.zip)
and
[https://data.binance.vision/data/spot/monthly/trades/XRPUSDT/XRPUSDT-trades-2021-05.zip](https://data.binance.vision/data/spot/monthly/trades/XRPUSDT/XRPUSDT-trades-2021-05.zip)

The size differs a lot.
XRPUSDT-trades-2021-04.zip: **807 MB** 
XRPUSDT-trades-2021-05.zip: **3 MB**

Same problem applies for some other currency pairs like: 
* IOTAUSDT
* FETUSDT
* OMGUSDT
* ETCUSDT
* TRXUSDT
* VETUSDT
* XLMUSDT
* XMRUSDT

For example, let's look at IOTAUSDT data for 2021-05:
[https://data.binance.vision/data/spot/monthly/trades/IOTAUSDT/IOTAUSDT-trades-2021-05.zip](https://data.binance.vision/data/spot/monthly/trades/IOTAUSDT/IOTAUSDT-trades-2021-05.zip)

The zip file is only 1KB! And it contains only 24 lines!

**CHECKSUM matches**
```bash
$ curl https://data.binance.vision/data/spot/monthly/trades/XRPUSDT/XRPUSDT-trades-2021-05.zip.CHECKSUM
9ef8bcce624c34a457757f3e1a243407f4f5ff3cd62d3460dfb3d67041340dec  XRPUSDT-trades-2021-05.zip
$ sha256sum XRPUSDT-trades-2021-05.zip
9ef8bcce624c34a457757f3e1a243407f4f5ff3cd62d3460dfb3d67041340dec  XRPUSDT-trades-2021-05.zip
```

**Comment by ishuen** [comment]
Hi. Thanks for reporting. Will check with the team.

**Comment by ishuen** [comment]
The file must be recovered. Please check it again, thanks.

**Comment by ramazanpolat** [comment]
@ishuen thank you.

Although it is resolved for XRPUSDT, there are still some symbols that have missing trade data, e.g [IOTAUSDT](https://data.binance.vision/data/spot/monthly/trades/IOTAUSDT/IOTAUSDT-trades-2021-05.zip)(it is still 1kb).

I can not check each and every symbol but I can see that the problem not resolved altogether.

**Comment by 2pd** [comment]
We are working on validating and fixing all files.

**Comment by 2pd** [comment]
These are fixed,  please check again.
