### ISSUE TITLE
CHECKSUM files don't match

### ISSUE THREAD

**Issue by jnorthrup** [binance/binance-public-data#40]
jim@okmijnuihb:/vol/kerneldev/data.binance.vision/data/spot/monthly/klines/BTCUSDT/1m$ sha256sum -c *CHECKSUM
BTCUSDT-1m-2017-08.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2017-09.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2017-10.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2017-11.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2017-12.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-01.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-02.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-03.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-04.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-05.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-06.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-07.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-08.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-09.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-10.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-11.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2018-12.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-01.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-02.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-03.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-04.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-05.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-06.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-07.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-08.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-09.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-10.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-11.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2019-12.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-01.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-02.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-03.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-04.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-05.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-06.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-07.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-08.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-09.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-10.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-11.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2020-12.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
BTCUSDT-1m-2021-01.zip: OK
BTCUSDT-1m-2021-02.zip: OK
BTCUSDT-1m-2021-03.zip: OK
BTCUSDT-1m-2021-04.zip: OK
BTCUSDT-1m-2021-05.zip: OK

**Comment by jnorthrup** [comment]
the zip files in question

```
wget -rc --no-parent https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1m/BTCUSDT-1m-20{17..21}-{01,02,03,04,05,06,07,08,09,10,11,12}.zip{,.CHECKSUM}

cd /vol/kerneldev/data.binance.vision/data/spot/monthly/klines/BTCUSDT/1m
```

```
jim@okmijnuihb:/vol/kerneldev/data.binance.vision/data/spot/monthly/klines/BTCUSDT/1m$ ls -l *zip 
-rw-rw-r-- 1 jim jim  567703 Mar  5 17:07 BTCUSDT-1m-2017-08.zip
-rw-rw-r-- 1 jim jim 1394854 Mar  5 17:07 BTCUSDT-1m-2017-09.zip
-rw-rw-r-- 1 jim jim 1689941 Mar  5 17:07 BTCUSDT-1m-2017-10.zip
-rw-rw-r-- 1 jim jim 1992238 Mar  5 17:07 BTCUSDT-1m-2017-11.zip
-rw-rw-r-- 1 jim jim 2324674 Mar  5 17:07 BTCUSDT-1m-2017-12.zip
-rw-rw-r-- 1 jim jim 2192643 Mar  5 17:07 BTCUSDT-1m-2018-01.zip
-rw-rw-r-- 1 jim jim 1911980 Mar  5 17:07 BTCUSDT-1m-2018-02.zip
-rw-rw-r-- 1 jim jim 2181245 Mar  5 17:07 BTCUSDT-1m-2018-03.zip
-rw-rw-r-- 1 jim jim 2085477 Mar  5 17:07 BTCUSDT-1m-2018-04.zip
-rw-rw-r-- 1 jim jim 2150375 Mar  5 17:07 BTCUSDT-1m-2018-05.zip
-rw-rw-r-- 1 jim jim 2042278 Mar  5 17:07 BTCUSDT-1m-2018-06.zip
-rw-rw-r-- 1 jim jim 2135665 Mar  5 17:07 BTCUSDT-1m-2018-07.zip
-rw-rw-r-- 1 jim jim 2181742 Mar  5 17:07 BTCUSDT-1m-2018-08.zip
-rw-rw-r-- 1 jim jim 2087406 Mar  5 17:07 BTCUSDT-1m-2018-09.zip
-rw-rw-r-- 1 jim jim 2071463 Mar  5 17:07 BTCUSDT-1m-2018-10.zip
-rw-rw-r-- 1 jim jim 2059163 Mar  5 17:07 BTCUSDT-1m-2018-11.zip
-rw-rw-r-- 1 jim jim 2181611 Mar  5 17:07 BTCUSDT-1m-2018-12.zip
-rw-rw-r-- 1 jim jim 2120781 Mar  5 17:07 BTCUSDT-1m-2019-01.zip
-rw-rw-r-- 1 jim jim 1915927 Mar  5 17:07 BTCUSDT-1m-2019-02.zip
-rw-rw-r-- 1 jim jim 2089484 Mar  5 17:07 BTCUSDT-1m-2019-03.zip
-rw-rw-r-- 1 jim jim 2090113 Mar  5 17:07 BTCUSDT-1m-2019-04.zip
-rw-rw-r-- 1 jim jim 2198447 Mar  5 17:07 BTCUSDT-1m-2019-05.zip
-rw-rw-r-- 1 jim jim 2177693 Mar  5 17:07 BTCUSDT-1m-2019-06.zip
-rw-rw-r-- 1 jim jim 2272709 Mar  5 17:07 BTCUSDT-1m-2019-07.zip
-rw-rw-r-- 1 jim jim 2207879 Mar  5 17:07 BTCUSDT-1m-2019-08.zip
-rw-rw-r-- 1 jim jim 2140033 Mar  5 17:07 BTCUSDT-1m-2019-09.zip
-rw-rw-r-- 1 jim jim 2217849 Mar  5 17:07 BTCUSDT-1m-2019-10.zip
-rw-rw-r-- 1 jim jim 2133961 Mar  5 17:07 BTCUSDT-1m-2019-11.zip
-rw-rw-r-- 1 jim jim 2197736 Mar  5 17:07 BTCUSDT-1m-2019-12.zip
-rw-rw-r-- 1 jim jim 2224194 Mar  5 17:07 BTCUSDT-1m-2020-01.zip
-rw-rw-r-- 1 jim jim 2077466 Mar  5 17:07 BTCUSDT-1m-2020-02.zip
-rw-rw-r-- 1 jim jim 2277959 Mar  5 17:07 BTCUSDT-1m-2020-03.zip
-rw-rw-r-- 1 jim jim 2164104 Mar  5 17:07 BTCUSDT-1m-2020-04.zip
-rw-rw-r-- 1 jim jim 2265162 Mar  5 17:07 BTCUSDT-1m-2020-05.zip
-rw-rw-r-- 1 jim jim 2131275 Mar  5 17:07 BTCUSDT-1m-2020-06.zip
-rw-rw-r-- 1 jim jim 2203867 Mar  5 17:07 BTCUSDT-1m-2020-07.zip
-rw-rw-r-- 1 jim jim 2257720 Mar  5 17:07 BTCUSDT-1m-2020-08.zip
-rw-rw-r-- 1 jim jim 2174602 Mar  5 17:07 BTCUSDT-1m-2020-09.zip
-rw-rw-r-- 1 jim jim 2220928 Mar  5 17:07 BTCUSDT-1m-2020-10.zip
-rw-rw-r-- 1 jim jim 2228586 Mar  5 17:07 BTCUSDT-1m-2020-11.zip
-rw-rw-r-- 1 jim jim 2304125 Mar  5 17:07 BTCUSDT-1m-2020-12.zip
-rw-rw-r-- 1 jim jim 2399839 Mar  5 17:07 BTCUSDT-1m-2021-01.zip
-rw-rw-r-- 1 jim jim 2157176 Mar  5 17:07 BTCUSDT-1m-2021-02.zip
-rw-rw-r-- 1 jim jim 2375051 Apr  1 11:07 BTCUSDT-1m-2021-03.zip
-rw-rw-r-- 1 jim jim 2265385 May  2 06:53 BTCUSDT-1m-2021-04.zip
-rw-rw-r-- 1 jim jim 2407984 Jun  2 06:22 BTCUSDT-1m-2021-05.zip
```

**Comment by 2pd** [comment]
it works fine for me, please check again.

**Comment by TrentHouliston** [comment]
I have the exact same issue with most of the data before 2021
