### ISSUE TITLE
request time out

### ISSUE THREAD

**Issue by shanaou11** [binance/binance-public-data#45]
https://github.com/binance/binance-public-data/blob/ba11edcf4fd22e65717cd5704e52c09c67cad3da/python/utility.py#L20

Sorry if I bother you all. I am new here.

When I want to get all symbols, i just want to filter it by USDT only. first thing I do is get all symbols. But I'm getting error request time out all the time. Yes I didn't input -s args when running the python file because I want to get all the symbols first.

This is the error I get:

> urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Thank you...

**Comment by 2pd** [comment]
this is not related to the script. It is most likely that there is connection issue.

**Comment by shanaou11** [comment]
But when I use -s args it work well. 
This is my command when without -s args
`python download-kline.py -i 1d`

This is my command with -s args:
`python download-kline.py -s ADAUSDT -i 1d`

I struggle with this problems for weeks. Is there something I miss?
Thank you for the respond by the way

**Comment by ren0d1** [comment]
I just downloaded the project and tried the command `python download-kline.py` and it ran without any issue. As 2pd said, it is more likely to be an issue on your side than from the project itself.
My advice would be to make sure that you're first trying the code without any modification and then, if you're still encountering issues, I would suggest trying to contact the endpoint `https://api.binance.com/api/v3/exchangeInfo` directly with tools like curl or postman and check that you don't get any issue there already.

Then, just out of curiosity, I tried to filter the symbols before the crawler executes (my python knowledge is rock-bottom) and it plainly worked. Here is how the end of my `download-kline.py` file looks like now in case it may be of use:
```
# function that filters symbols
def filter_symbols(symbol):
    symbols = ['USDT', 'BUSD'] #currencies to look for

    for s in symbols:
      if(re.search(s, symbol, re.IGNORECASE)):
          return True
      else:
          return False

if __name__ == "__main__":
    parser = get_parser('klines')
    args = parser.parse_args(sys.argv[1:])

    if not args.symbols:
      print("fetching all symbols from exchange")
      symbols = get_all_symbols()
      num_symbols = len(symbols)
    else:
      symbols = args.symbols
      num_symbols = len(symbols)
    
    filtered_symbols = list(filter(filter_symbols, symbols))
    num_filtered_symbols= len(filtered_symbols)

    #print(filtered_symbols)

    if args.dates:
      dates = args.dates
    else:
      dates = pd.date_range(end = datetime.today(), periods = MAX_DAYS).to_pydatetime().tolist()
      dates = [date.strftime("%Y-%m-%d") for date in dates]
      download_monthly_klines(filtered_symbols, num_filtered_symbols, args.intervals, args.years, args.months, args.startDate, args.endDate, args.folder, args.checksum)
    download_daily_klines(filtered_symbols, num_filtered_symbols, args.intervals, dates, args.startDate, args.endDate, args.folder, args.checksum)
```

**Comment by 2pd** [comment]
Thanks for the feedback @ren0d1.
This handy python script can be adjusted or modified for your own usage.

I will close this issue, please open a new one if there is any concern.

**Comment by shanaou11** [comment]
Thank you so much @2pd @ren0d1  for the respond!

> I would suggest trying to contact the endpoint https://api.binance.com/api/v3/exchangeInfo directly with tools like curl 

yes, i already try this, and still no respond. 

I think the problem is my internet provider block the URL. One last think I want to try is use VPN first, then run the code. I live in Indonesia by the way, where the government control which URL or domain that you can access. Sometimes it miss block the URL. I miss this poin until your responses.

and thank you @ren0d1 for the function, it help much.
```
def filter_symbols(symbol):
    symbols = ['USDT', 'BUSD'] #currencies to look for

    for s in symbols:
      if(re.search(s, symbol, re.IGNORECASE)):
          return True
      else:
          return False
```
