### ISSUE TITLE
Missing days

### ISSUE THREAD

**Issue by ren0d1** [binance/binance-public-data#46]
I have just downloaded data for multiple timeframes of the "BNBUSD_PERP" on CM futures, but when trying to use it, I encountered a weird behavior in my code. After first looking into my code, obviously, I just so happen to discover that the data of some days are available on lower timeframes such as 30m or 5m, but aren't on the 1d timeframe.

I was wondering why is that so and if it was intentional, it could be interesting to make a note about it.

**Comment by 2pd** [comment]
could you please give the url of which data you are looking at?
 e.g. `https://data.binance.vision/?prefix=data/futures/cm/monthly/indexPriceKlines/`

**Comment by ren0d1** [comment]
Of course.
The problematic dataset is available on this page [https://data.binance.vision/?prefix=data/futures/cm/monthly/klines/BNBUSD_PERP/1d/](https://data.binance.vision/?prefix=data/futures/cm/monthly/klines/BNBUSD_PERP/1d/) under the name `BNBUSD_PERP-1d-2021-05.zip`

**Comment by SanjayaBR** [comment]
Thanks for reporting the issue. It should be fixed by now. Please confirm.

**Comment by ren0d1** [comment]
The reported file has been correctly updated accordingly, but whether the issue that caused this has been resolved or not that I can't say. That would be interesting to know though as I was using your service to avoid crawling through the API. But if the completeness cannot be guaranteed, I would rather know and act accordingly.

**Comment by 2pd** [comment]
@ren0d1  thanks for your suggestion, we will keep improving the tool that handling the data.
