### ISSUE TITLE
Is it possible to add Open Interest data?

### ISSUE THREAD

**Issue by KostyaCholak** [binance/binance-public-data#48]
Hello, could you please add data for Open Interest (from this endpoint GET /futures/data/openInterestHist)
Only 30 days are available via API and I can't find open interest in csv files for futures.
Also adding open interest statistics (Long/Short Ratio etc) would be great!!

Thanks!

**Comment by cqcn1991** [comment]
Hi, it is already in our plan, but not in the near future, so i'm sorry that you might not be able to access in recent months. we'll let you know when it's shipped.

**Comment by KostyaCholak** [comment]
Got it. Thanks! 

Best Regards,
Kostya Cholak

**Comment by excme** [comment]
> Hello, could you please add data for Open Interest (from this endpoint GET /futures/data/openInterestHist)
> Only 30 days are available via API and I can't find open interest in csv files for futures.
> Also adding open interest statistics (Long/Short Ratio etc) would be great!!
> 
> Thanks!

Hi, Did you have success to find open interest history of binance futures?

**Comment by georgandreasjaksch** [comment]
I'd love to have OI as well as Long/Short rate data as well. Any ETA on this? Love the data provided here so far a lot, but this would be the icing on the cake :-)
