### ISSUE TITLE
What is the Timezone in Funding rate?

### ISSUE THREAD

**Issue by Pimpin321** [binance/binance-public-data#54]
Hello, 
i downloaded the Perpetual funding rate from here:

https://www.binance.com/en/futures/funding-history/1

in what timezone is the time in the timestamps? What means
10:00:00"? like in the first row:

"2021-07-09 10:00:00","BTCUSDT Perpetual","8h","-0.0174%"

I am asking this since in the Price Data for the Perpetual the timestamp is UTC. 
The UTC times for the funding are as we know 8:00, 16:00, 00:00 UTC

And in older timestamps there is everything 1h off:

"2019-11-08 17:00:00","BTCUSDT Perpetual","8h","0.0100%"
"2019-11-08 09:00:00","BTCUSDT Perpetual","8h","0.0100%"
"2019-11-08 01:00:00","BTCUSDT Perpetual","8h","0.0125%"

It would be be better if all data from binance would just use UTC as a timestamp.
Greetings

**Comment by yohplala** [comment]
Hi @Pimpin321 
If you are interested in funding data available on 'binance data vision' as well, would mind thumbing up #44 I would feel less lonely in asking it ;)
:)

**Comment by Pimpin321** [comment]
Hi yohplala or someone from Binance, 
so do you know how that works with the timestamps? I can not backtest if i don't what the exact time is, it needs to fit to the underlying Perpetual prices. Was the funding in Nov 2019 really at a different time? this would be good to know?

Thanks..
PS I guess the voting is closed on you proposition?

**Comment by ishuen** [comment]
Hi. If you download directly from this site. It should be the local time.

**Comment by cqcn1991** [comment]
i just send this issue to related team; they will improv on this (may add time zone description later on that data file). regarding your question, it's in your timezone at the moment.

**Comment by Pimpin321** [comment]
> Hi. If you download directly from this site. It should be the local time.
Yes that's true Is there a link where it is UTC? How would i "non diretly download it?"

 i just send this issue to related team; they will improv on this (may add time zone description later on that data file). regarding your question, it's in your timezone at the moment.

Thanks cqcn1991!
