### ISSUE TITLE
没有合约按天打包的k线数据

### ISSUE THREAD

**Issue by green23** [binance/binance-public-data#56]
现货的k线数据有daily的数据，但是期货的k线数据只有monthly，没有daily，可以新增daily数据吗

**Comment by cqcn1991** [comment]
大佬，你看看这个？ 
https://data.binance.vision/?prefix=data/futures/um/monthly/klines/BTCUSDT/1d/

**Comment by green23** [comment]
> 大佬，
> 请问你说的是1d interval的k线，还是每天新增的按天打包的?
> 如果是1d interval的，可以看这个 https://data.binance.vision/?prefix=data/futures/um/monthly/klines/BTCUSDT/1d/
> 如果是确定要daily 更新的，这个我们讨论一下，有安排了告诉您

我表达地不清楚，是合约的各interval的按天打包的数据。目前获取该数据是通过rest api来获取的，但是fapi经常请求失败，所以想从data.binance.vision网站获取按天打包的k线数据。

**Comment by cqcn1991** [comment]
我们已经安排上了，应该近期能上线. 等有具体时间后会告诉你

**Comment by green23** [comment]
> 我们已经安排上了，应该近期能上线. 等有具体时间后会告诉你

好的，太感谢了

**Comment by cqcn1991** [comment]
> 好的，太感谢了

你好，目前已经soft launch. 已经经过QA，你可以先试用一下. 稳定以后全量使用

**Comment by green23** [comment]
> > 好的，太感谢了
> 
> 你好，目前已经soft launch. 已经经过QA，你可以先试用一下. 稳定以后全量使用

ok,看到6月1号以后的数据了，感谢
