### ISSUE TITLE
Huge Differences in Charts on website in "time" resolution

### ISSUE THREAD

**Issue by GBC999** [binance/binance-public-data#59]
Hello, 
today while i watching the huge price spike of BTC due to the Amazon rumours, i found hefty inconsistencies in the "BTCUSDT" data shown in the chart on the website. 

Edit: if you have trouble with the links (onedrive did not work for some users). Take those 3 links - no viruses promis;)
https://ibb.co/TtQVmpC
https://ibb.co/qs9wfW2
https://ibb.co/ZcMjpH5
---------End of Edit-----

If you look at the 1h resolution the high is shown with at  48268.6 at 1:00h UTC time (The timezone from my computer Is middle european summer time that is why it is shown as 3:00h)
https://1drv.ms/u/s!AhL9Tt_7-jkNghfF-NfxN-_fZBDm?e=W7vvJr

in 15min resolution in BTCUSDT it is the same High at 5:00h:
https://1drv.ms/u/s!AhL9Tt_7-jkNghfF-NfxN-_fZBDm?e=KYxtQw

**But if you take the "Time" resolution you get a completely Different High of 39 814 USD which is 18% (!!) lower than the previous 2:**

https://1drv.ms/u/s!AhL9Tt_7-jkNghh0TOD8BJ_v_Im9

This difference is huge and makes it difficult to trust/use the data. 
Greetings

**Comment by GBC999** [comment]
Could someone look into this please? i am having trouble using the data for trading strategies, since i am not shure what to make of the situation.

Greetings

**Comment by ishuen** [comment]
Hi. Thanks for the feedback. However, those resources you shared are not accessible. It shows "ERR_ACCESS_DENIED".

**Comment by GBC999** [comment]
Hi ishuen: strange the links work on my computer even if i am logged out. I uploaded them again:

https://ibb.co/TtQVmpC
https://ibb.co/qs9wfW2
https://ibb.co/ZcMjpH5

**Comment by GBC999** [comment]
i downloaded the daily/aggTrades Data and found out that they show with 48 168.6 $
the same High as the 15min and 1h data. 

**This raised more the question what "Time" Data on the website actually is (I used to watch at this), where it stems from. And what data is provided for the downloads for https://data.binance... futures/um  for "daily" and "monthly" (to be sure that i don't download erreonous data).**

Hope someone can look into this! Was a bit of a shocker for me
Thx.

**Comment by cqcn1991** [comment]
hi, i asked our team; the `time` only shows the `close` price, which is a common practice in the industry.

**Comment by GBC999** [comment]
Hi cqcn1991 good to hear from you!

> hi, i asked our team; the time only shows the close price, which is a common practice in the industry

I analyzed this yesterday with a database tool and i think something with the aggregation of the data is wrong.

This is the time view on the website: 
https://ibb.co/WKPLrmH

First of all the "Time" data is actually a 1min Kline (or often referred to as 1min "candles"). 
The red circle shows the 1 minute Kline going from 01h:02m:00sec.000ms till 01:02:59.000 which is thousands of trades and gives out only 4 prices: the **Open (=first quote in the intervall), High, Low, Close (last quote in the interval)**

You can see this in the the red rectangle in the upper left corner  (again my computer shows 3:02 o clock since european time MEZ=UTC+2h, but in UTC its the Kline at 1:02h). 

**So far so good. The problem is now that the prices do not match, what one would expect**

Time shows for the close: 39 525.6
I downloaded the **trades** and **AggTrades** data for the 26th I couldn't find 39 525.6 anywhere in there??Intuitively i thought trades would be EVERY trade that occured on that day. But i don't know then where "Time" gets this value from.

I then importet the data in a database tool. One can see that the last trade (aka close) in the time interval from 1:02 - 1:02:59.999 h should be 39 625.76 and not 39 525.6:
https://ibb.co/WKPLrmH

Another example is the High value for the interval which is shown with 40 050.6 but if i take the maximum price of all trades in the Interval from 01:02:00.000- 01:02:59:999h in the database tool:
https://ibb.co/C9xwMjj
with 44 000 a very different value

The other values don't macht too. 
If i had to guess, database tools often have a setting like "Maximum different values per group" when grouping the data for the klines. Its often set to 10K values maybe this caused this? (Binance has often more than 10K trades in 1-min which then would lead to many values not beeing regarded).

I would need some help me decide which data i should use for strategy testing. If someone could answer some of the questions would really help me (besides the obvious question why the values are way off):

- **If a 1-min Kline summarizes the data from e. g. 01h:02min till 01:02:59.999 does it then have the timestamp of 01:02 or 01:03 ? I am asking this since usually the timestamp of a Kline is the BEGINNING of the summarized period. But if you look at the last screenshot i posted, it shows that the high value of 48 168.6 was in the interval from 1:01h - 1:02, while the Chart on the website has the high (besides that the value is off too) at 1:02h...
- For the monthly Klines data is the 1-min data the same as the "Time" data shown on the website. Or is the 5min data aggregated differently? I asking this since i "like" 1-min resolution but don't trust the "Time" data anymore and i wonder if it would be safer to use the 5-min resolution. I am basically looking if there is some Klines data that is more reliable, recorded differently.
- **The Trades Data is simply every trade that occured on binance in the order the trades occured - right?** So if i aggregate this on my own i should be on the safe side? Or some remarks on that data too...
-  The "AggTrade" Data seems to be the same data as "trades"  only if trades have the same Timestamp AND Price then they aggregated and the volume is the sum of all trades at the same time/price. Or more differences? The structure seems a bit different too.

**Comment by cqcn1991** [comment]
noted. i need some time to check; will update you later on this.

**Comment by cqcn1991** [comment]
i think the screenshot in this comment has some issue. 

in your original screenshot `https://ibb.co/ZcMjpH5`; 

![image](https://user-images.githubusercontent.com/2425141/127802223-34bcbd87-a171-44cf-b7f1-90a8baa18829.png)

the close is 39814, and yet here it becomes 39525

what i get currently, is same as your initial screenshot; close 39814, high 48168.

![image](https://user-images.githubusercontent.com/2425141/127802130-a7dbcf33-32ca-44be-a6fb-261050499ffd.png)

and this matches the aggtrades data you get; could you check the the data at that time again?

**Comment by 630362055** [comment]
> i think the screenshot in this comment has some issue.
> 
> in your original screenshot `https://ibb.co/ZcMjpH5`;
> 
> ![image](https://user-images.githubusercontent.com/2425141/127802223-34bcbd87-a171-44cf-b7f1-90a8baa18829.png)
> 
> the close is 39814, and yet here it becomes 39525
> 
> what i get currently, is same as your initial screenshot; close 39814, high 48168.
> 
> ![image](https://user-images.githubusercontent.com/2425141/127802130-a7dbcf33-32ca-44be-a6fb-261050499ffd.png)
> 
> and this matches the aggtrades data you get; could you check the the data at that time again?

所以到底有问题还是没问题，我之前用的是API扒数据，后来发现你们这有提供数据我就想直接从你们这里下载了‘’‘

**Comment by cqcn1991** [comment]
> 所以到底有问题还是没问题，我之前用的是API扒数据，后来发现你们这有提供数据我就想直接从你们这里下载了‘’‘

在等上面那个大佬确认. 我们尽力提供准确的数据，但是bug也难以避免. 大佬你可以先用一下比比，目前质量问题比之前已经好不少了.

**Comment by GBC999** [comment]
Hi cqcn1991,
I was the last days on a trist just had time to come back this important (for me) issue.
 
**First of all could you or someone give me some information - after the work i put in this?, none of my old questions where answered**

I wold be really interested
---------------------------------------------------------------------------------------------------------------------
1. For **"daily"** data wich data do you think is better/ more error free to use the **AggTrades** or the **Trades** Data? In your answer you asked to compare with the aggTrades data (which i did below) does this indicate that it's of better quality? could you (or someone else) answer my old question of: "How does AggTrades data aggregate the data, could one give a short summary" and "Trades Data is simply all the Trades right out of the trading engine and should be "perfect".
**Are the known bugs in the mentioned 2 datastreams? one that wants to use the data for strategy testing should know of?**. The readme file barely explains lists anything. Nothing of when what error was corrrected.
2.  For **monthly** Klines data is it safe to use the 5min data or are errors to expected here, which resolution would be better?
-------------------------------------------------------------------------------------------------------------------------------------

> And this matches the aggtrades data you get; could you check the the data at that time again?

To your question:
The values on the website for the candle of 1:02 are now fixed as far as i can tell and they match the AggTrade data that i downloaded a while ago:
https://ibb.co/0JRzvX4

So what was the problem? How is it fixed? Should one rather not use "Time" but a 5min resolution rather?

Ok hope that helps and, again i would have liked to come back eralier to this since its pretty vital for me to know about "data quality".

Greetings!

**Comment by cqcn1991** [comment]
hi, i'm sorry if i missed your concern. let me give you some idea

1. aggtrades vs. trades. how are they deifferent; which one is better in terms of quality? which one should i use?

- difference: please refer to `https://binance-docs.github.io/apidocs/futures/en/#compressed-aggregate-trades-list` 

`Get compressed, aggregate trades. Trades that fill at the time, from the same order, with the same price will have the quantity aggregated.`

- data quality: the historical datasets you're using, both are pull from the source directly; and we strive our best to ensure its quality (but does not mean there're no bugs), it's all ways in improving mode and at this stage, the quality is a lot better than we initally released. theoretically, aggtrades has been aggregate, so the aggregate can have some issue, that makes trades of higher quality; but that issue is rather rare.

- choice recom: i personally recom you use aggtrades; because it's only published through websocket (no trades publised through ws) https://binance-docs.github.io/apidocs/futures/en/#aggregate-trade-streams . that gurantee you're using as close to live data. 

2. which kline to use?
they're of the same quaility, should be same as what you get from rest api. so just use which one you prefer.

3. for the `huge difference issue`
this has 2 part
- the original `time` vs `1 min`. as answered . `time` only shows the `close` price. so you didnt get the `high` price
- the conflict between your 2 screenshot. we don't know if there is any issue, and we have not get similar feedback, and i don't think we have done any fix to this. so it might just be some accident. if you see similar issue again, let's work on it together as we might need your help to look into it (to reproduce the issue). 

hope this helps. and any other question i can help?

zk.

**Comment by GBC999** [comment]
Hi cqcn1991,

thanks for your answer. some questions/remarks back.

> which kline to use?
they're of the same quaility, should be same as what you get from rest api. so just use which one you prefer.

Well I should have written my question more clear. The erroneous "Time" data on the website was/is a 1-min Kline.
And no the error consisted for several days and now its gone. The question is now: if the 1min compressed data on site is wrong its probably not a good idea to download the 1min data, or? **Could you give me a recommendation regarding 1min Monthly Klines vs 5min Klines which one is better.** In case i don't want to aggregate the data always by myself. I know you will probably answer that they are the 'same', and if that's the only answer you can give, so be it, but my gut feeling is this: "Somewhere in the process the 1-min data is handled differently, therefore all the wrong values for OHLC in the candle of 1:02.  **Any input appreciated.**

> the original time vs 1 min. as answered, time only shows the close price. so you didn't see the high price.
Well this is true (i didn't want to bloat my answer to much since it becomes bigger and bigger), but only for the 1:01 Candle. 
    
> the conflict between your 2 screenshots. we don't know if there is any issue, and we have not get similar feedback, and i don't think we have done any fix to this.
I think i disagree here The error in the 1:02 Candle consisted for days. Every time i checked it. I mean every value of this candle was wrong Open was wrong, High was wrong low was wrong, Close was crazy wrong, i filtered for the close (just as example) it doesn't even exist around that timestamp in the data. It only exists about 17h later (!):
https://ibb.co/z6f9MPc

how did that even get in a candle of 1:02? its about 1000 1-min Intervals later?
Or do you think its somehow a problem of the the browser showing the data?
And it has been fixed now, I checked yesterday i checked today twice. It's consistently right. So it seems that somebody did something. But it would be important to know if it just has been manually reset to the values i posted for this one candle or if the problem has been found/what it was. Since this is just one candle i stumbled across by accident there might be thousands of candles with this problem otherwise. 

Besides that the data has a lot of Problems sometimes the sorting is not right, the first candle of a downloaded file is often twice...
It is especially worth looking into the process how the data gets there..

> if you see similar issue again, let's work on it together. as we might need your help to look into it (to reproduce the issue).
Yes definitely agree here. 

Have a good one!

**Comment by cqcn1991** [comment]
so first, `data has a lot of Problems sometimes the sorting is not right, the first candle of a downloaded file is often twice...` please give us the file you get, and we 'll look into the issue; that can help us and everyone using the data to have a better quality. improving data quality is a process, and we need your help. 

`Could you give me a recommendation regarding 1min Monthly Klines vs 5min Klines which one is better`. we can answer this after you give us specific example. apart from this, they are the same.

` Or do you think its somehow a problem of the the browser showing the data?`. that's my guess. but we don't know. to pinpoint issue we have to re-produce it, but now we can't so we have no idea. my guess is based on 

(1) you get the data correct in your screenshot first time, and later wrongly, and now correct again. but we don't re-produce kline data repetitively; it's produced and then leave as it is. so might be some downstream api/connection issue.

(2) we don't have other sources reporting the same issue (as the the impact of such issue is huge; we would get tons of question on this). but that seems a single case for you.

**Comment by GBC999** [comment]
Hi cqcn1991, 
thanks for your answer! But i don't have more time to test, look up stuff.  My expectation was more i put in 3-5h (put in much more anyways) you guys put in 15-20h to find /fix it. Not the other way round.

But i did learn some stuff out of this (that the Grey numbers show the highest close and not the highest High - which would be better actually, since liquidation for a margin product will be on highest High and not Highest close, but good to know).

A bit unsatisfying is that we don't know what caused this: 

> Time shows for the close: 39 525.6
> I downloaded the trades and AggTrades data for the 26th I couldn't find 39 525.6 anywhere in there??Intuitively i thought trades would be EVERY trade that occured on that day. But i don't know then where "Time" gets this value from.
> 
> I then importet the data in a database tool. One can see that the last trade (aka close) in the time interval from 1:02 - 1:02:59.999 h should be 39 625.76 and not 39 525.6:
> https://ibb.co/Gd8qhw6
> 
> Another example is the High value for the interval which is shown with 40 050.6 but if i take the maximum price of all trades in the Interval from 01:02:00.000- 01:02:59:999h in the database tool:
> https://ibb.co/C9xwMjj
> with 44 000 a very different value

> The other values don't match too.
> If i had to guess, database tools often have a setting like "Maximum different values per group" when grouping the data for the klines. Its often set to 10K values maybe this caused this? 

but that's how it is life sometimes i guess.

> we don't have other sources reporting the same issue (as the the impact of such issue is huge; we would get tons of question on this). but that seems a single case for you.

For some reason i want to write out my thoughts on this: Honestly i don't think so. I think there are 2 types of people using your site: A) the traders who just look at the charts and trade based on "gut feeling" /Indicator on the fly etc. And B) the people downloading data and building models. But its not really happening that an "model builder" person downloads the data and compares it to the charts on the website: they simply don't care what a chart on a website shows. The traders don't download data. I mean think about it who downloads data, aggregates it in a database tool on his own and compares it to the Chart?? On top of that people usually just trust data. I have seen this a lot in the last 10 years (I am not a programmer but i usually find the mistakes in data) That people use erroneous data for 5+ years because they never really check it. In fact i just stumbled across this by coincidence: The "amazon spike" caused my interest to look at this in the charts and then saw that something is not right... It was a pure accident.

Anyways i think this thread can be closed, its to much all-over the place, to much different topics in one thing.

If i find something again/ something else in testing i make a new thread it will be cleaner and more on a single point - i think that's better

Have a good day!

**Comment by 2pd** [comment]
let's open new issue for any concern.

**Comment by volkan-akkus-tr** [comment]
Hi @GBC999,

How did you solve your issues?
