### ISSUE TITLE
Provide historical market depth data as well

### ISSUE THREAD

**Issue by RastislavMirek** [binance/binance-public-data#6]
Order book depth data can be very  relevant for algorithmic trading. Therefore, it would be highly useful for API customers and algorithmic traders  if you provided historical order book depth data as well.

Understandably, these data can get **very** large indeed. I suggest this approach to keep the data size reasonable while providing high quality data for algorithmic trading:

1. Provide order book snapshot at each End of Day.
2. Provide incremental updates to order book during the day analogical to [diff depth stream](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#diff-depth-stream).
3. The frequency of updates may vary depending on how active is the pair. For ETHBTC, one second updates seems to be appropriate, for less active pairs one update per 10 seconds may be enough.

The order book may be reasonably aggregated e.g. by price levels to further decrease the data size. Such aggregation would be deployed before most algorithmic trading applications anyway.

**Comment by 2pd** [comment]
thank you for your feedback, we have this in the plan, but for now we will focus on klines, trades, aggTrades data.

**Comment by RastislavMirek** [comment]
> thank you for your feedback, we have this in the plan, but for now we will focus on klines, trades, aggTrades data.

Thank you for information. If this is a case, it is a good general practice to keep this issue open until the data are added.

One of the advantages of such a best practise for you is that others will see my request here and thus they will not open duplicated issues. Plus, I would really appreciate it for my own reference as well.

**Comment by p-i-** [comment]
Is there any resource one can get historical orderbook data?
It's a LOT of data!
But very juicy! 😋

**Comment by 2pd** [comment]
yes, that's a lot of data. It's in plan.

**Comment by Karlheinzniebuhr** [comment]
👁
