### ISSUE TITLE
Is it posible to download daily klines before March 2021?

### ISSUE THREAD

**Issue by emseider** [binance/binance-public-data#60]
I was trying to download BTCUSDT daily klines from the past year (2020) but I realize I can downloaded them only from March 01 2021. Is any one knows if there is some delete strategy from Binance? or the data hasn't uploaded yet?  I just want to prevent this behavior into my scripts since I have a Date Range feature.

**Comment by cqcn1991** [comment]
spot or futures? and what you mean `daily`?

if it's futures, and you mean `1d` interval; you can get from https://data.binance.vision/?prefix=data/futures/um/monthly/klines/BTCUSDT/1d/

**Comment by emseider** [comment]
> spot or futures? and what you mean `daily`?
> 
> if it's futures, and you mean `1d` interval; you can get from https://data.binance.vision/?prefix=data/futures/um/monthly/klines/BTCUSDT/1d/

SPOT
Example:
https://data.binance.vision/data/spot/daily/klines/BNBUSDT/5m/BNBUSDT-5m-2019-01.zip
Just change /monthly/ by /daily/

**Comment by 2pd** [comment]
We support only limited daily data for download. 
You may wish to split them from monthly files, which includes all available klines.
