### ISSUE TITLE
Where to find futures data *.csv files columns description?

### ISSUE THREAD

**Issue by Warlib1975** [binance/binance-public-data#62]
Hi,

in a readme file, there are no columns descriptions for USD-M futures Trades and aggTrades *.csv files. Where it could be possible to get columns descriptions of these files?

Thank you.

**Comment by cqcn1991** [comment]
got it. i'll add it later. 

for now, you can refer 
https://binance-docs.github.io/apidocs/futures/en/#old-trades-lookup-market_data
https://binance-docs.github.io/apidocs/futures/en/#compressed-aggregate-trades-list

the cols are used in order with the api endpoints.
