### ISSUE TITLE
[Request] Add historical tick size

### ISSUE THREAD

**Issue by qbx2** [binance/binance-public-data#71]
Tick sizes are continuously updated by binance and I don't know any specific formula to calculate it.
I want to simulate trading with old klines data in an environment which places bid order with 1 higher price tick, and ask order with 1 lower price tick.
I found that binance has announced price tick updates on [here](https://www.binance.com/en/support/search?type=1&q=Tick%20Size), it is hard to crawl & parse however.
It should be great if historical tick size data is provided in here.

**Comment by qbx2** [comment]
If it can't be provided, any rough rule to determine tick size should be useful, too.
Is there definite maximal value of `tick_size/price` ?

**Comment by cqcn1991** [comment]
sorry, we don't have history data for this, and there is no deterministic rule for setting the tick size.
