### ISSUE TITLE
Does data site support multi-task to download file simutaneously?

### ISSUE THREAD

**Issue by inix** [binance/binance-public-data#73]
Hi:
Does data site support multi-task or multi thread to download file simutaneously?

I just modify your python codes to support multi threading using asyncio,but connection will timeout after about 30 minutes.

Thanks.

**Comment by 2pd** [comment]
the data zip files are hosted in aws s3, there may be some restriction from them for multi threading downloading.

**Comment by inix** [comment]
> the data zip files are hosted in aws s3, there may be some restriction from them for multi threading downloading.

I see.
Thanks.
