### ISSUE TITLE
May I ask what kind of future data do you provide?

### ISSUE THREAD

**Issue by AntonotnaWang** [binance/binance-public-data#75]
To whom it may concern,

May I ask what kind of future data is shown in https://data.binance.vision/?prefix=data/futures/? Are they perpetual or delivery? Thanks a lot.

Best

**Comment by cqcn1991** [comment]
> https://data.binance.vision/?prefix=data/futures/

as you can see here 

![image](https://user-images.githubusercontent.com/2425141/133380706-b1b40a38-30a0-482e-aa4a-894900d24690.png)

https://data.binance.vision/?prefix=data/futures/um/monthly/klines/

both delivery and perpetual are provided.

**Comment by AntonotnaWang** [comment]
> > https://data.binance.vision/?prefix=data/futures/
> 
> as you can see here
> 
> ![image](https://user-images.githubusercontent.com/2425141/133380706-b1b40a38-30a0-482e-aa4a-894900d24690.png)
> 
> https://data.binance.vision/?prefix=data/futures/um/monthly/klines/
> 
> both delivery and perpetual are provided.

Dear cqcn1991,

May I ask which is delivery and which is perpetual? Does "BTCUSDT 210326" mean a delivery future of BTCUSDT ending at 21-03-26? And "BTCUSDT" means perpetual future? Thanks a lot.

Best

**Comment by cqcn1991** [comment]
> May I ask which is delivery and which is perpetual? Does "BTCUSDT 210326" mean a delivery future of BTCUSDT ending at 21-03-26? And "BTCUSDT" means perpetual future? Thanks a lot.
> 
> Best

yes, it's the symbol name you see in our trading page. 

![image](https://user-images.githubusercontent.com/2425141/133389412-0c72290e-13cb-43cd-98da-36be08087cf1.png)

**Comment by AntonotnaWang** [comment]
> > May I ask which is delivery and which is perpetual? Does "BTCUSDT 210326" mean a delivery future of BTCUSDT ending at 21-03-26? And "BTCUSDT" means perpetual future? Thanks a lot.
> > Best
> 
> yes, it's the symbol name you see in our trading page.
> 
> ![image](https://user-images.githubusercontent.com/2425141/133389412-0c72290e-13cb-43cd-98da-36be08087cf1.png)

Thanks a lot.

**Comment by AntonotnaWang** [comment]
> > May I ask which is delivery and which is perpetual? Does "BTCUSDT 210326" mean a delivery future of BTCUSDT ending at 21-03-26? And "BTCUSDT" means perpetual future? Thanks a lot.
> > Best
> 
> yes, it's the symbol name you see in our trading page.
> 
> ![image](https://user-images.githubusercontent.com/2425141/133389412-0c72290e-13cb-43cd-98da-36be08087cf1.png)

I found that the code cannot automatically download different kinds of futures of BTCUSDT if only "BTCUSDT" was typed. Thus, I added a new function to utility.py to order to download all the items containing "BTCUSDT". Maybe it helps.

```
import urllib
import xml.etree.ElementTree as ET

def getResponse(url):
    operUrl = urllib.request.urlopen(url)
    if(operUrl.getcode()==200):
        data = operUrl.read()
    else:
        print("Error receiving data", operUrl.getcode())
    return data

def get_all_related_symbols(trading_type, market_data_type, time_period, symbol):
    trading_type_path = 'data/spot'
    if trading_type != 'spot':
        trading_type_path = f'data/futures/{trading_type}'
    path = f'{trading_type_path}/{time_period}/{market_data_type}/'
    
    info = getResponse("https://s3-ap-northeast-1.amazonaws.com/data.binance.vision?delimiter=/&prefix="+path)
    info_tree = ET.fromstring(info)
    
    related_symbols = []
    for item in info_tree.iter():
        if "Prefix" in item.tag and \
        item.text is not None and \
        item.text.split("/")[-2] != path.split("/")[-2] and \
        symbol in item.text.split("/")[-2]:
            related_symbols.append(item.text.split("/")[-2])
    
    return related_symbols
```
