### ISSUE TITLE
Errors in klines data

### ISSUE THREAD

**Issue by NklDnn** [binance/binance-public-data#77]
Hello!

There are several dramatic errors in historical klines data:

Check and correct please next periods and timeframes:

BTCUSDT-1h-2018-01

Kline open time is 1515034800000. Kline close time is 1515034814838 instead of 1515038399999.

Kline open time is 1515042000000. Previous kline open time is 1515034800000. The difference is 7200000, thus there is one kline missing.

BTCUSDT-1h-2018-02

Kline open time is 1518048000000. Kline close time is 1518049694788 instead of 1518051599999.

Kline open time is 1518168494789. Previous kline open time is 1518048000000. The difference is 120494789, thus there are about 34 klines missing.

Kline open time is 1518319694789. Kline close time is 1518321600999 instead of 1518323294788.

Kline open time is 1518321600000. Previous kline open time is 1518319694789. The difference is 1905211, thus there is something weird in this kline.

BTCUSDT-1h-2018-06

Kline open time is 1530014400000. Previous kline open time is 1529974800000. The difference is 39600000, thus there are 11 klines missing.

Kline open time is 1530108000000. Previous kline open time is 1530100800000. The difference is 7200000, thus there is 1 kline missing.

BTCUSDT-1h-2018-07

Kline open time is 1530662400000. Kline close time is 1530663745551 instead of 1530665999999.

Kline open time is 1530691200000. Previous kline open time is 1530662400000. The difference is 28800000, thus there are about 8 klines missing.

BTCUSDT-1h-2018-10

Kline open time is 1539939600000. Previous kline open time is 1539925200000. The difference is 14400000, thus there are about 4 klines missing.

BTCUSDT-1h-2018-11

Kline open time is 1542186000000. Previous kline open time is 1542157200000. The difference is 28800000, thus there are about 8 klines missing.

BTCUSDT-1h-2019-03

Kline open time is 1552377600000. Previous kline open time is 1552352400000. The difference is 25200000, thus there are about 7 klines missing.

BTCUSDT-1h-2019-05

Kline open time is 1557925200000. Previous kline open time is 1557885600000. The difference is 39600000, thus there are about 11 klines missing.

BTCUSDT-1h-2019-08

Kline open time is 1565863200000. Previous kline open time is 1565830800000. The difference is 32400000, thus there are about 9 klines missing.

BTCUSDT-1h-2019-11

Kline open time is 1573617600000. Previous kline open time is 1573606800000. The difference is 10800000, thus there are about 3 klines missing.

Kline open time is 1574654400000. Previous kline open time is 1574643600000. The difference is 10800000, thus there are about 3 klines missing.

BTCUSDT-1h-2020-02

Kline open time is 1581217200000. Previous kline open time is 1581210000000. The difference is 7200000, thus there are about 2 klines missing.

Kline open time is 1582131600000. Previous kline open time is 1582110000000. The difference is 21600000, thus there are about 6 klines missing.

BTCUSDT-1h-2020-03

Kline open time is 1583312400000. Kline close time is 1583313706694 instead of 1583315999999. Therefore there is an error in kline data.

Kline open time is 1583319600000. Previous kline open time is 1583312400000. The difference is 7200000, thus there are about 2 klines missing.

BTCUSDT-1h-2020-04

Kline open time is 1587787200000. Previous kline open time is 1587776400000. The difference is 10800000, thus there are about 3 klines missing.

BTCUSDT-1h-2020-06

Kline open time is 1593320400000. Previous kline open time is 1593306000000. The difference is 14400000, thus there are about 4 klines missing.

BTCUSDT-1h-2020-11

Kline open time is 1606719600000. Previous kline open time is 1606712400000. The difference is 7200000, thus there are about 2 klines missing.

BTCUSDT-1h-2020-12

Kline open time is 1608559200000. Smth weird with this kline data – Volume is 0,  looks like kline data is incorrect. BTW close time is 1608558440521, which is earlier than open time.

Kline open time is 1608573600000. Previous kline open time is 1608559200000. The difference is 14400000, thus there are about 4 klines missing.

Kline open time is 1608865200000. Previous kline open time is 1608858000000. The difference is 7200000, thus there are about 2 klines missing.

BTCUSDT-1h-2021-02

Kline open time is 1583312400000. Kline close time is 1583313706694 instead of 1583315999999. Therefore there is an error in kline data. BTW there is an error in volume value.

Kline open time is 1613019600000. Previous kline open time is 1613012400000. The difference is 7200000, thus there are about 2 klines missing.

BTCUSDT-1h-2021-03

Kline open time is 1614999600000. Previous kline open time is 1614992400000. The difference is 7200000, thus there are about 2 klines missing.

BTCUSDT-1h-2021-04

Kline open time is 1618891200000. Previous kline open time is 1618880400000. The difference is 10800000, thus there are about 3 klines missing.

Kline open time is 1619323200000. Kline close time is 1619323258146 instead of 1619326799999. Therefore there is an error in kline data.

Kline open time is 1619337600000. Previous kline open time is 1619323200000. The difference is 14400000, thus there are about 4 klines missing.

BTCUSDT-1h-2021-08

Kline open time is 1628834400000. Previous kline open time is 1628816400000. The difference is 18000000, thus there are about 5 klines missing.

BTCUSDT-4h-2018-02

Kline open time is 1518163200000. Previous kline open time is 1518048000000. The difference is 115200000, thus there are about 32 klines missing.

BTCUSDT-4h-2018-06

Kline open time is 1529971200000. Kline close time is 1529978399999 instead of 1529985599999. Therefore there is an error in kline data.

Kline open time is 1530014400000. Previous kline open time is 1529971200000. The difference is 43200000, thus there are about 12 klines missing.

BTCUSDT-4h-2018-07

Kline open time is 1530662400000. Kline close time is 1530663745551 instead of 1530676799999. Therefore there is an error in kline data.

Kline open time is 1530691200000. Previous kline open time is 1530662400000. The difference is 28800000, thus there are about 8 klines missing.

BTCUSDT-4h-2018-11

Kline open time is 1542153600000. Kline close time is 1542160799999 instead of 1542167999999. Therefore there is an error in kline data.

Kline open time is 1542182400000. Previous kline open time is 1542153600000. The difference is 28800000, thus there are about 8 klines missing.

BTCUSDT-4h-2019-03

Kline open time is 1542153600000. Kline close time is 1552355999999 instead of 1552363199999. Therefore there is an error in kline data.

Kline open time is 1552377600000. Previous kline open time is 1552348800000. The difference is 28800000, thus there are about 8 klines missing.

BTCUSDT-4h-2019-05

Kline open time is 1557878400000. Kline close time is 1557889199999 instead of 1557892799999. Therefore there is an error in kline data.

Kline open time is 1557921600000. Previous kline open time is 1557878400000. The difference is 43200000, thus there are about 12 klines missing.

BTCUSDT-4h-2019-08

Kline open time is 1565827200000. Kline close time is 1565834399999 instead of 1565841599999. Therefore there is an error in kline data.

Kline open time is 1557921600000. Previous kline open time is 1565827200000. The difference is 28800000, thus there are about 8 klines missing.

BTCUSDT-4h-2020-02

Kline open time is 1582099200000. Kline close time is 1582112132286instead of 1582113599999. Therefore there is an error in kline data.

Kline open time is 1582128000000. Previous kline open time is 1582099200000. The difference is 28800000, thus there are about 8 klines missing.

 I very ask you to fix that asap.

Looking forward for corrected data, thank you!

**Comment by NklDnn** [comment]
![image](https://user-images.githubusercontent.com/91590784/135392176-6a1190f8-6c65-44f0-88d8-5c7182a5259b.png)
![image](https://user-images.githubusercontent.com/91590784/135392212-a469c3dd-fc90-4f7d-bcdf-4b71a1002e92.png)

For instance look at first bullet of my message.
BTCUSDT-1h-2018-01

Kline open time is 1515034800000. Kline close time is 1515034814838 instead of 1515038399999.

Kline open time is 1515042000000. Previous kline open time is 1515034800000. The difference is 7200000, thus there is one kline missing.

On the attached prtscrns u can see, that even in Binance Desktop there is 1 kline missing

**Comment by 2pd** [comment]
Some of the klines are missing due the server maintenance, when there is no trading.
For zip data hosted in this project are downloaded from the endpoint /api/v3/klines. As we checked,  all of the concerns above are not an issue of the downloading, they are not existing in the API server.

**Comment by NklDnn** [comment]
Ok, why then there is a discrepancy in start kline?
Look please at BTCUSDT-1h-2018-01. 
The first kline open time is 1514764800000 in downloaded data.
However, the actual open time of 2018-01 in accordance with trading view in Binance App is 1514754000000 and this is how should be in downloaded data. 
Why 3 klines are missing?(

**Comment by nitko12** [comment]
Just stumbled upon this,

I'm trying to query all the klines who have time <= x <= close_time for some arbitrary x fast,

but for a low of pairs timestamp 1608559200000 has closing time which are before it.

Probably won't be a problem for me bu letting you know :)
