### ISSUE TITLE
Missing data for BTCUSDT

### ISSUE THREAD

**Issue by yivanov-it** [binance/binance-public-data#84]
Have some missing data in zip files - 
maybe miss something else
Missed here (as example) - https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1m/BTCUSDT-1m-2020-02.zip
All missed data in file:
[empty_data.csv](https://github.com/binance/binance-public-data/files/7463356/empty_data.csv)

**Comment by 2pd** [comment]
This folder contains the 1m klines in Feb 2020, can you point out which kline is missing?

**Comment by yivanov-it** [comment]
In Feb 2020 missed from 1582112100000 till 1582133400000
List of all missed timestamps in attached file before

**Comment by yakobsoahmin00** [comment]
https://github.com/binance/binance-public-data/issues/84#issuecomment-958945591

**Comment by 2pd** [comment]
https://www.binance.com/en/support/announcement/360039984971
there was a system maintenance during the time.
