### ISSUE TITLE
General question regarding aggregateTradeId

### ISSUE THREAD

**Issue by yohplala** [binance/binance-public-data#85]
Hi,
I compared file format between spot and futures (um) for ADABUSD pair.
I noticed that the 1st aggregateTradeId does not start at same index:
 - 0 for spot : https://data.binance.vision/data/spot/monthly/aggTrades/ADABUSD/ADABUSD-aggTrades-2019-11.zip
 - 1 for futures (um): https://data.binance.vision/data/futures/um/monthly/aggTrades/ADABUSD/ADABUSD-aggTrades-2021-08.zip

It is certainly a detail, but I prefer to enquire:
 is this normal or might there be a hole in data with the very 1st aggregate trade in ADABUSD futures data?

Thanks in advance for the feedback,
Bests

**Comment by 2pd** [comment]
there is no wrong in these data, 0 for spot and 1 for UM.
