### ISSUE TITLE
Missing data in monthly files

### ISSUE THREAD

**Issue by ghostoid** [binance/binance-public-data#86]
Hi. 
Files
https://data.binance.vision/data/spot/monthly/trades/SHIBBUSD/SHIBBUSD-trades-2021-10.zip
https://data.binance.vision/data/spot/monthly/trades/SHIBUSDT/SHIBUSDT-trades-2021-10.zip
are not full.
SHIBBUSD ends with 2021-10-21 without 3 last hours of a day
and SHIBUSDT ends with 2021-10-27 without 3 last hours of a day

**Comment by 2pd** [comment]
This has been fixed, please download last month data again.
The app had an issue processing `SHIB*` data that is larger than expected, we will improve it and upload the complete dataset next time.

Thanks again for your feedback.
