### ISSUE TITLE
question about API request limit

### ISSUE THREAD

**Issue by lderoose** [binance/binance-public-data#9]
Are there any limitations on the number of requests to make to the Binance API please?

I have seen this:

`{
  "rateLimitType": "REQUEST_WEIGHT",
  "interval": "MINUTE",
  "intervalNum": 1,
  "limit": 1200
}
{
  "rateLimitType": "ORDERS",
  "interval": "SECOND",
  "intervalNum": 1,
  "limit": 10
}
{
  "rateLimitType": "RAW_REQUESTS",
  "interval": "MINUTE",
  "intervalNum": 5,
  "limit": 5000
}`
 here https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md

but I don't see anything special in download-kline.py about.

Thank you

**Comment by 2pd** [comment]
- If you fetch kline data from Binance API endpoint directly, aka `/api/v3/kline`, you will need to follow the request limit as state from the API document.
- If you download the kline data as `.zip` file, there is no limit. ( It's hosted in cloud storage).
