### ISSUE TITLE
BTCUSD Trimestral 220325 Historical Data

### ISSUE THREAD

**Issue by fedebelo** [binance/binance-public-data#92]
Is there a way to access the historical data of "BTCUSD Trimestral 220325"?
[Binance Market Data](https://data.binance.vision/?prefix=data/futures/cm/monthly/klines/BTCUSD_220325/1d/) only has from 2021/09/23 to 2021/10/30 but in [binance](https://www.binance.com/es/delivery/BTCUSD_BI-QUARTER) the graphs have historical information starting from 2020/06/30.

**Comment by 2pd** [comment]
- `BTCUSD_220325` trading symbol details can be found the endpoint `dapi/v1/exchangeInfo`, it's onboard date is on September.

```json
{
            "symbol": "BTCUSD_220325",
            "pair": "BTCUSD",
            "contractType": "NEXT_QUARTER",
            "deliveryDate": 1648195200000,
            "onboardDate": 1632470400000,
            "contractStatus": "TRADING",
            "contractSize": 100,
            "marginAsset": "BTC",
            "maintMarginPercent": "2.5000",
            "requiredMarginPercent": "5.0000",
            "baseAsset": "BTC",
            "quoteAsset": "USD",
            "pricePrecision": 1,
            "quantityPrecision": 0,
            "baseAssetPrecision": 8,
            "quotePrecision": 8,
            "equalQtyPrecision": 4,
            "maxMoveOrderLimit": 10000,
            "triggerProtect": "0.0500",
            "underlyingType": "COIN",
            "underlyingSubType": [],
}
```

-  The monthly data of Nov is not uploaded until the beginning of Dec.
