### ISSUE TITLE
All Book Tickers Stream timestamp

### ISSUE THREAD

**Issue by pantonis** [binance/binance-public-data#94]
Hello,

Using the websocket market data stream for All Book Tickers how do I find the timestamp for each bid/ask received?

Thanks

**Comment by GedeanJohn** [comment]
Good afternoon for somebody in UTC -3!!!

Which timeStamp format is for column "time" in "SPOT - Trades"?

Thank you for helping me.

**Comment by 2pd** [comment]
https://en.wikipedia.org/wiki/Unix_time

timestamp at Binance is 13 digits, in milliseconds.

Please open topic at dev.binance.vision for API related questions.
