### ISSUE TITLE
Be nice to have  a python package on pypi

### ISSUE THREAD

**Issue by dougransom** [binance/binance-public-data#98]
Be nice to have a python package that can be installed from pypi, and some commands in the python scripts folder so the user doesnt have to type `python download...`.

**Comment by dougransom** [comment]
#97 has the python packaging ready.  You can run `flit build` to build it and `flit publish` to push to pypi.  Flit is a more modern way than setuptools to make a python package.

**Comment by 2pd** [comment]
Thank you @dougransom  for your feedback and suggestion, it's a nice idea.

This repo is focusing on giving more general information about the Binance public data. For the tool/script to download those data, we may build it into a separate repo and upload to pypi.

**Comment by dougransom** [comment]
@2pd Did you see the pull request in #97?  Very easy since i barely changed the scripts, just added the packaging.

**Comment by dougransom** [comment]
If anyone in interested, a fork can make a Python dataframe after downloading the files has been published on  [https://pypi.org/project/binance_pandas_dataframe/(https://pypi.org/project/binance_pandas_dataframe/).
